### ISSUE TITLE
Shouldn't deluged / deluge-web listen on the docker interface?

### ISSUE THREAD

**Issue by dprus** [binhex/arch-delugevpn#1]
It seems like deluged and deluge-web are being set to listen on the VPN interface. I see OpenVPN getting a 10.8.*.* IP yet the container->docker host interface is 172.*.*.*. Why wouldn't deluged and deluge-web listen on the container->docker host interface?

**Comment by dprus** [comment]
So what I'm seeing in the log is this:
```
Deluge listening interface IP and OpenVPN local IP 10.8.x.x different, configuring Deluge...
```
This appears to be when deluge is changed to listen on the VPN interface instead of the container->docker interface. When this happens my -p 8112:8112 I passed to "docker run" seems to be pointless because deluge isn't actually listening there anymore.

**Comment by dprus** [comment]
So it turns out the issue I was having was that my Synology NAS doesn't load the iptable_mangle and xt_mark kernel modules by default. After loading them up I was able to connect to the web UI. Your image appears to work great :) Thanks for the hard work!

**Comment by sambub** [comment]
@dprus I'm trying to install this on a DS713+ via Docker and facing the same issues. How did you include the iptable_mangle and xt_mark? Would love some tips on getting this running!

**Comment by dprus** [comment]
Hi @sambub ,

I simply SSH'd into my Synology and issued the following commands:
```
insmod /lib/modules/tun.ko
insmod /lib/modules/iptable_mangle.ko
insmod /lib/modules/xt_mark.ko
```

**Comment by sambub** [comment]
Thank you Richard for your reply. I'll try this out!

**Comment by Ryanb58** [comment]
@dprus Just confirmed this worked on my DS918+
