### ISSUE TITLE
Q: Why are the PUID/PGID stored in /tmp instead of /config?

### ISSUE THREAD

**Issue by gangefors** [binhex/arch-delugevpn#101]
[Storing these values in /tmp](https://github.com/binhex/arch-delugevpn/blob/6eb63ae35264d6a59683b7cce26a0bc8b545b914/build/root/install.sh#L104) will make them inaccessible on upgrades since we are creating a new container. Storing them in /config would make upgrading much faster for large shares.

I might be missing the reasoning behind storing them in /tmp, but to me it feels like the values are something that one wants to save between upgrades. No need to chown if all files are already owned by the correct account.

Or it would be nice to have a flag one could set to skip chowning the /data folder. This is most likely stored on a host mounted volume where I have full control of the files and can chown if needed.

Thanks for awesome images.

**Comment by binhex** [comment]
As your so rightly pointed out updating does mean creating a new container, and thus a chmod and chown must be done on certain folders INSIDE the container, this does not change permissions for files external to the container i.e. /data

**Comment by gangefors** [comment]
But how come this is done on /data every time I start up a new container even if I use the same /config volume?

What I want to avoid doing is that the continer does a chmod on my 1M files large /data volume. It's totally ok that it does this for the /config volume but it should not be needed on /data unless I specifically tell it to on upgrades.

If the files were stored in /config a user could force a re-chown on all volumes if needed. But as it is now it happens every time I start a new container.

I have found a workaround by starting the container, then enter the now running container with docker exec and from inside create these files in /tmp. Then immediately restart the container which now starts up without chowning /data.

**Comment by gangefors** [comment]
I'll see if I can dig out some old logs. Cause when I lauched it yesterday it did do a chown on /data.

**Comment by gangefors** [comment]
I'm using 1.3.15_14_gb8e5ebe82-1-23

When I launch the container for the first time with fresh /confg volume the following is shown in the log.

`2019-04-06 14:59:29.465442 [info] Setting permissions recursively on volume mappings...`

If I check the processes running in the container at that point I see this.

`root                10627               10431               3                   15:04               ?                   00:00:00            chown -R 1026:100 /config /data`

So something is running chown on /data. I can't find the log output in the git repo by searching. So I searched for chown and found the one I referred to before. But that doesn't seem to refer to the chown I see running in the container because install_paths="/etc/privoxy,/home/nobody".

But something is doing it and I want it to not do that when I launch my container.

**Comment by binhex** [comment]
I'm not sure what to say, there is no code to chmod/chown either /config or /data are you sure you are running my code and not a fork?.

Btw you are behind on the releases so I would encourage you to go with the latest.

**Comment by gangefors** [comment]
I found the source to this issue.

https://github.com/binhex/scripts/blob/4a2be13f06a46064b6ddea9842577c97fecb4fc1/shell/arch/docker/init.sh#L60

But it do have a file it checks in the /config folder.  So this is failry easy to bypass, if one knew about it.

It would be helpful if this was documented since running chown/chmod on first run is a waste of time if the user already have the correct permissions and ownership of the files.

**Comment by binhex** [comment]
That file is persistent as it's stored in /,config so it should only run once unless your delete the file

**Comment by gangefors** [comment]
I know that now. But it's not very clear that one can skip it for the first run as well.

Another way to skip it is to not use the /data directory as the data volume and instead go with another host mounted directory.

For my when I experimented with this container using a docker volume it took me 15 minutes each launch since I sometimes wanted to reset the config volume. It was extremely annoying since it was not documented how to disable that check.

**Comment by gangefors** [comment]
If you want I can do a PR for the docs so that part becomes clear. But I guess that PR must be applied to all git repos with docker images that are based on your base image. So it could be quite a task since you ahve quite a few images to maintain. :)

**Comment by binhex** [comment]
Ideally the /data volume mapping should be pointing to a empty folder with no sun directories, its not meant to contain your media collection, it's supposed to store incomplete and completed etc, specific to deluge.

Having said that I take your point about additional documentation and will have a look at adding in a section regards perms.txt
