### ISSUE TITLE
Unable to access GUI, not connecting to VPN 

### ISSUE THREAD

**Issue by shresth45** [binhex/arch-delugevpn#102]
After running the docker-compose file, I'm unable to access the GUI for deluge. If I change the VPN_ENABLED flag to false, then I'm able to access the GUI. This issue is replicated both through the docker run command on https://hub.docker.com/r/binhex/arch-delugevpn/ as well as through docker-compose. I've attached the complete supervisord.log file below. DEBUG=true.

In the logs, I'm seeing the following

2019-04-06 22:09:54,120 DEBG 'start-script' stdout output:
Sat Apr  6 22:09:54 2019 NOTE: the current --script-security setting may allow this configuration to call user-defined scripts
Sat Apr  6 22:09:54 2019 TCP/UDP: Preserving recently used remote address: [AF_INET]82.102.24.164:1198
Sat Apr  6 22:09:54 2019 UDP link local: (not bound)
Sat Apr  6 22:09:54 2019 UDP link remote: [AF_INET]82.102.24.164:1198

Complete supervisord.log 
https://pastebin.com/1TjLh42u

My docker-compose file is as below:
https://pastebin.com/TqDa3exA

**Comment by binhex** [comment]
It looks like something on your lab is blocking access to the Swiss pia endpoint, check host firewall, hardware firewall, vlan etc

**Comment by shresth45** [comment]
Hello.
As per your suggestion, I have modified the firewall rules for the vlan to allow port 1198.

I am now getting the following output in the logs, though still cannot access the GUI
delugevpn           | 2019-04-08 10:50:43,903 DEBG 'watchdog-script' stdout output:
delugevpn           | [info] No torrents with state 'Error' found
delugevpn           |
delugevpn           | 2019-04-08 10:50:43,904 DEBG 'watchdog-script' stdout output:
delugevpn           | [info] Starting Deluge Web UI...
delugevpn           | [info] Deluge Web UI started

The container as well as its files were wiped and recreated. Full supervisord.log below 
https://pastebin.com/8zkiy7TN

Firewall rules for the vlan = allow outbound ports 53,123,80,443,1198.
Host firewall = allow 8112, 8118 among others
Please let me know if any further changes are necessary.

**Comment by binhex** [comment]
The lan_network is incorrectly configured,.

**Comment by shresth45** [comment]
Changed Lan_network to 10.10.0.0/16, and it is finally running successfully. Thank you!
