### ISSUE TITLE
Cannot get webgui to work

### ISSUE THREAD

**Issue by erfly7** [binhex/arch-delugevpn#103]
Cannot get webgui to load no matter what localhost 8112 not available

**Comment by thebosspt** [comment]
same here

**Comment by binhex** [comment]
you arent exactly flooding me with details here guys!, click on the link below and follow the procedure:-

https://forums.unraid.net/topic/44108-support-binhex-general/?do=findComment&comment=435831

**Comment by Mizerka** [comment]
good chance either your ovpn files are missing, wrong or haven't populated cred variables in container profile. also gib logs if you want anything to be looked at

**Comment by userdocs** [comment]
I just wondered if this is using Chrome on Windows. For me a proxy using kitty works fine on chrome except to access deluge web ui.

Works fine in Firefox. Just Chrome with `127.0.0.1:8112` fails.

I have not figured out why yet.

**Comment by Mizerka** [comment]
works all platforms for me but gave up on headless setup with win client managing addons etc. couldn't get that to work.

but populating template creds and giving it a .ovpn nordvpn connection worked fine first time.

not op btw

**Comment by userdocs** [comment]
I have my win client working, i have the webui working in firefox. It's just chrome that is giving me hassle.

I just wondered if the OP was having this issue instead of a configuration issue.

**Comment by erfly7** [comment]
Finally solved on complete reinstall.
