### ISSUE TITLE
Increase connect-timeout

### ISSUE THREAD

**Issue by rsteckler** [binhex/arch-delugevpn#105]
PIA servers are slow to connect.
The following command is run at startup:
```
curl --continue-at - --connect-timeout 5 --max-time 600 --retry 10 --retry-delay 10 --retry-max-time 120 -o /tmp/pia_vpninfo_api_result -L -s -w %{http_code} https://www.privateinternetaccess.com/vpninfo/servers?version=82
```

--connect-timeout will often fail with PIA servers, regardless of how many times you retry.  Simply changing the connect-timeout to 10 or 15 seconds makes the command succeed instead of failing multiple times via retries.

**Comment by rsteckler** [comment]
https://github.com/binhex/scripts/blob/master/shell/arch/docker/curly.sh#L32

**Comment by gtbuchanan** [comment]
Same issue here on Synology DS412+ no matter what PIA server is configured. Updated `connect-timeout` to 10 in `/root/curly.sh` directly in the container and the issue was resolved. This is obviously just a workaround.

**Comment by binhex** [comment]
ok working on it guys...

**Comment by binhex** [comment]
ok new image just built with the connection timeout cranked up to 10 seconds, can somebody please give it a whirl and let me know how you get on.

**Comment by rsteckler** [comment]
Working for me.  Thanks for the fix.
@gtbuchanan You mind re-pulling the latest image and making sure it works on Synology?

**Comment by gtbuchanan** [comment]
Just confirmed it's working great now on Synology. Thanks for the fix.
