### ISSUE TITLE
The webAPI won't work

### ISSUE THREAD

**Issue by guim31** [binhex/arch-delugevpn#106]
Hi,

I'm facing a problem as I want to integrate Deluge (wich is working fine) in my OrganizR front end homepage.

OrganizR says I should install this plugin : 
WebAPI-0.3.2-py2.7.egg
form https://github.com/idlesign/deluge-webapi/tree/master/dist

But I can't get it to show in the plugins list... So I can't activate it.

I'm using the Deluge docker image (latest)

**Comment by feyded1020** [comment]
> Hi,
> 
> I'm facing a problem as I want to integrate Deluge (wich is working fine) in my OrganizR front end homepage.
> 
> OrganizR says I should install this plugin :
> WebAPI-0.3.2-py2.7.egg
> form https://github.com/idlesign/deluge-webapi/tree/master/dist
> 
> But I can't get it to show in the plugins list... So I can't activate it.
> 
> I'm using the Deluge docker image (latest)

Did you ever get this issue fixed? Im having the exact same issue still.

**Comment by Petahh** [comment]
https://github.com/idlesign/deluge-webapi/issues/21
https://github.com/idlesign/deluge-webapi/issues/14

**Comment by ivanfilippov** [comment]
Take a look at https://github.com/binhex/arch-delugevpn/issues/100#issuecomment-535353664 and assist with testing if you can. 😄

**Comment by idlesign** [comment]
webapi 0.4.0 is now available.

**Comment by nameproof** [comment]
> 
> 
> webapi 0.4.0 is now available.

WebAPI-0.4.0-py3.7.egg is a no go for me, I don't understand why. Does this work for you guys?

**Comment by binhex** [comment]
stale issue, closing
