### ISSUE TITLE
Webgui not accessible (docker windows)

### ISSUE THREAD

**Issue by stevealexandre** [binhex/arch-delugevpn#108]
Hi dude,

I've tried some issue resolution before create this but any doesn't work for my case.
I run docker with windows 10 with linux container option.

Below the full infos needed to debug :
- supervisord.log
https://pastebin.com/3dwUeZNS

- ipconfig /all
https://image.noelshack.com/fichiers/2019/18/1/1556571009-ipconfig.png

- Config docker through Kitematic (gui for windows)
https://image.noelshack.com/fichiers/2019/18/1/1556571205-kitematic.png

- When trying to access through localhost:8112
Website not available
localhost doesn't allow the connection
ERR_CONNECTION_REFUSED

Thank you for your help

**Comment by binhex** [comment]
firstly i wouldnt try localhost, try using your lan ip address, secondly check that this is correct:-

[info] LAN_NETWORK defined as '192.168.1.0/24'

is your lan network actually defined as that? (that is the default).

**Comment by stevealexandre** [comment]
Thanks for your reply.
Neverminds, you can insult me ahah It's just because I forgot to add the right port redirection and Kitematic have defined himself local port config to the docker container.
By modifying them like 8112 = 8112 it's working.
Sorry for this fake issue.
