### ISSUE TITLE
Latest update broke connection

### ISSUE THREAD

**Issue by Steven-Harris** [binhex/arch-delugevpn#109]
I had to revert to 1.3.15_18_ge050905b2-1-01 to get my services working again

**Comment by Mizerka** [comment]
`2019-05-02 10:12:28.074 154a9bf9a140 Fatal error: can't bind to 172.17.0.2 :8118: The hostname is not resolvable`

Is what I get in mine after update, but tunnel appears to come up and external IP presented is changed to providers, when I dig myip opendns

**Comment by NobQuaffer** [comment]
I've got the same issue too. Plenty of people reporting the same thing on the unraid forum as well.

**Comment by binhex** [comment]
resolved in latest image, please pull down.
