### ISSUE TITLE
Plugins not executing after upgrade from API/URL Release (1.3.15+18+ge050905b2-1-01)

### ISSUE THREAD

**Issue by doczong** [binhex/arch-delugevpn#113]
After manually upgrading to the release 4 weeks ago, plugins are imported but not executing.  Such as AutoRemovePlus etc.  Checked Python verison, is not 2.7 - and is 3.x... could be problem moving forward?

**Comment by doczong** [comment]
Correction, Python 3 is in both... I am stumped.  Let me know if you want some logs.

They are loading into memory, but they won't trigger.

**Comment by trijenhout** [comment]
over here the same problem whit the plugins not loading. went back to 1.3.15  need rss plugin

**Comment by binhex** [comment]
Deluge v1 plugins are not compatible with deluge V2
