### ISSUE TITLE
Can access Web UI but can't connect with deluge

### ISSUE THREAD

**Issue by EnderShadow** [binhex/arch-delugevpn#115]
If I try and access the container from the WebUI it connects fine, but if I try to connect from deluge which is running on the same computer with the connection manager it fails to detect it.

**Comment by poohbah** [comment]
I'm having the same issue. The webui works normally, but remotely connecting via a local deluge install doesn't see the (remote) docker install of delugevpn. No settings have changed and it worked well for a long time. My delugevpn image was updated 6/19/19.

**Comment by binhex** [comment]
deluge 2.x is not compatible with deluge 1.x thin clients, so unless you update all connecting deluge instances to 2.x then you will be out of luck - note there is currently no windows 2.x deluge thin client.

**Comment by madsboddum** [comment]
> deluge 2.x is not compatible with deluge 1.x thin clients, so unless you update all connecting deluge instances to 2.x then you will be out of luck - note there is currently no windows 2.x deluge thin client.

That was the issue in my case. Too bad that there are no supporting clients for Windows.

**Comment by EnderShadow** [comment]
I'm running linux as my host.
