### ISSUE TITLE
Sleeps every 10 min

### ISSUE THREAD

**Issue by wschlotter** [binhex/arch-delugevpn#12]
When I look at the log it says that it wakes up checks and then goes back to sleep on a 10 min cycle. Is there a way to turn that off?

**Comment by binhex** [comment]
ive moved this into the debug block now, so unless you have debug switched on then you wont see this message, this will be included in the next docker hub build.

**Comment by wschlotter** [comment]
i have DEBUG=false at the moment

**Comment by wschlotter** [comment]
I have debug switched to false DEBUG=false, and it is still sleeping every 10 mins

**Comment by binhex** [comment]
Yes as above, you need you wait for the next build of the image on docker hub, the change has been done.

**Comment by wschlotter** [comment]
ok
