### ISSUE TITLE
Download folder deleted

### ISSUE THREAD

**Issue by samsepiol59** [binhex/arch-delugevpn#123]
Hello, so I managed to set delugevpn up in Cloudbox - everything works great... 

But one thing - I set the download folder to the same folder as "normal" Deluge, and when the download completed in delugevpn the folder got deleted.. And the files with it.

I'm not sure what happened! Any idea?

**Comment by binhex** [comment]
```
But one thing - I set the download folder to the same folder as "normal" Deluge, 
```
no idea what 'normal deluge' is?, do you mean the default?, if so then this is incorrect, you need to configure this to write your downloads OUTSIDE of the container e.g. /data/completed (assuming a container volume map named 'data' is defined in the docker run command)
