### ISSUE TITLE
rutracker not downloading?

### ISSUE THREAD

**Issue by samsepiol59** [binhex/arch-delugevpn#125]
Hello, so I've set up delugevpn with PIA and it's working flawlessly - I'm downloading form italian public trackers without any issues.

But, I've tried adding a few torrents from RuTracker and I keep getting the `Error: Cannot assign requested address` - what's going on? 

Thank you!

**Comment by ivanfilippov** [comment]
Since this is only happening on one tracker, can you confirm that it isn't happening on a base deluge install outside of this container? (Install PIA client and deluge outside docker, connect to VPN and add the same torrents)

**Comment by samsepiol59** [comment]
Sorry, I don't have PIA anymore. I do have NordVPN now, and I wanted to try and setup delugevpn with Nord - it works right?! Is there any particular setup I need to follow?

**Comment by sachinmu** [comment]
@samsepiol59 hey were you able to get NordVPN working on this? I'm not able to figure out how to do the config
