### ISSUE TITLE
Stats plugin not showing graphs

### ISSUE THREAD

**Issue by paolobasso99** [binhex/arch-delugevpn#128]
Hi, I'd like to see the graphs provided by the Stats plugin which it seems to be already installed in this image. The problem is that even after enabling it in the webUI it does not appear to be working since there is not the graphs page at the bottom.
As a note I'm running this container in a ubuntu remote server with the vpn enabled and the webUI accessible through an nginx proxy.

**Comment by batu-one** [comment]
That plugin doesn't support the WebUI, see https://dev.deluge-torrent.org/wiki/Plugins
