### ISSUE TITLE
VPN Host cannot be resolved, possible DNS issues

### ISSUE THREAD

**Issue by tercan99** [binhex/arch-delugevpn#129]
Looking at other tickets, it looks like lookups were switched from `dig` to `drill`? I'm using a VPN service where there are 173 A records for the one host. `dig` just complains about switching to TCP due to response truncation, but `drill` fails completely unless you pass the `-t` flag to force TCP to avoid truncation. I think this is why the startup script fails DNS lookup for me. Is this the case?

```[root@deluge-84b74468c5-xdxh8 /]# drill us-la.secureconnect.me
;; ->>HEADER<<- opcode: QUERY, rcode: NOERROR, id: 15353
;; flags: qr tc rd ra ; QUERY: 1, ANSWER: 0, AUTHORITY: 0, ADDITIONAL: 0 
;; QUESTION SECTION:
;; us-la.secureconnect.me.      IN      A

;; ANSWER SECTION:

;; AUTHORITY SECTION:

;; ADDITIONAL SECTION:

;; Query time: 1837 msec
;; SERVER: 1.1.1.1
;; WHEN: Thu Sep 12 04:16:19 2019
;; MSG SIZE  rcvd: 40

;; WARNING: The answer packet was truncated; you might want to
;; query again with TCP (-t argument), or EDNS0 (-b for buffer size)
```

**Comment by binhex** [comment]
i can replicate the issue, however its more work than first thought, as i dont want to include the -t option by default, as you are currently the only user experiencing this issue, so i need to put in some checks to see if the issue occurs and if so then add in -t flag, ive got some code to do this but ive not checked it in yet.

**Comment by tercan99** [comment]
With the version of drill, you can just use the -a option, which will keep falling back from UDP, to an Enhanced Buffer, to TCP. Also need to tweak the grep of the result to only take the top 63 as OpenVPN is limited to 64 --remote* options. Will push a MR to /arch-int-openvpn.
