### ISSUE TITLE
Can't connect to daemon from thin client on another computer on LAN

### ISSUE THREAD

**Issue by jamesahad** [binhex/arch-delugevpn#130]
Hi, 

I am running the latest build of delugevpn on a Synology NAS with privoxy and VPN turned on. I am using Nord VPN. I've been trying to install and setup yarss2 plugin for deluge, but have not been able to connect to the daemon via thin client on a computer that is on LAN. 

I've tried various things on other posts about this issue. I have made sure that remote connects are accepted via the webui and am using all the standard ports. I've made sure the auth file contains a user/pass in the correct format. I've also tried connecting with vpn disabled. 

None of these methods seem to work. Is there anything else that I could possibly try?

**Comment by IDmedia** [comment]
I could be wrong, but I think the reason is that this Docker image is using Deluge version 2 while the client (for Windows) only supports version 1 yet. From https://dev.deluge-torrent.org/wiki/Download

"Deluge 2.0 packages are not yet available"

**Comment by jamesahad** [comment]
That was exactly the issue. I reverted to 1.3.15 and was able to connect with thinclient. Thank you for your help!

**Comment by Jasmin25** [comment]
@jamesahad I am new to setting up home media server and trying to find how I can setup nordpvpn with this project. Can you please share your docker container config? That'd be very helpful!
