### ISSUE TITLE
delugevpn does not create config folders

### ISSUE THREAD

**Issue by ENTXawp** [binhex/arch-delugevpn#131]
I have an issue where my container (on unraid) won't start. 
![image](https://user-images.githubusercontent.com/39438957/65493397-0ec7d400-deb3-11e9-876e-57dfb6fc23f2.png)
So I went to check the folder and there are no folders.
![image](https://user-images.githubusercontent.com/39438957/65493166-9b25c700-deb2-11e9-8fd7-7f49e106c42f.png)
Binhex's solution for this is to 

> Once you have downloaded the zip (normally a zip as they contain multiple ovpn files) then extract it to /config/openvpn/ folder (if that folder doesn't exist then start and stop the docker container to force the creation of the folder).

Unfortunately, I am unable to start the container as it stops itself.
![gif](https://user-images.githubusercontent.com/39438957/65495617-56e8f580-deb7-11e9-8554-8ba96ec9de1e.gif)

Sorry if I've misunderstood the instructions or the issue has been solved before.

**Comment by binhex** [comment]
follow this procedure and attach the log here (do not paste):-
https://github.com/binhex/documentation/blob/master/docker/faq/help.md
