### ISSUE TITLE
Unrecognized option or missing or extra parameter(s) in xxx.ovpn:18: block-outside-dns (2.4.7)

### ISSUE THREAD

**Issue by roupasz** [binhex/arch-delugevpn#133]
Hi all,

I've been using binhex/arch-delugevpn for quite some time now and i'm really satisfied, great work and very very stable. I'm also using freevpn.me accounts instead of PIA and also everything was working great until today. For some reason that i can't understand suddenly when starting the docker image the connection keeps restarting

```
[info] Starting OpenVPN...
2019-10-02 23:23:18,769 DEBG 'start-script' stdout output:
Wed Oct  2 23:23:18 2019 Unrecognized option or missing or extra parameter(s) in /config/openvpn/FreeVPN.it-TCP443             .ovpn:18: block-outside-dns (2.4.7)
2019-10-02 23:23:18,772 DEBG 'start-script' stdout output:
Wed Oct  2 23:23:18 2019 WARNING: file 'credentials.conf' is group or others accessible
Wed Oct  2 23:23:18 2019 OpenVPN 2.4.7 [git:makepkg/2b8aec62d5db2c17+] x86_64-pc-linux-gnu [SSL (OpenSSL)] [LZO] [             LZ4] [EPOLL] [PKCS11] [MH/PKTINFO] [AEAD] built on Feb 19 2019
Wed Oct  2 23:23:18 2019 library versions: OpenSSL 1.1.1d  10 Sep 2019, LZO 2.10
[info] OpenVPN started
Wed Oct  2 23:23:18 2019 NOTE: the current --script-security setting may allow this configuration to call user-def             ined scripts
Wed Oct  2 23:23:18 2019 Outgoing Control Channel Authentication: Using 256 bit message hash 'SHA256' for HMAC aut             hentication
Wed Oct  2 23:23:18 2019 Incoming Control Channel Authentication: Using 256 bit message hash 'SHA256' for HMAC aut             hentication
Wed Oct  2 23:23:18 2019 TCP/UDP: Preserving recently used remote address: [AF_INET]195.154.58.188:443
Wed Oct  2 23:23:18 2019 Attempting to establish TCP connection with [AF_INET]195.154.58.188:443 [nonblock]
2019-10-02 23:23:19,772 DEBG 'start-script' stdout output:
Wed Oct  2 23:23:19 2019 TCP connection established with [AF_INET]195.154.58.188:443
Wed Oct  2 23:23:19 2019 TCP_CLIENT link local: (not bound)
Wed Oct  2 23:23:19 2019 TCP_CLIENT link remote: [AF_INET]195.154.58.188:443
2019-10-02 23:23:20,147 DEBG 'start-script' stdout output:
Wed Oct  2 23:23:20 2019 VERIFY OK: depth=1, CN=www.FreeVPN.it
Wed Oct  2 23:23:20 2019 VERIFY KU OK
Wed Oct  2 23:23:20 2019 Validating certificate extended key usage
Wed Oct  2 23:23:20 2019 ++ Certificate has EKU (str) TLS Web Server Authentication, expects TLS Web Server Authentication
Wed Oct  2 23:23:20 2019 VERIFY EKU OK
Wed Oct  2 23:23:20 2019 VERIFY OK: depth=0, CN=www.FreeVPN.it
2019-10-02 23:23:20,310 DEBG 'start-script' stdout output:
Wed Oct  2 23:23:20 2019 Connection reset, restarting [0]
Wed Oct  2 23:23:20 2019 SIGHUP[soft,connection-reset] received, process restarting
```
I would say that this is strange:

`Unrecognized option or missing or extra parameter(s) in /config/openvpn/FreeVPN.it-TCP443.ovpn:18: block-outside-dns (2.4.7)`

In https://freevpn.it/accounts/ states that latest certificate bundle and openvpn client should be used. I've pulled the latest docker image which has 2.4.7 openvpn client installed (2.4.7-1 is the latest though in repo) and downloaded the latest certs from thei site ( they are from Arpil even though September should be the latest ones) and keep getting this message which i think is the root cause of connection reset.

Does anyone else has encountered the same problem with block-outside-dns  parameter? Should this be the problem or should i look somewhere else?

Best regards and thanks in advance

**Comment by binhex** [comment]
Unrecognized option or missing or extra parameter(s) in /config/openvpn/FreeVPN.it-TCP443.ovpn:18: block-outside-dns (2.4.7)

i would certainly say this is not helping, for now remove that line from your ovpn file and the message should stop, if you are feeling up to it i would feed this back to your vpn provider, as it looks like an invalid option.

**Comment by zroupas** [comment]
Thanks for the reply.

I did that already and re tried but it keeps restarting. Yes the second point is the provider but i just wanted you to take a look and maybe give an opinion if this parameter is added in the latest openvpn 2.4.7-1 and this is why when trying to connect with 2.4.7 which is currently in docker image would create a problem (tbh i wouldn't expect for a minor version to add block-outside-dns parameter)

Thanks again for the time

**Comment by zroupas** [comment]
Hi again,

Thanks for the support, i have contacted also the VPN provider and they fixed their certificates.
Now after removing  block-outside-dns from ovpn file (which previously had no change to the behaviour) i can login without any problems.

This issue can be closed
