### ISSUE TITLE
LAN_NETWORK for any ip?

### ISSUE THREAD

**Issue by loganto** [binhex/arch-delugevpn#135]
Ive tried launching a container with these:
-e LAN_NETWORK=1.1.1.1/32
and 
-e LAN_NETWORK=0.0.0.0/0

attempting to allow access from anywhere - but something doesn't work - still cant access webui.
What am I doing wrong?

**Comment by binhex** [comment]
i would advise you not to try doing this, the whole idea is that you prevent ip leakage by preventing the torrent client from communicating other than down the vpn tunnel, this is in effect removing this restriction.

**Comment by loganto** [comment]
@binhex   
im only trying to setup access to gui.   
It works fine when Im on my home network - however when I connect remotely via openvpn client my network ip might be in different range then the one allowed...  
so what is for me to do?    
I men n- I'm only trying to allow access to gui, not open ports for other traffic.

**Comment by binhex** [comment]
you add in the additional VPN range to LAN_NETWORK with a comma to separate in that case, that will work just fine.
