### ISSUE TITLE
no config files created

### ISSUE THREAD

**Issue by Dravenrip** [binhex/arch-delugevpn#136]
Hi guys, 
i try ton install delugeVPN on my Pi 4 with raspbian buster. 
Everything seems to be ok, except that no config files or folder are created when i launch my docker. I only have a "config" folder but nothing in it.

I tried te activate the DEBUG mode but nothing better... 

When i make "docker ps -a" i can see that delugevpn is restarting ... again and again. 
<img width="1002" alt="Capture d’écran 2019-10-26 à 12 25 39" src="https://user-images.githubusercontent.com/2520639/67618163-fc132880-f7eb-11e9-977a-0db115681b2d.png">

could you help me please to understand what happened ? 
I'm sorry i'm totally noob with docker and this kind of things... 

Thanks for you help

**Comment by fryfrog** [comment]
Did you pass a volume in for `/config` to use? What is your `docker run` command?

**Comment by Dravenrip** [comment]
Sorry i don't understand what you mean with "Did you pass a volume in for /config to use?" 

i'm launching all my containers with a docker compose.
Here is the docker-compose.yml 
[docker-compose.yml.zip](https://github.com/binhex/arch-delugevpn/files/3775653/docker-compose.yml.zip)

If it could help i'm following this article : [https://howto.wared.fr/debian-seedbox-docker-openvpn-nginx/](url)

Thanks again

**Comment by binhex** [comment]
stale issue, closing
