### ISSUE TITLE
Not able to connect to daemon from Deluge thin-client

### ISSUE THREAD

**Issue by JoeMShanahan** [binhex/arch-delugevpn#139]
I have the latest docker image running Deluge 2.0.3.

My client is a VM on the Unraid server running Ubuntu 18.04.3, it also has Deluge 2.0.3

The Deluge daemon does not report as being online.

```
Unraid host 192.168.0.35
 |   |
 |    +- Docker image
 |         |
 |         +- Daemon running on 58846, with working Webui on 192.168.0.35:8112
 |
 +- VM 192.168.0.30
      |
      +- Can't connect to daemon on 192.168.0.35:58846 with a user/pass from auth file
```

How do I debug this?

**Comment by fryfrog** [comment]
Show your `docker run` or `docker-compose.yml`, are you passing through the port?

**Comment by binhex** [comment]
probably due to the NAT on the vm, make sure you define the LAN_NETWORK to also include the vm's network as well as your lan.

**Comment by groot-stuff** [comment]
Confirming that updating the LAN_NETWORK container parameter fixed my connection issue when attempting to connect from another subnet (my firewall/router has multiple subnet, vlan and zone support).

My config for reference:
- unRaid server on 10.3.0.0/28
- Wireless devices on 10.4.0.0/24

Previously I only had LAN_NETWORK set to the `10.3.0.0/28` and the webui worked fine...
but I couldn't connect from my wireless devices on 10.4.0.0/24 through the _Trireme for Deluge_ android app (found on the F-Droid app store if you are interested).

Setting my LAN_NETWORK parameter to `10.3.0.0/28,10.4.0.0/24` and restarting the container now allows me to connect from my wireless devices on 10.4.0.0/24.

Thanks @binhex !
