### ISSUE TITLE
Deluge port accessible via VPN?

### ISSUE THREAD

**Issue by luciusbono** [binhex/arch-delugevpn#14]
The tracker I am using with Deluge claims that it cannot reach the port that I've specified (and I've confirmed this with one of those janky web-based port scanners). 

I'm not very savvy with `iptables`, but I dug through your config file and it looks to me like all traffic FROM the VPN connection should be routed to the torrent client free and clear. My VPN provider does not block any ports and is very torrent friendly. I also see that port forwarding is enabled via `systemctl`, which exhausts most of the troubleshooting I've come across. 

Is this expected, or is something amiss?

Thank you for all your hard work!

**Comment by binhex** [comment]
as long as your vpn provider supports port forwarding (most dont) and you have defined deluge to use the port specified via your vpn provider, then it should just work. as you have correctly identified i dont block any traffic to/from the tunnel once its established.
