### ISSUE TITLE
Add Support for Mullvad over Wireguard

### ISSUE THREAD

**Issue by anthr76** [binhex/arch-delugevpn#142]
With the recent buyout with PIA and limitations with OpenVPN. I was wondering if it would be possible to add functionality for Mullvad specifically over WireGuard.

This is a terrific project ! I've been using it for over a year.

**Comment by binhex** [comment]
wireguard support is a massive undertaking and not something on my todo list, it MAY get done in the distant future if enough vpn providers support it (which is not the case right now).
