### ISSUE TITLE
Not able to make TUN

### ISSUE THREAD

**Issue by justinglock40** [binhex/arch-delugevpn#144]
2019-12-01 11:52:20,140 DEBG 'start-script' stdout output:

Sun Dec  1 11:52:20 2019 ERROR: Cannot ioctl TUNSETIFF tun: Operation not permitted (errno=1)

Sun Dec  1 11:52:20 2019 Exiting due to fatal error

Any Known causes or fixes?

**Comment by fryfrog** [comment]
A good start would be providing enough information to help you. What is your `docker run`? My *guess* is you left off some `--option` for permissions that would allow it to create the `tun` device.

**Comment by justinglock40** [comment]
Was missing NET-ADMIN
