### ISSUE TITLE
Version Mismatch

### ISSUE THREAD

**Issue by darsh12** [binhex/arch-delugevpn#146]
Hi,
I was testing out deluge with this particular tag `binhex/arch-delugevpn:2.0.3_23_g5f1eada3e-1-01` in order to get the stable version. But after starting the container the version shows up as 2.0.4-dev20.

![Screen Shot 2019-12-04 at 10 48 52 PM](https://user-images.githubusercontent.com/16546412/70210757-5acf9a00-16e8-11ea-823f-427e58864144.png)

**Comment by binhex** [comment]
i take the version from the upstream arch package maintainer:-https://www.archlinux.org/packages/extra/any/deluge/

**Comment by darsh12** [comment]
Thanks, ill revert back to 2.0.3-2.01
