### ISSUE TITLE
AutoRemovePlus plugin won't work with this container as it is missing python future package

### ISSUE THREAD

**Issue by staticn0de** [binhex/arch-delugevpn#147]
Hey mate,

This may be outside of what you want to do with the container but the AutoRemovePlus plugin won't work with this container as it is missing the python future package. As expected if I manually install it it is removed when the container is recreated. 

link to the issue [https://github.com/springjools/deluge-autoremoveplus/issues/3](url)

Would you be able to include it in the container?
`pip3 install future`

**Comment by torresdrew** [comment]
Same issue here.

**Comment by binhex** [comment]
I will take a look tonight guys, should be simple

**Comment by binhex** [comment]
python future module now included in the latest image, please pull down.
