### ISSUE TITLE
Unable to reach web-UI behind a Traefik reverse-proxy in Kubernetes

### ISSUE THREAD

**Issue by JoooostB** [binhex/arch-delugevpn#159]
Caused by the strict IPtables, which in second thought is out of scope for a GitHub issue.

**Comment by seanrclayton** [comment]
I know I'm late to the discussion here, but in case someone searches the repo for kubernetes: 

container / pod communication works, so does external load balancing the trick is to set the `LAN_NETWORK` env variable in your spec to the **subnet for your cni provider** for flannel eg:

```
- name: LAN_NETWORK
     value: '10.96.0.0/16
```
I could then expose the pod as a type load balancer to hit it from my network. I hope this helps.
