### ISSUE TITLE
Add note about correct port setting when using STRONG_CERTS on PIA

### ISSUE THREAD

**Issue by jimeh** [binhex/arch-delugevpn#16]
PIA uses a different port for the strong certs, specifically 1197, instead of 1198. Source: https://helpdesk.privateinternetaccess.com/hc/en-us/articles/218984968-What-is-the-difference-between-the-OpenVPN-config-files-on-your-website-

And in fact I couldn't connect to PIA with strong certs until I set my port to 1197. I think it would be helpful with a small note in the readme about changing the port when using STRONG_CERTS :)

**Comment by binhex** [comment]
this is now resolved, as i automatically change the port for the user if defined wrong (pia only)

**Comment by jimeh** [comment]
Sweet :)
