### ISSUE TITLE
PIA wiregaurd support

### ISSUE THREAD

**Issue by cheesemarathon** [binhex/arch-delugevpn#166]
According to [this](https://www.privateinternetaccess.com/blog/wireguide-all-about-the-wireguard-vpn-protocol/)  article, it looks like PIA are working on wiregaurd support. In closed beta at the moment but hopefully it won't be long before it's public. 

With how much faster wiregaurd can be than OpenVPN, is it possible to work on a wireguard mode for this container when using PIA?

**Comment by cheesemarathon** [comment]
Not in beta anymore
https://www.privateinternetaccess.com/blog/wireguard-on-pia-is-out-of-beta-and-available-to-use-on-windows-mac-linux-android-and-ios/

**Comment by mjameson** [comment]
Should be a massive power saving and speed boost for ARM devices!

**Comment by mjameson** [comment]
BTW, please check this out. It is a bash script for acquiring the keys/ip information for wireguard config.

https://gist.github.com/tpretz/5ea1226517d95361f063f621e45de0a6

**Comment by binhex** [comment]
Until PIA officially support native WireGuard connections (not via PIA app) AND port forwarding is operational over WireGuard, then i won't be putting any effort into this, i believe at this time both of these are not in place.

**Comment by cheesemarathon** [comment]
No problem! Thanks for the update @binhex

**Comment by mjameson** [comment]
Thanks for the clarification @binhex and thanks so much for this project!

**Comment by theg00s3** [comment]
According to [this reddit comment by PIA](https://www.reddit.com/r/PrivateInternetAccess/comments/itafwx/pias_nextgen_vpn_network_is_a_huge_deal_update_to/g64673l), it looks like wireguard can be used without their app

**Comment by binhex** [comment]
> According to [this reddit comment by PIA](https://www.reddit.com/r/PrivateInternetAccess/comments/itafwx/pias_nextgen_vpn_network_is_a_huge_deal_update_to/g64673l), it looks like wireguard can be used without their app using a bash script they provide

it can but its very fragile, as it uses the wireguard config generated by the app, if this expires or needs re-creating then the script will break.

**Comment by doczong** [comment]
So this is technically offtopic... but I use PIA and my renewal is coming up on October 25th, which is five days before they sunset legacy.  And I don't trust them.

I know this is a lazy question:  But who sells VPN, specifically with port forwarding, and preferably without logging.

I don't need it for anything except Deluge.  And maybe my WiFi Hotspot.

**Comment by cheesemarathon** [comment]
> So this is technically offtopic... but I use PIA and my renewal is coming up on October 25th, which is five days before they sunset legacy.  And I don't trust them.
> 
> I know this is a lazy question:  But who sells VPN, specifically with port forwarding, and preferably without logging.
> 
> I don't need it for anything except DelugeVPN.  And maybe my WiFi Hotspot.  So this would limit any suggestions to something that works with this awesome project.

I have just switched to Mullvad. Very privacy focused. It was easy to setup. I'm using it with rtorrent but the same principal applies. I have been struggling to get port forwarding to work, but I havnt seen any drops in download speed so I have just left it for now.

**Comment by binhex** [comment]
wireguard support is now in, please see the readme.md for details.

**Comment by theg00s3** [comment]
is it possible to choose the wireguard endpoint?

**Comment by binhex** [comment]
@theg00s3 Q21:- https://github.com/binhex/documentation/blob/master/docker/faq/vpn.md
