### ISSUE TITLE
Can I use this with NordVPN?

### ISSUE THREAD

**Issue by BobWs** [binhex/arch-delugevpn#168]
Hi,
Can I use this image with NordVPN? Is there a description how to setup the image with NordVPN?
Thanks

**Comment by binhex** [comment]
yes, but i wouldnt, nordvpn do not support port forwarding so your speeds will be slow at best.

**Comment by BobWs** [comment]
> yes, but i wouldnt, nordvpn do not support port forwarding so your speeds will be slow at best.

Okay thanks for replying
