### ISSUE TITLE
Privoxy: Invalid header received from client.

### ISSUE THREAD

**Issue by Nathan13888** [binhex/arch-delugevpn#174]
When connected to the Privoxy page, default port 8118, it reports "Invalid header received from client."

Tried different browsers, doesn't seem to help.

Help or any reports to this issue seems to be limited.

How anyone who has encountered this issue or has some possible solutions could shed light!

Thanks

![image](https://user-images.githubusercontent.com/29968201/79712732-ad75b100-8299-11ea-8805-0b688cd82e51.png)

Btw, I've mapped the 8118 port to 192.168.10.250:18118.

![image](https://user-images.githubusercontent.com/29968201/79712754-bbc3cd00-8299-11ea-9dd9-a54d0dad7e49.png)

Also, there are no errors or anything irregular in the Docker logs.

**Comment by binhex** [comment]
this is completely normal, you should not be trying to access privoxy via the web ui (or curl/wget), instead you configure your browser to use the proxy.

**Comment by Nathan13888** [comment]
Hi @binhex. Sorry for being kind of a noob, never actually used privoxy before...

I'm a bit confused with how the configuration part works.

(Question 1) When I connect to the Proxy and use Firefox or Chrome, I get something like:

![image](https://user-images.githubusercontent.com/29968201/79782127-902dfa80-830c-11ea-88de-e4a13c0adfec.png)

*Am I missing any configuration or steps before stuff starts to work??*

(Question 2) Does the Privoxy part of the Docker run as a separate service which is exposed to LAN/Dockernet. Meaning that the Deluge part of the Docker is configured to run with Privoxy if the ENV Variable is set to "yes". So essentially could both Deluge and another computer on LAN use Privoxy as another proxy?

(Question 3) Is there any documentation or instructions I could refer to for configuring and using Privoxy?

**Comment by binhex** [comment]
> Question 1) When I connect to the Proxy and use Firefox or Chrome, I get something like:

can you send me a screenshot of how you have configured firefox and/or chrome to use privoxy?, also detail what the ip address is of your host machine running the container.

> (Question 2) Does the Privoxy part of the Docker run as a separate service which is exposed to LAN/Dockernet. Meaning that the Deluge part of the Docker is configured to run with Privoxy if the ENV Variable is set to "yes". So essentially could both Deluge and another computer on LAN use Privoxy as another proxy?

privoxy and deluge are two independant processes running in the same container that share the same network, so you can have deluge running, or deluge and privoxy running at the same time. you do NOT configure deluge to privoxy, this is not required and will cause issues.

> (Question 3) Is there any documentation or instructions I could refer to for configuring and using Privoxy?

i would only be googling it just like you, do a search for 'privoxy documentation' and start from there.

**Comment by Nathan13888** [comment]
# Q1
It's off right now but it was on before when it didn't work. All my browsers use the default settings for Proxies (ie., use whatever is in the system settings)

The Docker runs on this home server with the IP (192.168.10.250, 192.168.10.200 and a few others). But the Privoxy port on the Docker is set to 192.168.10.250:18118.

![image](https://user-images.githubusercontent.com/29968201/79892198-2d059c00-83d0-11ea-8b06-5305f47059a3.png)

![image](https://user-images.githubusercontent.com/29968201/79892517-b321e280-83d0-11ea-8a31-57bffe1cf3d4.png)

![image](https://user-images.githubusercontent.com/29968201/79892642-d8aeec00-83d0-11ea-8aec-921b4666dfee.png)

# Q2
1. Since I don't need to configure deluge to privoxy, *would Deluge be using Privoxy*?

2. And what IP would Deluge appear to be if it is using Privoxy? I don't really get how Privoxy works, especially how it works as a Proxy and how does it help with anonymity of Deluge.

3. Also, is the point of exposing Privoxy just to test to see if it works??? What is the point exactly?


Sorry for all these questions, hope you could help me out here. Thanks for all your advice so far.

**Comment by binhex** [comment]
hmm ok so Q1 looks ok, can you attach or paste your privoxy config file, it will be located in /config/privoxy/config.

Q2.
1. no, deluge does not use and should not use any form of proxy, thats what the vpn tunnel is for - securing deluge.

2. see 1.

3. see Q3 from the following link:-
https://github.com/binhex/documentation/blob/master/docker/faq/vpn.md

**Comment by Nathan13888** [comment]
Config file (inside the zip):
[config.zip](https://github.com/binhex/arch-delugevpn/files/4511987/config.zip)

So as for Privoxy, what do I need to configure in Privoxy or does it works good enough out of the box? Is Deluge setup with Privoxy by default is what I'm trying to say.

**Comment by binhex** [comment]
> So as for Privoxy, what do I need to configure in Privoxy or does it works good enough out of the box?

you shouldnt need to configure it for it to work out of the box.

> is Deluge setup with Privoxy by default is what I'm trying to say.

no, deluge (as in the app not the container) is not setup to use privoxy, and as previously mentioned, should not be set to do so. if what you are asking is does privoxy work if ENABLE_PRIVOXY is set to yes, then the answer to THAT question is yes.

i can see no problems with your privoxy config file, so i can only assume something is blocking it on your lan, got vlan's defined?, are they blocking?, pfsense or some such advanced firewall, is it blocking?, host firewall, is that blocking?.

**Comment by Nathan13888** [comment]
Yes, everything is near default.

There are no VLANs running as of now, not even the security cameras

The entire server running Docker is connected using this wifi router. No PFsense and the wifi router doesn't really have a firewall. I have pretty default firewall settings on my laptop (windows) so I don't think that's the problem.

Also, I'm wondering what these ports are for? Could these be related to Privoxy??
![image](https://user-images.githubusercontent.com/29968201/79999667-2f2c3100-848a-11ea-8205-ed8817ea86d6.png)

**Comment by binhex** [comment]
> I have pretty default firewall settings on my laptop (windows) so I don't think that's the problem.

so am i right in thinking you are running docker on windows?, if so the windows firewall could well be the problem as it tends to block inbound requests, try temporarily disabling the windows firewall and see if you can access privoxy, if so then you need to tweak the firewall.

port 58846 and 58946 are there to be used if you turn off the vpn, as you can use them for incoming ports, so nothing to do with privoxy.

**Comment by Nathan13888** [comment]
Hi @binhex.  I'm actually not running Docker on Windows. The Deluge docker is running on this dedicated home server that runs Debian Buster. The server also uses default firewall settings too.
