### ISSUE TITLE
How would I set delugevpn to use a socks5 proxy

### ISSUE THREAD

**Issue by Titaniumtown** [binhex/arch-delugevpn#177]
How would I set delugevpn to use a socks5 proxy at a specific ip and port? I want to set it to my tor proxy at 127.0.0.1:9050 bc I don't have money to pay for a vpn service, lol. (btw I am new to docker)

**Comment by Titaniumtown** [comment]
I really want to use delugevpn instead of what i'm using atm.

**Comment by binhex** [comment]
deluge is sadly a bit crap when it comes to socks5 and http proxy support, it leaks ip info so i wouldnt do this if i were you, get yourself a vpn, its like $4 a month.
