### ISSUE TITLE
Docker for Windows - Web UI from different machine

### ISSUE THREAD

**Issue by chavezjose** [binhex/arch-delugevpn#178]
First off, thank you Binhex. Been using this for almost half a year now and loving it.

One thing I haven't been able to figured out is how to view the Web UI from any none host machine.

>Local IP - 10.0.0.12
Router - 10.0.0.1
Subnet - 255.255.255.0

No issues with the Web UI at 10.0.0.12:8112, localhost:8112, or even 127.0.0.1 from inside the host machine. Out side of the machine, I get ERR_CONNECTION_TIMED_OUT (Chrome, W10).

Don't wanna add too much detail if it's no necessary. Is this something that could be config or a limitation of Docker for Windows? This is the first DfW project I've taken on.

Thanks,
Jose

**Comment by doscott** [comment]
On the same network use the computer address the image is running on. Eg.
http://192.168.1.200:8112

From outside the network, if you have a public ip address, you should be able to port forward 8112 to your computer and reach it that way (I haven't for this image but I for Virtualbox images).

**Comment by chavezjose** [comment]
>computer address the image is running

Do you mean the IP address of the Windows Machine running Docker for Windows? That's what I'm doing, and that specific address (10.0.0.12:8112) only works on the same machine. If I go to Desktop 2, it gives me the above error. I setup a bridge network in my docker settings. If you mean another IP, which is it and how would I get it?

**Comment by doscott** [comment]
That’s what I mean. I do this with Firefox on an iPad and I have checked a Windows 10 / VirtualBox setup. My docker is on a Linux box, perhaps that is the difference. I also have port 8112 opened on the Linux box firewall.

**Comment by chavezjose** [comment]
I think you made me finally try the one thing I haven't. I don't recall having to open up ports for Plex, Sonarr, and Radarr, but that's exactly what I had to do here. Feel like an idiot for not figuring this out sooner. Thanks for the help.

Cheers,
Jose
