### ISSUE TITLE
error: unable to get local issuer certificate

### ISSUE THREAD

**Issue by houdini3009** [binhex/arch-delugevpn#18]
I'm trying to get this container working with PIA. I've tried every combination of user/password/remote I can think of but I keep getting the same error explaining that the local issuer certificate can't be found. Is there a step missing in the setup details? Where do we get this certificate and where should it be stored?

`DEBG 'start-script' stdout output:
UDPv4 link local: [undef]
UDPv4 link remote: [AF_INET]104.200.153.85:1198

DEBG 'start-script' stdout output:
VERIFY ERROR: depth=0, error=unable to get local issuer certificate: C=US, ST=CA, L=LosAngeles, O=Private Internet Access, OU=Private Internet Access, CN=1da62a494fe4951e6cea37cf8a930bcc, name=1da62a494fe4951e6cea37cf8a930bcc
TLS_ERROR: BIO read tls_read_plaintext error: error:14090086:SSL routines:ssl3_get_server_certificate:certificate verify failed
TLS Error: TLS object -&gt; incoming plaintext read error
TLS Error: TLS handshake failed
SIGUSR1[soft,tls-error] received, process restarting`

**Comment by binhex** [comment]
i will need the full supervisord.log file to correctly identify the issue (located in /config) please remove credentials from it and then post it here.

**Comment by houdini3009** [comment]
Here you go. Appreciate you having a look at it. Not sure what's going on.

http://pastebin.com/jTuXgAMD

**Comment by houdini3009** [comment]
I fixed it by changed the VPN_PORT from 1198 to 1194. Weird.
