### ISSUE TITLE
Set incoming port range

### ISSUE THREAD

**Issue by lsaadeh** [binhex/arch-delugevpn#189]
More of a question if is possible to define the incoming port/port range within the deluge networking settings.

It seems after defining a specific port it randomly changes to another port, preferably I would like to define a range between 50k and 65k as anything below 50k has a higher chance of being throttled by an ISP.

Could this be a vpn thing?

**Comment by binhex** [comment]
your ISP wont throttle you, once you have a vpn tunnel established your ISP will have zero visibility of anything that gets transferred over the tunnel, this includes ports used.

not only that, but vpn providers will only allocate you a single port at a time, so you wont be able to have a large range of incoming ports.

**Comment by lsaadeh** [comment]
Thanks for that information, just curious any reason why changing the incoming port to a figure between 50-65k would drastically improve performance temporarily?
And would it be possible to lock to a certain port? or to vpn assign you ports randomly?

**Comment by binhex** [comment]
> just curious any reason why changing the incoming port to a figure between 50-65k would drastically improve performance temporarily?

no reason that i can think of, ive not seen this behaviour myself tbh.

> And would it be possible to lock to a certain port? or to vpn assign you ports randomly?

that depends on the vpn provider, some dynamically provision incoming ports, others allow you to define your own static port.
