### ISSUE TITLE
Deluge Stopped Working. No access to Web UI. Not talking to Sonarr

### ISSUE THREAD

**Issue by samdj0** [binhex/arch-delugevpn#194]
Been using the same container for 8 months and suddenly stopped. I saw that it might be PIA, so I updated the openvpn config files, but still not luck. 

attaching my log and docker cmd

i do not have the background to decipher log file, so any help would be appreciated. 

[deluge log.txt](https://github.com/binhex/arch-delugevpn/files/5205862/deluge.log.txt)
[deluge docker clean.txt](https://github.com/binhex/arch-delugevpn/files/5205863/deluge.docker.clean.txt)

**Comment by Greg2dot0** [comment]
I am getting similar issues since sometime yesterday. It seems as though it's related to port forwarding, but that's just a guess. based on the log entry right before the error. I have tried most of the dynamic port endpoints with the same error.

I am on a Qnap system but also tried on a straight Unbutu install and got the same results. Even tried a clean install with only the PIA stuff installed.



`[info] Attempting to get dynamically assigned port...`

Here's the error:

`
2020-09-11 05:13:07,613 DEBG 'start-script' stdout output:
[warn] Exit code '56' from curl != 0 or no response body received
[info] 11 retries left
[info] Retrying in 10 secs...
`
[
[delugevpn.txt](https://github.com/binhex/arch-delugevpn/files/5207982/delugevpn.txt)
](url)

**Comment by Greg2dot0** [comment]
Definitely an issue with PIA's port forwarding API.
I tried to manually test with their KB article

https://www.privateinternetaccess.com/helpdesk/kb/articles/can-i-use-port-forwarding-without-using-the-pia-client-current-gen-only

One thing of note was a bold line in the article.

** The information contained within this article will only work with our Current/Previous Generation servers. Our Next Generation servers do not currently offer port-forwarding outside of the application. **

**Comment by binhex** [comment]
hi guys, the situation for PIA is as follows (at present):-

- Port forwarding on their legacy network is near enough dead, their API is completely random right now as to whether you get a port assigned or not, its normally a case of not.

- Port forwarding using OpenVPN on their next-gen network is currently not possible, api is not accessible.

- Native Wireguard support on their next-gen network is currently not possible (hacks are available but they are fragile!).

So where does that leave us?, well not quite up sh*t creek without a paddle :-), you can set 'STRICT_PORT_FORWARDING' to 'no' and this will then allow you to connect to any legacy endpoint, however this will mean you wont have a working incoming port so speeds will be lower than usual - its not ideal i know, but its the best we have got right now until PIA sort their sh*t out (not happy).

If you want to help out then PLEASE raise a support ticket and bitch about the above, the more people that complain the more pressure they have to do something about it!.

See link below for an ongoing discussion of the issues with PIA and their port forwarding API on reddit:-
https://www.reddit.com/r/PrivateInternetAccess/comments/iq8mm4/anyone_else_having_trouble_with_portforwarding/

**Comment by Tuumke** [comment]
Using the STRICT_PORT_FORWARDING set to no works for me.
Don't notice any speed difference.. but then again, i only have 100mbit connection so..

**Comment by samdj0** [comment]
I’ll raise a ticket with PIA. Thank you @binhex for the thorough explanation.

**Comment by mjameson** [comment]
Hi guys, here's a link to a script that acquires port binding on next gen servers for PIA. Figured it would be a good reference.

https://github.com/fm407/PIA-NextGen-PortForwarding/blob/master/pia-nextgen-pf.sh

**Comment by theg00s3** [comment]
[https://www.reddit.com/r/PrivateInternetAccess/comments/itafwx/pias_nextgen_vpn_network_is_a_huge_deal_update_to/g64673l](This comment) seems to imply that port forwarding is now available on the next-gen servers

**Comment by theg00s3** [comment]
[This comment](https://www.reddit.com/r/PrivateInternetAccess/comments/itafwx/pias_nextgen_vpn_network_is_a_huge_deal_update_to/g64673l?utm_source=share&utm_medium=web2x&context=3) seems to state that port forwarding is now available on the next-gen network

**Comment by HNGamingUK** [comment]
@binhex I assume that as per the above comment you will be able to incorporate their scripts to allow port-forwarding on their next-gen network?

**Comment by andy-vdg** [comment]
@binhex 
Can we re-open based on [https://github.com/binhex/arch-qbittorrentvpn/issues/50](https://github.com/binhex/arch-qbittorrentvpn/issues/50)?
