### ISSUE TITLE
PIA requires script for port forwarding now

### ISSUE THREAD

**Issue by trevormiller6** [binhex/arch-delugevpn#197]
see PIA support site: https://www.privateinternetaccess.com/helpdesk/kb/articles/can-i-use-port-forwarding-without-using-the-pia-client-current-gen-only

This would need to be added to the start script to enable port forwarding. Not sure if that is possible haven't looked at the code. will update once i investigate more.

**Comment by binhex** [comment]
thats not a new method, thats the same method i have been using for years, thanks for trying to help though :-).

**Comment by binhex** [comment]
Support for multi remote endpoints and PIA 'Next-Gen' networks now complete, see Q19 and Q20 for details:-
https://github.com/binhex/documentation/blob/master/docker/faq/vpn.md
