### ISSUE TITLE
Dynamic port config issue after upgrade

### ISSUE THREAD

**Issue by eringuet** [binhex/arch-delugevpn#198]
Hi, I've upgraded my deluge container and since then, it won't come up.

I see that it seems to hang at "Attempting to get dynamically assigned port":

[info] Attempting to get dynamically assigned port...

2020-09-15 14:45:40,868 DEBG 'start-script' stdout output:
[warn] Exit code '56' from curl != 0 or no response body received
[info] 12 retries left
[info] Retrying in 10 secs...
[supervisord.log](https://github.com/binhex/arch-delugevpn/files/5225964/supervisord.log)

**Comment by binhex** [comment]
https://github.com/binhex/arch-delugevpn/issues/194#issuecomment-691044876

**Comment by binhex** [comment]
Support for multi remote endpoints and PIA 'Next-Gen' networks now complete, see Q19 and Q20 for details:-
https://github.com/binhex/documentation/blob/master/docker/faq/vpn.md
