### ISSUE TITLE
Is there an easy way to set Deluge's UMASK?

### ISSUE THREAD

**Issue by dprus** [binhex/arch-delugevpn#2]
It seems that right now Deluge will create files only writable by nobody. Would it be possible to allow us to configure Deluge's UMASK? Deluge also seems to create all the download folders with nobody as both the owner and group - it would be great if we could configure the group it creates the folders as.

This way I could allow Sonarr to pull files from Deluge's complete folder (Sonarr runs as a separate user 'nzbdrone' that is also part of the 'users' group).

**Comment by alias1** [comment]
+1 this, it's sort of a pain.

My hacky workaround was to have it execute chmod 777 on file download completion. chown to someone else would probably also be a useful way to achieve this.

**Comment by binhex** [comment]
umask is now 000 (set around oct-nov 2015)

**Comment by dmp1ce** [comment]
I would still like a way to set umask. I prefer 022 on my system.

Should I just override the image locally to change the umask?

**Comment by binhex** [comment]
ok i can add this in as a env var so you can define it when you create the container, something like

`-e MASK=XXX`

**Comment by dmp1ce** [comment]
That would work for me!

**Comment by fryfrog** [comment]
Did this ever make it in?

**Comment by binhex** [comment]
not yet, i had other bigger fish to fry im afraid, but im ready to take a look at this, hope to have it complete by mid next week.

**Comment by binhex** [comment]
This is now complete, if you want to change the umask from the default (000) then simply create an additonal env var via the docker -e flag with a key name of UMASK and a value of the umask you want (3 number format), see readme for examples.
