### ISSUE TITLE
Synology Docker: Can't see downloaded files

### ISSUE THREAD

**Issue by kefrens** [binhex/arch-delugevpn#204]
Hi,
I'm using latest version on a Synology Docker and I can't see the downloaded files.
1. WebUI is working fine and I can add a torrent and get downloaded. However once completed I can't see it on my NAS.
2. It seems that the torrent get loaded in memory as I see the docker memory increase to multiple gigs
In volume tab under docker settings I have added the 2 below folders with this access:
- ISO/Download -> /data
- docker/delugevpn2/config -> /config

I have tried to move the downloaded file to the root "/" which is in my case a folder ISO/Download however nothing appears.
The only thing I found in the logs when I try to move the completed file:

14:26:28.701 [DEBUG   ][deluge.ui.web.json_api     :202 ] json-request: b'{"method":"core.move_storage","params":[["fe9c412cac71114d81476b29cdb70af8f10f732d"],"/"],"id":57}'

However I don't see any errror.
Does anyone is having the same issue? Otherwise everything seems to work fine (UI or VPN or magnet download works fine)

**Comment by binhex** [comment]
It looks to me as if your host paths are relative as opposed to what they should be which is absolute so please change the paths

**Comment by kefrens** [comment]
This is how it's configured in the NAS
I select ISO/Download as a folder and I had the path /data

![image](https://user-images.githubusercontent.com/25610681/94660281-cefabe80-0348-11eb-9f05-c90fb44430a2.png)

Should it be something else?

**Comment by binhex** [comment]
hmm ok, thats an odd interface, im not too sure what that is doing under the hood, but im assuming its at least putting a leading forward slash on both paths then, so path '/ISO/Download' exists on your host right?, check the case too.

**Comment by kefrens** [comment]
This is the Synology interface, the path "/ISO/Download" is taken when I browse after clicking "Add folder"
![image](https://user-images.githubusercontent.com/25610681/94750158-d1046200-03c8-11eb-8393-df5a97cbc5a1.png)

Admin/root/my user is having full permission on folder (read/write).
Is there another level of log I can set to check what it's doing ?

**Comment by kefrens** [comment]
Hi,

This issue can be closed. Issue was on the Deluge UI.
In preferences -  Downloads, the "download to" must be: "/data/"
(we need the second slash) otherwise it will save it to root on the docker image which is not user accessible (only by SSH)

Cheers
