### ISSUE TITLE
[warn] Incoming port site 'https://portchecker.co/' failed to web scrape, marking as failed

### ISSUE THREAD

**Issue by doczong** [binhex/arch-delugevpn#208]
`[warn] Incoming port site 'https://portchecker.co/' failed to web scrape, marking as failed`

Seeing this every 30 minutes in the logs.

Ping and Curl of page from within the container works.

Because I have PTSD from red lights and warnings as a sysadmin... can I safely ignore this, and / or what can I do to remedy it?

**Comment by binhex** [comment]
yes you can ignore it, it will be fixed in the next release.
