### ISSUE TITLE
PIA Next Gen issue with 10.0.0.0/24 LAN_NETWORK config

### ISSUE THREAD

**Issue by mcpowell87** [binhex/arch-delugevpn#209]
I just encountered this issue that seems to have been resolved in your arch_int_openvpn project.  (see https://github.com/binhex/arch-int-openvpn/issues/15)
For completeness: 
Using the :latest tag.
My LAN_NETWORK is defined as "10.0.0.0/8"

Errors I am getting:
```
2020-10-06 19:30:16,007 DEBG 'start-script' stdout output:
[warn] Unable to successfully download PIA json to generate token from URL 'https://10.0.0.1/authv3/generateToken'
[info] 12 retries left
[info] Retrying in 10 secs...
```
10.0.0.1 is currently the IP of my gateway.

Manually routing the IP each time the container starts seems to fix the issue:

```
[root@1228e2248e5f /]# route -n
Kernel IP routing table
Destination     Gateway         Genmask         Flags Metric Ref    Use Iface
0.0.0.0         10.44.112.1     128.0.0.0       UG    0      0        0 tun0
0.0.0.0         172.18.0.1      0.0.0.0         UG    0      0        0 eth0
10.0.0.0        172.18.0.1      255.0.0.0       UG    0      0        0 eth0
10.44.112.0     0.0.0.0         255.255.255.0   U     0      0        0 tun0
66.115.142.238  172.18.0.1      255.255.255.255 UGH   0      0        0 eth0
128.0.0.0       10.44.112.1     128.0.0.0       UG    0      0        0 tun0
172.18.0.0      0.0.0.0         255.255.0.0     U     0      0        0 eth0
[root@1228e2248e5f /]# route add 10.0.0.1 gw 10.44.112.1
```

I'm hoping that, since the same workaround applies, it will be the same fix you applied in the other project.

**Comment by binhex** [comment]
the workaround should be applied to all vpn images i produce, have you done a docker pull to ensure you are running the latest image?

**Comment by mcpowell87** [comment]
You know, I had that thought after looking through the dockerfile last night, and I have tried to pull everything.  In fact, I have even fully removed the container, deleted the image, and then re-pulled and I still am getting the issue.  I am not sure if there's any hardcore caching going on somewhere, but I just can't get this to work.

Steps I've used to try and force a fresh re-pull:
```
docker-compose stop deluge
docker-compose rm deluge
docker rmi -f e72c2c3517bf
docker pull binhex/arch-delugevpn:latest
docker-compose up -d deluge
```
That _should_ freshly pull the image and create a new container, but I still see the same image id as I did before and I see the same issue described above.

Here's my docker-compose entry that I've been using for quite some time:
```
deluge:                                                       
	image: binhex/arch-delugevpn:latest                   
	container_name: deluge                                
	restart: always                                       
	privileged: true                                      
	cap_add:                                              
		- NET_ADMIN                                   
	ports:                                                
		- 8112:8112                                   
		- 8118:8118                                   
		- 58846:58846                                 
		- 58946:58946                                 
	volumes:                                              
		- /downloads:/downloads                       
		- /home/docker/deluge/config:/config
		- /home/docker/deluge/data:/data    
		- /etc/localtime:/etc/localtime:ro            
	environment:                                          
		- VPN_ENABLED=yes                             
		- VPN_USER=<redacted>                           
		- VPN_PASS=<redacted>                       
		- VPN_PROV=pia                                
		- STRICT_PORT_FORWARD=yes                     
		- STRONG_CERTS=no                             
		- ENABLE_PRIVOXY=yes                          
		- LAN_NETWORK=10.0.0.0/8                      
		- PGID=2000                                   
		- PUID=2000                                   
		- UMASK=002                                   
		- NAME_SERVERS=8.8.8.8,8.8.4.4                
		- DEBUG=true
```
Is there something else I can try, or is there something I missed?

**Comment by mcpowell87** [comment]
Just pulled the latest image and I am still getting the same problem.

**Comment by binhex** [comment]
hi, can you docker exec into your container and then add the following line to the file ```/root/iptable.sh```:-

```
route add 10.0.0.1/32 dev "${VPN_DEVICE_TYPE}"
```
save the change and then reboot the container, let me know if it fixes the issue, if it does i will include the fix.

**Comment by mcpowell87** [comment]
I tacked that command at  the end of the iptable.sh file and rebooted, and it did not work and spit out the same errors.  This is the result from the route -n command after it reboots:

```
Kernel IP routing table
Destination     Gateway         Genmask         Flags Metric Ref    Use Iface
0.0.0.0         10.36.112.1     128.0.0.0       UG    0      0        0 tun0
0.0.0.0         172.18.0.1      0.0.0.0         UG    0      0        0 eth0
10.0.0.0        172.18.0.1      255.0.0.0       UG    0      0        0 eth0
10.36.112.0     0.0.0.0         255.255.255.0   U     0      0        0 tun0
128.0.0.0       10.36.112.1     128.0.0.0       UG    0      0        0 tun0
162.216.47.166  172.18.0.1      255.255.255.255 UGH   0      0        0 eth0
172.18.0.0      0.0.0.0         255.255.0.0     U     0      0        0 eth0
```

**Comment by mcpowell87** [comment]
So I've looked a bit more into this and found that that ```route add 10.0.0.1/32 dev "${VPN_DEVICE_TYPE}"``` is simply not being executed when placed in the iptables.sh script and I'm not sure why.  However, running that in the docker exec manually works fine and fixes the issue.

As a test, I also added a ```route add 10.0.0.1 gw "${vpn_ip}"``` right after the vpn ip is established (in getvpnip.sh), which seems to fix it, but this is definitely a hack.

**Comment by chavezjose** [comment]
+1 on your last fix. I lose it when I restart, but running right when it starts lets it continue and deluge successfully starts. Hacky, but I hope it gets resolved in a future build.

**Comment by mcpowell87** [comment]
I just reproduced this using wireguard as well, but I get extra errors:

```
[warn] Unable to successfully download PIA json payload from URL 'https://10.13.128.1:19999/getSignature' using token <redacted>
```
This can be fixed by adding another route ```route add 10.13.128.1 dev wg0``` (similar to above to fix the generateToken error).  But it's worth noting that even though my home network is defined as 10.0.0.0/8, I don't have any devices using 10.13.128.1, but it's possible the internal network is still conflicting with my home network.

However, a more serious issue is that while using both openvpn and wireguard with these fixes applied, no torrent seems to work.  I have even tried with well-known working torrents such as the ubuntu iso.  So it does seem that the internal network is a bit screwy.  

I attached the supervisord.log from my latest effort.
[supervisord.log](https://github.com/binhex/arch-delugevpn/files/5454177/supervisord.log)

**Comment by Aterfax** [comment]
Pretty sure I just hit this issue also.

**Comment by Aterfax** [comment]
Q7 on this iirc https://github.com/binhex/documentation/blob/master/docker/faq/vpn.md

**Comment by binhex** [comment]
> @binhex Could you add this to the docs on swapping to Next Gen? Not sure when this became a breaking change but it will probably confuse people who are swapping.

Q16, its already in there:- https://github.com/binhex/documentation/blob/master/docker/faq/vpn.md

**Comment by mcpowell87** [comment]
For the record: I am not having issues logging into PIA.  My issue seems to be related specifically to fact that the internal docker network is colliding with my LAN (which is also a 10.0.0.0 network).  It is attempting to hit ```https://10.0.0.1/authv3/generateToken```, but since 10.0.0.1 is my router, it fails.  Once I explicitly set up new routes to redirect traffic to 10.0.0.1 to go through the wg0 or tun0 interface, it progresses past that step.  I suspect there are more collisions that occur even after that generateToken step completes, since the following ```https://10.13.128.1:19999/getSignature``` call fails as well (since I switched to wireguard) until I set up an additional route for it.  What furthers my suspicion of additional network collisions is that torrents no longer work despite authentication succeeding.  It's also worth noting that this behavior is consistent between both wireguard and openvpn, with the exception that wireguard requires a second additional route to proceed (for the getSignature call).

Unfortunately, I do not know much about how to properly isolate the internal docker network from the LAN, but I am curious if there could either be a parameter introduced that changes the network the internal docker container uses so that we can avoid conflicts, or if the container itself can simply choose a network that differs from the one provided by the LAN_NETWORK parameter.

**Comment by jkwmoore** [comment]
> 
> 
> > @binhex Could you add this to the docs on swapping to Next Gen? Not sure when this became a breaking change but it will probably confuse people who are swapping.
> 
> Q16, its already in there:- https://github.com/binhex/documentation/blob/master/docker/faq/vpn.md

Oh I know, that's how I fixed it after further digging - but it isn't immediately obvious is all :)

**Comment by jkwmoore** [comment]
> 
> 
> For the record: I am not having issues logging into PIA. My issue seems to be related specifically to fact that the internal docker network is colliding with my LAN (which is also a 10.0.0.0 network). It is attempting to hit `https://10.0.0.1/authv3/generateToken`, but since 10.0.0.1 is my router, it fails. Once I explicitly set up new routes to redirect traffic to 10.0.0.1 to go through the wg0 or tun0 interface, it progresses past that step. I suspect there are more collisions that occur even after that generateToken step completes, since the following `https://10.13.128.1:19999/getSignature` call fails as well (since I switched to wireguard) until I set up an additional route for it. What furthers my suspicion of additional network collisions is that torrents no longer work despite authentication succeeding. It's also worth noting that this behavior is consistent between both wireguard and openvpn, with the exception that wireguard requires a second additional route to proceed (for the getSignature call).
> 
> Unfortunately, I do not know much about how to properly isolate the internal docker network from the LAN, but I am curious if there could either be a parameter introduced that changes the network the internal docker container uses so that we can avoid conflicts, or if the container itself can simply choose a network that differs from the one provided by the LAN_NETWORK parameter.

Not sure I can add much but I also have a 10.0.X.X based network but I am not having this issue due to my setup - I am VLANing (VLAN10 = 10.0.10.X, VLAN20 = 10.0.20.X etc...) but with subnets of /24 so my gateway is 10.0.X.1 for each.

You might want to consider adjusting your networking subnets? /8 is absolutely enormous block and will be causing your collision due to the routes being applied over a block much larger (than I suspect) you need.

**Comment by Aterfax** [comment]
> 
> 
> > @binhex Could you add this to the docs on swapping to Next Gen? Not sure when this became a breaking change but it will probably confuse people who are swapping.
> 
> Q16, its already in there:- https://github.com/binhex/documentation/blob/master/docker/faq/vpn.md

Oh I know, that's how I fixed it after further digging - but it isn't immediately obvious is all :)

**Comment by Aterfax** [comment]
> 
> 
> For the record: I am not having issues logging into PIA. My issue seems to be related specifically to fact that the internal docker network is colliding with my LAN (which is also a 10.0.0.0 network). It is attempting to hit `https://10.0.0.1/authv3/generateToken`, but since 10.0.0.1 is my router, it fails. Once I explicitly set up new routes to redirect traffic to 10.0.0.1 to go through the wg0 or tun0 interface, it progresses past that step. I suspect there are more collisions that occur even after that generateToken step completes, since the following `https://10.13.128.1:19999/getSignature` call fails as well (since I switched to wireguard) until I set up an additional route for it. What furthers my suspicion of additional network collisions is that torrents no longer work despite authentication succeeding. It's also worth noting that this behavior is consistent between both wireguard and openvpn, with the exception that wireguard requires a second additional route to proceed (for the getSignature call).
> 
> Unfortunately, I do not know much about how to properly isolate the internal docker network from the LAN, but I am curious if there could either be a parameter introduced that changes the network the internal docker container uses so that we can avoid conflicts, or if the container itself can simply choose a network that differs from the one provided by the LAN_NETWORK parameter.

Not sure I can add much but I also have a 10.0.X.X based network but I am not having this issue due to my setup - I am VLANing (VLAN10 = 10.0.10.X, VLAN20 = 10.0.20.X etc...) but with subnets of /24 so my gateway is 10.0.X.1 for each.

You might want to consider adjusting your networking subnets? /8 is absolutely enormous block and will be causing your collision due to the routes being applied over a block much larger (than I suspect) you need.

**Comment by mcpowell87** [comment]
> > For the record: I am not having issues logging into PIA. My issue seems to be related specifically to fact that the internal docker network is colliding with my LAN (which is also a 10.0.0.0 network). It is attempting to hit `https://10.0.0.1/authv3/generateToken`, but since 10.0.0.1 is my router, it fails. Once I explicitly set up new routes to redirect traffic to 10.0.0.1 to go through the wg0 or tun0 interface, it progresses past that step. I suspect there are more collisions that occur even after that generateToken step completes, since the following `https://10.13.128.1:19999/getSignature` call fails as well (since I switched to wireguard) until I set up an additional route for it. What furthers my suspicion of additional network collisions is that torrents no longer work despite authentication succeeding. It's also worth noting that this behavior is consistent between both wireguard and openvpn, with the exception that wireguard requires a second additional route to proceed (for the getSignature call).
> > Unfortunately, I do not know much about how to properly isolate the internal docker network from the LAN, but I am curious if there could either be a parameter introduced that changes the network the internal docker container uses so that we can avoid conflicts, or if the container itself can simply choose a network that differs from the one provided by the LAN_NETWORK parameter.
> 
> Not sure I can add much but I also have a 10.0.X.X based network but I am not having this issue due to my setup - I am VLANing (VLAN10 = 10.0.10.X, VLAN20 = 10.0.20.X etc...) but with subnets of /24 so my gateway is 10.0.X.1 for each.
> 
> You might want to consider adjusting your networking subnets? /8 is absolutely enormous block and will be causing your collision due to the routes being applied over a block much larger (than I suspect) you need.

Thank you for the tips.  I changed the LAN_NETWORK to 10.0.0.0/21, which allows for the getSignature call to succeed without having to explicitly adding that second rule, while still covering my network.  My network does also have a number of VLANs (each are 10.0.x.0/24), however since my servers are on the 10.0.0.x network, the gateway is still 10.0.0.1.

**Comment by HNGamingUK** [comment]
Equally as mentioned in #226 you can add seperate subnets by comma seperating them.

**Comment by mcpowell87** [comment]
> Equally as mentioned in #226 you can add seperate subnets by comma seperating them.

I wound up moving my servers to a new VLAN with a 10.0.10.0/24 subnet and used the tip from the mentioned issue to assign individual LANs except for 10.0.0.0/24.  It seems to be working so far.  Thanks for all the help everyone.
