### ISSUE TITLE
PIA Documentation not up to date

### ISSUE THREAD

**Issue by oliverde8** [binhex/arch-delugevpn#214]
First of all thank you for all these great dockers. 

I think there is an issue with the documentation 

> PIA users - The URL to download the OpenVPN configuration files and certs is:-
> 
> https://www.privateinternetaccess.com/openvpn/openvpn.zip

The URL should be https://www.privateinternetaccess.com/openvpn/openvpn-nextgen.zip at least my docker stopped working recently and that's how I fixed it. 

Regards,

**Comment by binhex** [comment]
I've updated the link in the readme.md and it should get updated on docker hub when the image next gets built.
