### ISSUE TITLE
Response code 000 from curl != 2xx ?

### ISSUE THREAD

**Issue by lsaadeh** [binhex/arch-delugevpn#218]
Hi all,

I regularly see this issue in the logs and deluge does start, any idea what its from or how I can begin diagnosing it?

`[info] Attempting to curl http://209.222.18.222:2000/?client_id=xxxxxxxxxxxxxxxxxxxxxx...
2020-10-22 23:01:42,065 DEBG 'start-script' stdout output:
[warn] Response code 000 from curl != 2xx
[warn] Exit code 7 from curl != 0
[info] 12 retries left
[info] Retrying in 10 secs...`

**Comment by binhex** [comment]
you are using legacy network from pia, which is being dismantled and replaced with next-gen, move over to next-gen, see Q19:- https://github.com/binhex/documentation/blob/master/docker/faq/vpn.md

**Comment by camillescott** [comment]
I'm having the same issue, but I've updated my openvpn config. Oddly, I'm getting:

```
2020-11-13 19:10:34,440 DEBG 'start-script' stdout output:
[warn] PIA endpoint 'spain.privacy.network' is not in the list of endpoints that support port forwarding, DL/UL speeds maybe slow
[info] Please consider switching to one of the endpoints shown below

2020-11-13 19:10:34,441 DEBG 'start-script' stdout output:
[info] List of PIA endpoints that support port forwarding:-
[info] ca-toronto.privateinternetaccess.com
[info] ca-montreal.privateinternetaccess.com
[info] ca-vancouver.privateinternetaccess.com
[info] de-berlin.privateinternetaccess.com
[info] de-frankfurt.privateinternetaccess.com

2020-11-13 19:10:34,441 DEBG 'start-script' stdout output:
[info] france.privateinternetaccess.com
[info] czech.privateinternetaccess.com
[info] spain.privateinternetaccess.com
[info] ro.privateinternetaccess.com
[info] israel.privateinternetaccess.com
[info] Attempting to get dynamically assigned port...

```

Those endpoints appear to be legacy, right? I have pulled the latest image as well.

**Comment by camillescott** [comment]
Actually, scratch that, I just had to re-run the startup command. D'oh.

**Comment by mf-lit** [comment]
@camillescott 
> Actually, scratch that, I just had to re-run the startup command. D'oh.

I've just run into exactly the same issue, please can you explain what you mean by "re-run the startup command" ? I'd appreciate it.
