### ISSUE TITLE
Cant start since PIA-NextGen

### ISSUE THREAD

**Issue by HenneCuppens** [binhex/arch-delugevpn#219]
Hello,

I just updated to the latest version of delugevpn on unraid 6.8.3(because I noticed that my VPN was not working anymore). Normally it is an update problem, so I did. But now my deluge wont start I added the new PIA-nextgen files, (as said in https://github.com/binhex/documentation/blob/master/docker/faq/vpn.md q19) and is giving me these errors:

2020-11-02 20:28:20 OPTIONS ERROR: failed to negotiate cipher with server. Add the server's cipher ('BF-CBC') to --data-ciphers (currently 'AES-256-GCM:AES-128-GCM:AES-128-CBC') if you want to connect to this server.

2020-11-02 20:28:20 ERROR: Failed to apply push options

2020-11-02 20:28:20 Failed to open tun/tap interface

2020-11-02 20:28:20 SIGHUP[soft,process-push-msg-failed] received, process restarting

2020-11-02 20:28:20 DEPRECATED OPTION: --cipher set to 'aes-128-cbc' but missing in --data-ciphers (AES-256-GCM:AES-128-GCM). Future OpenVPN version will ignore --cipher for cipher negotiations. Add 'aes-128-cbc' to --data-ciphers or change --cipher 'aes-128-cbc' to --data-ciphers-fallback 'aes-128-cbc' to silence this warning.

It seems like there are new settings in the menu of the docker container. Anyone else has this issue, or knows how I can solve this?

Thanks in advance!

**Comment by tom472** [comment]
Going to make some guesses here - 

That error appears to be an issue with OpenVPN 2.5 which ONLY allows AES-256-GCM AES-128-GCM by default. 
The config files provided by PIA only set up CBC ciphers.
(Not my source - found [here](https://www.reddit.com/r/PrivateInternetAccess/comments/j1iyl7/openvpn_client_no_longer_connects_cipher_not/)) 

Going to guess that the OpenVPN version on the docker image that currently has the "latest" tag (as of now):

> Tag    | Commit  | Created      | Updated
> latest | e64b1ef | 15 hours ago | 15 hours ago

Has had OpenVPN 2.5 added into it .. maybe.. 

The issue appears to go away if you roll back to a container version (tag) just before that push.
binhex/arch-delugevpn:2.0.4.dev38_g23a48dd01-2-14
(Last pushed a day ago)

Again - making some guesses here and then the real crux is do we wait for PIA to fix/adjust?
Or is there anything that can be adjusted in the container.

**Comment by mistergoodwin** [comment]
Just adding confirmation this problem exists for me also. I've added `data-ciphers-fallback aes-256-gcm` into my ovpn file with no change to the exact same errors as OP above. it's as if it's ignored completely.

I have rolled back to `tag: 2.0.4.dev38_g23a48dd01-2-14` for now where the same ovpn file continues to work.

**Comment by HenneCuppens** [comment]
I did some further testing on this, I found out the newgen only works on some servers, even though PIA adds all the servers in the ovpn configs download....

https://www.privateinternetaccess.com/blog/private-internet-access-next-generation-network-now-available-for-beta-preview/

I did not test all the servers, but I can see when I load in Amsterdams config my deluge starts up without any errors.

So for other users, check if changing the ovpn file to one of those files works for you.

**Comment by PTRFRLL** [comment]
Looks like those [FAQ](https://github.com/binhex/documentation/blob/master/docker/faq/vpn.md) were updated and the current solution works for me:

> The fix for this is to specify a fallback cipher on the client side to a cipher that PIA does support, this is done by editing the file /config/openvpn/<file with a ovpn extension> and adding/replacing the following lines (use notepad++ NOT notepad):-

```
cipher aes-256-gcm
ncp-disable
```

> Remove this line (if present):-

```
data-ciphers-fallback aes-256-gcm
```

> Save and restart the container for the change to take effect.

**Comment by jeffreyswiggins** [comment]
This change did not work for me.  I had rolled back to **binhex/arch-delugevpn:2.0.4.dev38_g23a48dd01-2-13** so I updated my docker-compose to use the latest and updated each OVPN file with the new info.  There was no **data-ciphers-fallback aes-256-gcm** in any OVPN file I had from PIA which were downloaded new yesterday when i started troubleshooting this issue.  The result of the changes was the same problem so I reverted back to the older version.

**Comment by groot-stuff** [comment]
> Looks like those [FAQ](https://github.com/binhex/documentation/blob/master/docker/faq/vpn.md) were updated and the current solution works for me (Q/A 22):
> 
> > The fix for this is to specify a fallback cipher on the client side to a cipher that PIA does support, this is done by editing the file /config/openvpn/ and adding/replacing the following lines (use notepad++ NOT notepad):-
> 
> ```
> cipher aes-256-gcm
> ncp-disable
> ```
> 
> > Remove this line (if present):-
> 
> ```
> data-ciphers-fallback aes-256-gcm
> ```
> 
> > Save and restart the container for the change to take effect.

Thanks @PTRFRLL !

Confirming this worked for me. 

Not sure if it matters at all, but I always use a custom generated .opvn file (not ones from the mass .zip file).

`nextgen-ca_vancouver-aes-128-cbc-udp-dns.ovpn` was generated on pia.com with these settings:
- **Serers:** Nextgen
- **OpenVPN Version:** OpenVPN 2.4 or newer
- **Platform:** Linux
- **Region:** North America, CA Vancouver
- **Port:** UDP/1198, RSA-2048, AES-128-CBC, SHA1 (Recommended)

After downloading I opened it in Notepad++ and replaced the line
`cipher aes-128-cbc` 
with
`cipher aes-256-gcm`
then added this line below it
`ncp-disable`

Saved the file then restarted the binhex-delugevpn container and all was well.

Other config items to note: 
- No VPN Options were specified in the container config
- Strict port forwarding is OFF (SPF doesn't allow my SOCKS5 proxy from another provider, configured within Deluge to connect when it is ON... but speeds seem to be okay, no change from before this issue).

**Comment by earef** [comment]
> Looks like those [FAQ](https://github.com/binhex/documentation/blob/master/docker/faq/vpn.md) were updated and the current solution works for me (Q/A 22):
> 
> > The fix for this is to specify a fallback cipher on the client side to a cipher that PIA does support, this is done by editing the file /config/openvpn/ and adding/replacing the following lines (use notepad++ NOT notepad):-
> 
> ```
> cipher aes-256-gcm
> ncp-disable
> ```
> 
> > Remove this line (if present):-
> 
> ```
> data-ciphers-fallback aes-256-gcm
> ```
> 
> > Save and restart the container for the change to take effect.

This worked on my client config file perfectly.
