### ISSUE TITLE
Update to the newest deluge

### ISSUE THREAD

**Issue by smvoss** [binhex/arch-delugevpn#23]
I just wanted to post this while I was thinking about it, and if someone else doesn't get around to it I can, but:

I had to skim through your install scripts to figure out how you were installing deluge (using the aor's latest, clever) to see if you were using the newest version that was just recently.

Because of the method you used, the user needs to know that they have to actually not only remove the container, but also use rmi to get rid of the image as well otherwise it doesn't see an update to grab due to the image not actually changing between versions (which then downloads the new deluge).

Only took a few minutes to hunt down, but still took a minute and might be worth capturing the work done in the readme to streamline this in the future.

**Comment by binhex** [comment]
Yes i dont go down the road of auto updating apps on startup, there are several good reasons for this, such as - 

1. repeatability - a tagged image pulled down today will be exactly the same tomorrow, independent of any external changes - this is also what docker is meant to be, a shippable point in time container.

2. complexity - having scripts that auto update is tricky, having to support both offline and online modes.

3. speed - auto updating on startup is going to be sloooooow, as is checking.

all of the images i produce use the same method, if you want to be notified of updates then i would recommend checking the tags, as i tag every built image - 

https://hub.docker.com/r/binhex/arch-delugevpn/builds/

**Comment by smvoss** [comment]
I agree, and I believe that is the correct functionality.

My comment didn't suggest changing this, it instead suggested outlining that in a brief section in the readme so that anyone who wants to update and has issues (due to most other docker containers NOT using this workflow) can easily find the solution they are looking for without having to dig through the install scripts.

**Comment by binhex** [comment]
No problem I will try and come up with some wording for the readme
