### ISSUE TITLE
Deprecated cipher AES-256-CBC

### ISSUE THREAD

**Issue by kriegalex** [binhex/arch-delugevpn#231]
Here is the issue:
```
2020-11-30 12:13:52 DEPRECATED OPTION: --cipher set to 'AES-256-CBC' but missing in --data-ciphers (AES-256-GCM:AES-128-GCM). Future OpenVPN version will ignore --cipher for cipher negotiations. Add 'AES-256-CBC' to --data-ciphers or change --cipher 'AES-256-CBC' to --data-ciphers-fallback 'AES-256-CBC' to silence this warning.
```

Version : Docker binhex/arch-delugevpn:latest

**Comment by binhex** [comment]
issue related to what?, thats a deprecation warning triggered by a ovpn file that is using an old cypher, nothing to do with my code im afraid.

**Comment by kriegalex** [comment]
Well, I think it is, because it is written in clear in the warning what to do : Add 'AES-256-CBC' to --data-ciphers. I guess this is up to you, no, when calling OpenVPN ?

You can't ignore people which get this cipher from their VPN provider :(

**Comment by binhex** [comment]
> Add 'AES-256-CBC' to --data-ciphers. I guess this is up to you, no, when calling OpenVPN ?

no, that is defined in the ovpn file.

**Comment by kriegalex** [comment]
Ok, so because of the message being so precise about using this flag, I did not see that indeed this could go into the ovpn file directly. 

So taking this issue from another angle, if --cipher is prone to be deprecated, I'm sure you will get hammered at some point by requests from people using providers that don't update their stuff or people using very old ovpn.

Maybe you could get ahead of the curve by treating this directly at the OpenVPN level ? It is indeed only a warning, but soon to because an error.

**Comment by binhex** [comment]
> Maybe you could get ahead of the curve by treating this directly at the OpenVPN level ? It is indeed only a warning, but soon to because an error.

sorry but i wont do this, it is not always as simple as replacing ```cipher``` with ```data-ciphers-fallback``` or ```data-ciphers```, as i found out to when i was debugging issues with PIA, and i dont want to get into tweaking ovpn config files on a per vpn provider basis, i just dont have the time to do this.
