### ISSUE TITLE
Options error: --proto tcp is ambiguous in this context. Please specify --proto tcp-server or --proto tcp-client

### ISSUE THREAD

**Issue by Kamakiri77** [binhex/arch-delugevpn#232]
I'm getting an error that says please use tcp-server or tcp-client. I can't find where to put this info to get it work.

Options error: --proto tcp is ambiguous in this context. Please specify --proto tcp-server or --proto tcp-client

**Comment by Bodgers** [comment]
Same as https://github.com/binhex/arch-delugevpn/issues/230 - `test` works and fix to `latest` seems imminent...

**Comment by binhex** [comment]
fixed in latest, please pull down (just built).
