### ISSUE TITLE
Unable to resolve DNS once connected to VPN

### ISSUE THREAD

**Issue by jscottdouglas** [binhex/arch-delugevpn#234]
Using this docker with cloudbox, was working up til i rebooted the docker now as soon as VPN connect i am not able to resolve any domains.  Any help to resolve this would be appreciated.  Although i am not using PIA, i am using torguard.

**Comment by binhex** [comment]
what have you defined for 'NAME_SERVERS'?.

**Comment by jscottdouglas** [comment]
I have nothing defined in the ovpn file, however the output of resolv.conf 

nameserver 209.222.18.222
nameserver 84.200.69.80
nameserver 37.235.1.174
nameserver 1.1.1.1
nameserver 209.222.18.218
nameserver 37.235.1.177
nameserver 84.200.70.40
nameserver 1.0.0.1

**Comment by jscottdouglas** [comment]
seems only way i was able to resolve it is by adding dhcp-option DNS x.x.x.x i used torguards DNS and it seems to be working now i also update the nameservers in the docker to reflect torguards dns as well.. after verify the dhcp-option worked and that seemed to get everything rolling..
