### ISSUE TITLE
Problem with DNS before openvpn

### ISSUE THREAD

**Issue by SturkenSnure** [binhex/arch-delugevpn#235]
I have run into a problem with DNS. It works if you use open DNS, like google, but if you add your vpn DNSes in the NAME_SERVERS option, you run into the following problem:

2020-12-04 09:08:20,287 DEBG 'start-script' stdout output:
[crit] 'openvpn.integrity.st' cannot be resolved, possible DNS issues, exiting...

This is because the container tries to use the VPN DNS before starting the VPN. The VPN DNS'es are only available over VPN. Is there any way to make it use another DNS before starting openvpn?

**Comment by binhex** [comment]
> This is because the container tries to use the VPN DNS before starting the VPN. The VPN DNS'es are only available over VPN. Is there any way to make it use another DNS before starting openvpn?

you define which name server you want to use by changing the value for env var NAME_SERVERS, i would advise against using vpn dns if its only reachable after the tunnel is established, simply use a public name server.
