### ISSUE TITLE
web ui showing external ip n/a

### ISSUE THREAD

**Issue by fooxytv** [binhex/arch-delugevpn#238]
I could be doing something stupid, but I'm sure this was working a few weeks ago.

When I browse to the Web UI I usually get a visual on the External IP address in the bottom right, at the moment it's showing as N/A. I can see that it's connected to the VPN and a `curl ipinfo.io` within the Docker container it shows my external IP address and location.

I've reverted to a different image version and also used different VPN providers and still same results.

**Comment by fooxytv** [comment]
Indeed it was me doing something wrong, seems to be back up and working again.

**Comment by kaoslabs** [comment]
@fooxytv I am having the same issue after pulling the latest image. What was your fix?

**Comment by fooxytv** [comment]
Hey Kyle,

The solution for me was to clear the config and image locally and re-pull.

I’m also using 2.0.4.dev38_g23a48dd01-2-15 image from Docker Hub.

Hope that helps, good luck!

Simon

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by Pleighgue** [comment]
Hey I see you found out what you were doing wrong, I'm probably making the same mistake but can't figure out what and not seeing this particular issue elsewhere. Would really appreciate if you had any suggestions. Thanks
