### ISSUE TITLE
"critical" invalid logging parameter for deluged daemon

### ISSUE THREAD

**Issue by oregonpillow** [binhex/arch-delugevpn#239]
I followed readme instructions. Booted up and WebUI would not show. Checked docker logs and Deluged cannot start because `critical` is not a valid logging parameter it said. I ended up changing to `none` and then it worked.

Is the Readme instructions for docker run, incorrect?

**Comment by binhex** [comment]
i guess this mustb e a change with deluge 2.x, as the readme was created when deluge 1.x was latest stable, im pretty sure 'info' is a working logging level, and this will show you all info, warning, and error messages, so its quite verbose, im not sure if that is what you are trying to achieve?.

**Comment by oregonpillow** [comment]
from the docker logs:

`deluged: error: argument -L/--loglevel: invalid choice: 'critical' (choose from 'info', 'INFO', 'warn', 'WARN', 'warning', 'WARNING', 'error', 'ERROR', 'none', 'NONE', 'debug', 'DEBUG', 'trace', 'TRACE', 'garbage', 'GARBAGE')`
