### ISSUE TITLE
Ability to specify an ovpn/cert directory to use

### ISSUE THREAD

**Issue by ErroneousBosch** [binhex/arch-delugevpn#25]
To expand out the usability of this docker, could we get an option to load a specified ovpn file on a mounted volume? Something like:

`-e USE_OVPNFILE=TRUE -e OVPN_FILE=/config/openvpn/default.ovpn `

Would open this up to using other VPN services, which would be nice given how overloaded PIA has become. Then I could just place my ovpn file and certs into wherever that is mounted and use my own VPN  service.

**Comment by binhex** [comment]
I am considering parsing the ovpn file, if the env vars aren't set for port and protocol and endpoint then use values in ovpn, this would then allow either env var definition or ovpn, sound OK?

**Comment by keirlawson** [comment]
Sounds good, though there are a lot of options in those .ovpn files, not sure they are currently all covered by the env vars

**Comment by binhex** [comment]
They aren't but that hasn't been much of an issue as openvpn reads in the options in the ovpn file as well, the other option is purely to use ovpn file only and don't use env vars, I will have a think about it.

**Comment by ErroneousBosch** [comment]
Since an OVPN file is setable as an environment variable (config), your setup script should still be usable if you add into your if-then chain that if an OVPN file is specified, it skips setting the other environment variables
