### ISSUE TITLE
Privoxy not starting (After last update)

### ISSUE THREAD

**Issue by noxmotta** [binhex/arch-delugevpn#257]
LOG:

> 2021-02-26 19:11:03,514 DEBG 'watchdog-script' stdout output:
[info] Privoxy not running

2021-02-26 19:11:03,516 DEBG 'watchdog-script' stdout output:
[info] Attempting to start Privoxy...

2021-02-26 19:11:04,521 DEBG 'watchdog-script' stdout output:
[info] Privoxy process started
[info] Waiting for Privoxy process to start listening on port 8118...

2021-02-26 19:11:04,526 DEBG 'watchdog-script' stdout output:
[info] Privoxy process listening on port 8118

2021-02-26 19:11:04,521 DEBG 'watchdog-script' stdout output:
[info] Privoxy process started
[info] Waiting for Privoxy process to start listening on port 8118...

2021-02-26 19:11:04,526 DEBG 'watchdog-script' stdout output:
[info] Privoxy process listening on port 8118

2021-02-26 19:11:34,568 DEBG 'watchdog-script' stdout output:
[info] Privoxy not running

2021-02-26 19:11:34,569 DEBG 'watchdog-script' stdout output:
[info] Attempting to start Privoxy...

2021-02-26 19:11:35,575 DEBG 'watchdog-script' stdout output:
[info] Privoxy process started
[info] Waiting for Privoxy process to start listening on port 8118...

2021-02-26 19:11:35,578 DEBG 'watchdog-script' stdout output:
[info] Privoxy process listening on port 8118

2021-02-26 19:12:06,630 DEBG 'watchdog-script' stdout output:
[info] Privoxy not running

2021-02-26 19:12:06,631 DEBG 'watchdog-script' stdout output:
[info] Attempting to start Privoxy...

2021-02-26 19:12:07,637 DEBG 'watchdog-script' stdout output:
[info] Privoxy process started
[info] Waiting for Privoxy process to start listening on port 8118...

2021-02-26 19:12:07,640 DEBG 'watchdog-script' stdout output:
[info] Privoxy process listening on port 8118

2021-02-26 19:12:37,677 DEBG 'watchdog-script' stdout output:
[info] Privoxy not running

2021-02-26 19:12:37,678 DEBG 'watchdog-script' stdout output:
[info] Attempting to start Privoxy...

2021-02-26 19:12:38,683 DEBG 'watchdog-script' stdout output:
[info] Privoxy process started
[info] Waiting for Privoxy process to start listening on port 8118...

2021-02-26 19:12:38,687 DEBG 'watchdog-script' stdout output:
[info] Privoxy process listening on port 8118

2021-02-26 19:12:38,683 DEBG 'watchdog-script' stdout output:
[info] Privoxy process started
[info] Waiting for Privoxy process to start listening on port 8118...

2021-02-26 19:12:38,687 DEBG 'watchdog-script' stdout output:
[info] Privoxy process listening on port 8118

**Comment by edrohler** [comment]
That log output shows it has started. If you're running into an issue where Radarr/Sonarr/Lidarr are reporting the clients/indexers are unavailable after the last update, see the binhex's thread on [Unraid Forums](https://forums.unraid.net/topic/44109-support-binhex-delugevpn/?do=findComment&comment=952516)

**Comment by Ed-Savill** [comment]
I am also getting this same issue.

How can I rebuild to pervious image?

**Comment by keifererikson** [comment]
Also having the same issue.

Am I able to roll back to a previous version? My whole Unraid server is now unable to function without this privoxy.

**Comment by noxmotta** [comment]
still not working on the new update

**Comment by Ed-Savill** [comment]
> Am I able to roll back to a previous version? My whole Unraid server is now unable to function without this privoxy.

I had to roll back. This is the last working update for me;

binhex/arch-delugevpn@sha256:ecd2b9749289d731901aa94d33526cb8e2e91c6f15b8eaccc8c1007a4e2ef306

**Comment by boxee-htpc** [comment]
same issue with version binhex/arch-delugevpn:2.0.4.dev38-g23a48dd01-3-03

**Comment by stealthlego** [comment]
Also getting errors after most recent update. 

Failed with docker version: 2.0.4.dev38-g23a48dd01-3-05
Was able to roll back to this version to finally get things working again: 2.0.4.dev38_g23a48dd01-2-18

**Comment by binhex** [comment]
guys i am not able to reproduce this issue, please can you try deleting /config/privoxy (folder) and restart the container, its possible its a config change in later version of privoxy thats causing it.

**Comment by Aceriz** [comment]
> guys i am not able to reproduce this issue, please can you try deleting /config/privoxy (folder) and restart the container, its possible its a config change in later version of privoxy thats causing it.


Hey so I gave it a try deleting the config/privoxy folder forcing an update then restarting the docker... still getting error unfortuantely 

What might be helpful to troubleshoot this ?  (I am very much not smart enough to understand )

**Comment by binhex** [comment]
can you please do this:- https://github.com/binhex/documentation/blob/master/docker/faq/help.md

**Comment by jorgenjanssonlee** [comment]
Hi binhex, I just realised I have the same problem with Privoxy not starting. Same errors in the supervisord.log as reported above.

This line is repeated over and over in /appdata/binhex-delugevpn/privoxy/logfile
`2021-02-26 00:30:36.928 14a649c341c0 Fatal error: can't bind to INADDR_ANY:8118: There may be another Privoxy or some other proxy running on port 8118`

Debug supervisord.log here:
https://pastebin.com/30S8pGa5

Hopefully this is useful in troubleshooting, let me know if you need anything else.

**Comment by jorgenjanssonlee** [comment]
Things look ok from the container console I think:
```
sh-5.1# ps aux | grep privoxy
nobody     593  0.0  0.0   4236  2704 ?        Ss   12:20   0:00 /usr/bin/privoxy /config/privoxy/config
root      2902  0.0  0.0   6268  2248 pts/0    S+   13:01   0:00 grep privoxy

sh-5.1# netstat -tulpn | grep LISTEN
tcp        0      0 10.4.199.147:29578      0.0.0.0:*               LISTEN      555/python          
tcp        0      0 0.0.0.0:8112            0.0.0.0:*               LISTEN      597/deluge-web      
tcp        0      0 0.0.0.0:8118            0.0.0.0:*               LISTEN      593/privoxy         
tcp        0      0 0.0.0.0:8989            0.0.0.0:*               LISTEN      -                   
tcp        0      0 127.0.0.1:58846         0.0.0.0:*               LISTEN      555/python          
tcp6       0      0 :::7878                 :::*                    LISTEN      -                   
tcp6       0      0 :::9117                 :::*                    LISTEN      -                   

sh-5.1# ss -tulwn
Netid       State        Recv-Q       Send-Q             Local Address:Port              Peer Address:Port      Process      
udp         UNCONN       0            0                   10.4.199.147:29578                  0.0.0.0:*                      
udp         UNCONN       0            0                        0.0.0.0:6771                   0.0.0.0:*                      
udp         UNCONN       0            0                        0.0.0.0:58571                  0.0.0.0:*                      
udp         UNCONN       0            0                           [::]:58571                     [::]:*                      
tcp         LISTEN       0            5                   10.4.199.147:29578                  0.0.0.0:*                      
tcp         LISTEN       0            50                       0.0.0.0:8112                   0.0.0.0:*                      
tcp         LISTEN       0            128                      0.0.0.0:8118                   0.0.0.0:*                      
tcp         LISTEN       0            128                      0.0.0.0:8989                   0.0.0.0:*                      
tcp         LISTEN       0            50                     127.0.0.1:58846                  0.0.0.0:*                      
tcp         LISTEN       0            128                            *:7878                         *:*                      
tcp         LISTEN       0            128                            *:9117                         *:*                      
sh-5.1# 
```

**Comment by jorgenjanssonlee** [comment]
Is the problem with the command to check if privoxy is running in watchdog.sh? I think pgrep -x expects the process name, not the full path?

```
sh-5.1# pgrep privoxy -l
614 privoxy

sh-5.1# pgrep -x "/usr/bin/privoxy"

sh-5.1# pgrep -x "privoxy"
614
sh-5.1# 
```

**Comment by noxmotta** [comment]
deleted all the deluge app data fresh install of doker deluge image still the same error

**Comment by binhex** [comment]
thanks for the details guys, i was previously unable to reproduce this, but spotted the reason, this only affects delugevpn, the other vpn images are set correctly to pgrep -fa /usr/bin/privoxy, so fix is now in and image is built, please pull down and let me know ow you get on.

**Comment by noxmotta** [comment]
no error in console but sonar and radar not working with proxy

**Comment by jorgenjanssonlee** [comment]
Working perfectly for me and logs are coming up clean again
