### ISSUE TITLE
Unable to reach docker containers running in bridge mode on same host via host IP (unraid)

### ISSUE THREAD

**Issue by jorgenjanssonlee** [binhex/arch-delugevpn#258]
I reported this on the unraid support thread but think it got lost in the general chatter after the latest delugevpn update.
https://forums.unraid.net/topic/44109-support-binhex-delugevpn/?do=findComment&comment=952743

In short, from the delugevpn container it's no longer possible to communicate with other docker containers running on the same host in bridge mode using the host IP. 
It is possible to communicate with these containers via their docker bridge IP (172.x.x.x), but those are dynamically assigned and will/may change on restart of the containers.
Prior to the release with the iptables tightening this worked as expected.

For example, I'm running NzbGet in bridge mode on the same (unraid) host as delugevpn. 
From the delugevpn console:
* I CAN NOT connect to NzbGet as a download client using <unraidIP=192.168.11.111>:6789. Connection times out.
* I CAN connect to NzbGet using it's docker bridge IP (172.17.0.3:6789) 

```
sh-5.1# curl -v 192.168.11.111:6789
*   Trying 192.168.11.111:6789...
* connect to 192.168.11.111 port 6789 failed: Connection timed out
* Failed to connect to 192.168.11.111 port 6789: Connection timed out
* Closing connection 0
curl: (28) Failed to connect to 192.168.11.111 port 6789: Connection timed out
sh-5.1# curl -v 172.17.0.3:6789
*   Trying 172.17.0.3:6789...
* Connected to 172.17.0.3 (172.17.0.3) port 6789 (#0)
> GET / HTTP/1.1
> Host: 172.17.0.3:6789
> User-Agent: curl/7.75.0
> Accept: */*
> 
* Mark bundle as not supporting multiuse
< HTTP/1.1 401 Unauthorized
< WWW-Authenticate: Basic realm="NZBGet"
< Connection: close
< Content-Type: text/plain
< Content-Length: 0
< Server: nzbget-21.0
< 
* Closing connection 0
```
This becomes a problem when sonarr/radarr are sharing the delugevpn network, as they cannot communicate with nzbget as a download client. Unless I use teh docker 172.x.x.x address, or join nzbget to the delugevpnnetwork as well. Both have drawbacks, but for now I'm using the docker IP and just have to remember to go in and reconfigure the radarr/sonarr download client IP everytie I restart nzbget...

**Comment by binhex** [comment]
See the recommended post in the support thread on the unraid forum and follow either q25 or q26

**Comment by jorgenjanssonlee** [comment]
**Steps to reproduce:**
1. Run another container in bridge mode on the same host as delugevpn
2. From delugevpn console try to connect to other container with `curl -v <hostIP>:port`
3. Try to connect to other container with `curl -v <dockerIP>:port`

**Expected behaviour**
both curl commands can establish a connection

**Actual behaviour**
- connection to host IP times out
- connection to docker IP succeeds

**Addtional info**

docker run command for delugvpn:
```
root@localhost:# /usr/local/emhttp/plugins/dynamix.docker.manager/scripts/docker run -d --name='binhex-delugevpn' --net='bridge' --privileged=true -e TZ="Australia/Sydney" -e HOST_OS="Unraid" -e 'VPN_ENABLED'='yes' -e 'VPN_USER'='redacted' -e 'VPN_PASS'='redacted' -e 'VPN_PROV'='pia' -e 'VPN_CLIENT'='wireguard' -e 'VPN_OPTIONS'='' -e 'STRICT_PORT_FORWARD'='yes' -e 'ENABLE_PRIVOXY'='yes' -e 'LAN_NETWORK'='192.168.11.0/24, 10.253.0.0/24' -e 'NAME_SERVERS'='84.200.69.80,37.235.1.174,1.1.1.1,37.235.1.177,84.200.70.40,1.0.0.1' -e 'DELUGE_DAEMON_LOG_LEVEL'='info' -e 'DELUGE_WEB_LOG_LEVEL'='info' -e 'ADDITIONAL_PORTS'='7878,8989,9117,6789' -e 'DEBUG'='false' -e 'UMASK'='000' -e 'PUID'='99' -e 'PGID'='100' -p '8112:8112/tcp' -p '58846:58846/tcp' -p '58946:58946/tcp' -p '58946:58946/udp' -p '8119:8118/tcp' -p '9117:9117/tcp' -p '7878:7878/tcp' -p '8989:8989/tcp' -v '/mnt/cache/appdata/binhex-delugevpn/downloads/':'/data':'rw' -v '/mnt/user/Downloads/':'/downloads/':'rw' -v '/mnt/cache/appdata/binhex-delugevpn':'/config':'rw' --sysctl="net.ipv4.conf.all.src_valid_mark=1" 'binhex/arch-delugevpn'
```

docker run command for NzbGet:
```
root@localhost:# /usr/local/emhttp/plugins/dynamix.docker.manager/scripts/docker run -d --name='binhex-nzbget' --net='bridge' -e TZ="Australia/Sydney" -e HOST_OS="Unraid" -p '6789:6789/tcp' -v '/mnt/cache/appdata/nzbget/':'/config':'rw' -v '/mnt/cache/appdata/nzbget/':'/data':'rw' -v '/mnt/user/Downloads/':'/downloads':'rw' --cap-add=SYS_NICE --log-opt max-size=50m --log-opt max-file=1 'binhex/arch-nzbget' 
```

**Comment by jorgenjanssonlee** [comment]
> See the recommended post in the support thread on the unraid forum and follow either q25 or q26

Yep, have done that and everything in the same container network (deluge, jacket, sonarr, radar) can communicate without problems by using localhost.
This issue is about containers within the deluge container network being unable to communicate with containers OUTSIDE the deluge container network.

I could of course be missing something, but I think I've followed the instructions and this issue still occurs. Are you not able to reproduce this behaviour?

**Comment by binhex** [comment]
I will take a look and see if I can replicate this tonight.

**Comment by binhex** [comment]
One quick question, what apps need to talk outbound that are not already in the VPN shared network?

**Comment by jorgenjanssonlee** [comment]
Thanks, no rush! I'm not really looking for support, just think this is a genuine issue with the iptables. If I knew more than what 5 minutes of googling have taught me about iptables I would try to troubleshoot a bit more on my own, but the learning curve is too steep...

NzbGet is the main use case. I don't want to run it inside the VPN network for performance reasons. But maybe that's not actually a real-life concern and I should just move it in.

**Comment by mgantlett** [comment]
What do you configure for ADDITIONAL_PORTS?

**Comment by mgantlett** [comment]
I had issues with the latest release but different than your issue.  To fix my issue I had to add my ports ADDITIONAL_PORTS=8989,7878,9117.  I compared your setup to mine.   One major difference I see is I'm using container network mode.  Have you tried or can you run the other containers in container network mode?

**Comment by jorgenjanssonlee** [comment]
> 
> 
> I had issues with the latest release but different than your issue. To fix my issue I had to add my ports ADDITIONAL_PORTS=8989,7878,9117. I compared your setup to mine. One major difference I see is I'm using container network mode. Have you tried or can you run the other containers in container network mode?

Yes, I'm running other containers (radarr/sonarr/jackett) in network bridging with delugeVPN and have added the ADDIONAL_PORTS. That all works great. The problem is only with NzbGet running outside the delugevpn network.
I have no doubt this will start working if I move NzbGet inside the delugevpn network as well. I'd like to avoid that, but will do it if the underlying communication problem is too hard to resolve.

**Comment by binhex** [comment]
> just think this is a genuine issue with the iptables

its not an issue per say, its simply me tightening up the iptables rules, it is very difficult to allow outbound communication from the docker network to your lan without then causing potential ip leakage, this a balancing act between security and functionality, sometimes you have to forego functionality in order to keep things secure.

having said that i THINK i have a way through which might work, but it will take extensive testing to ensure it firstly works and secondly does not introduce any potential ip leakage.

**Comment by jorgenjanssonlee** [comment]
I hear you, and I’m leaning towards just adding nzbget to the VPN network instead of creating lots of extra work for you! So if you want to close this issue that’s fine with me.

Let me know if I can help with testing in case you do go ahead anyway.

**Comment by binhex** [comment]
@jorgenjanssonlee i have a 'test' tagged image built for you to play with, in order to keep this as secure as possible i have had to introduce (yet!) another env var, key is named 'VPN_OUTPUT_PORTS' and the value will be a comma separated list of ports you want to communicate FROM the vpn network to your LAN, so in your case the port number for nzbget.

so please pull down 'test' tagged image and let me know how you get on, if it looks good i can release to the community.

if it doesnt work then please drop to console of the vpn container and run the command 'iptables -S' and then paste the output here.

**Comment by xtacle101** [comment]
I've been following this issue, as I too have seen the same behavior (in addition to Privoxy constantly restarting). I can confirm the 'test' image with the additional variable properly allows communication from with the vpn network, out to LAN addresses.

For the sake of documentation, my use case is adding a "speedtest" container to the VPN network which then writes the results to an InfluxDB database, which is not part of the VPN network. Adding the port for the InfluxDB container allows the "Speedtest" container to successfully connect to the InfluxDB database.  All these containers are on the same unraid host

If the changes made to the 'test' image get merged to a future image, can this same functionality be added to your other VPN images as well? I use a similar workflow to "speedtest" a separate PrivoxyVPN ('arch-privoxyvpn') container as well, which currently suffers the same communication issue.

Thank you for all your hard work in maintaining so many containers. The added security is always welcome and your willingness to add/test this flexibility are certainly appreciated!

**Comment by jorgenjanssonlee** [comment]
> 
> 
> @jorgenjanssonlee i have a 'test' tagged image built for you to play with,
Thanks! Will test this out tonight after work. 
On a side note, my NzbGet download speeds dropped from about 3MB/s to 1MB/s when moving it inside the VPN network, so moving it out again will definitely be a benefit for me at least.

**Comment by binhex** [comment]
> If the changes made to the 'test' image get merged to a future image, can this same functionality be added to your other VPN images as well? I use a similar workflow to "speedtest" a separate PrivoxyVPN ('arch-privoxyvpn') container as well, which currently suffers the same communication issue.

absolutely!, if this tests ok (which it sounds like it will, thanks for the testing) then the change will be included in all my vpn images.

**Comment by jorgenjanssonlee** [comment]
Happy to report that this works flawlessly with NzbGet outside the vpn network for me! Thanks again, download speed is back to normal. :)

Just one clarification, does the outbound iptables take into account both VPN_OUTPUT_PORTS and LAN_NETWORK? So delugevpn can talk to the output ports on any of the defined Lan networks? I have no use case for this, just curious.

If I can, I'll try to help you with the support load of another environment variable, people really seem to struggle with the concepts.

**Comment by binhex** [comment]
> does the outbound iptables take into account both VPN_OUTPUT_PORTS and LAN_NETWORK?

yes, the rule created does use the LAN_NETWORK to define the destination network permitted, otherwise if no destination network was defined then this would allow outbound to any ip on the defined 'VPN_OUTPUT_PORTS'.


> If I can, I'll try to help you with the support load of another environment variable, people really seem to struggle with the concepts.

appreciated!.

**Comment by xtacle101** [comment]
> if this tests ok (which it sounds like it will, thanks for the testing) then the change will be included in all my vpn images.

Thank you! Shortly after posting I saw a 'test' image for the PrivoxyVPN container as well. It too was working as expected by adding the necessary ports to VPN_OUTPUT_PORTS.

After testing various combinations of things and images, using VPN_OUTPUT_PORTS to communicate from the VPN network to the LAN_NETWORK works perfectly. using ADDITIONAL_PORTS to communicate from the LAN_NETWORK to the WebUI of containers inside the VPN network works perfectly. I've also added the "ignore address" to wildcard my LAN network inside the *arr apps. To "connect" Jackett to NZBHydra, i'm using localhost instead of the LAN address.

Inside the VPN network i have sabnzbd, jackett, nzbhydra, speedtest. Outside the VPN network i have the *.arr apps connected to the Privoxy port of the VPN network.

Just let me know if there is any other testing you'd like to see, happy to help. Looks like this is working well, just wait now for merge to 'latest'. again - Thank you for your continued efforts!

**Comment by binhex** [comment]
changes are now in 'latest' for all my vpn images, please pull down and let me know if any issues, if not then please close this issue

**Comment by xtacle101** [comment]
the 'latest' tags are all working for me. Thanks for the quick turnaround!

**Comment by binhex** [comment]
try restarting the speedtest container, if still no go then do a 'iptables -S' from the vpn container and paste it here.

**Comment by xtacle101** [comment]
it was all working the first time i switched to the 'latest' tag, but now toggling back and for from 'test' to 'latest' seems to be producing odd/different results. Now, when I switch to the 'latest' tag, I'm no longer able to communicate between things. it's looking like the iptables aren't being built correctly to include the VPN_OUTPUT_PORTS when using the 'latest' tag. The only change being made is with the "Repository" tag. I'm keeping all other variable consistent between tests.

Is there something else I should clear out from the "appdata" to "refresh"??

Here are the captured reports of the iptables using both the 'latest' and 'test' images:

**binhex/arch-delugevpn:latest**
`-P INPUT DROP`
`-P FORWARD DROP`
`-P OUTPUT DROP`
`-A INPUT -s 172.18.0.0/16 -d 172.18.0.0/16 -j ACCEPT`
`-A INPUT -s 212.##.##.##/32 -i eth0 -j ACCEPT`
`-A INPUT -s 212.##.##.##/32 -i eth0 -j ACCEPT`
`-A INPUT -s 212.##.##.##/32 -i eth0 -j ACCEPT`
`-A INPUT -s 212.##.##.##/32 -i eth0 -j ACCEPT`
`-A INPUT -s 212.##.##.##/32 -i eth0 -j ACCEPT`
`-A INPUT -i eth0 -p tcp -m tcp --dport 8112 -j ACCEPT`
`-A INPUT -i eth0 -p udp -m udp --dport 8112 -j ACCEPT`
`-A INPUT -i eth0 -p tcp -m tcp --dport 8080 -j ACCEPT`
`-A INPUT -i eth0 -p udp -m udp --dport 8080 -j ACCEPT`
`-A INPUT -i eth0 -p tcp -m tcp --dport 8090 -j ACCEPT`
`-A INPUT -i eth0 -p udp -m udp --dport 8090 -j ACCEPT`
`-A INPUT -i eth0 -p tcp -m tcp --dport 9117 -j ACCEPT`
`-A INPUT -i eth0 -p udp -m udp --dport 9117 -j ACCEPT`
`-A INPUT -i eth0 -p tcp -m tcp --dport 5076 -j ACCEPT`
`-A INPUT -i eth0 -p udp -m udp --dport 5076 -j ACCEPT`
`-A INPUT -s 192.168.0.0/24 -i eth0 -p tcp -m tcp --dport 58846 -j ACCEPT`
`-A INPUT -s 192.168.0.0/24 -i eth0 -p tcp -m tcp --dport 8118 -j ACCEPT`
`-A INPUT -p icmp -m icmp --icmp-type 0 -j ACCEPT`
`-A INPUT -i lo -j ACCEPT`
`-A INPUT -i tun0 -j ACCEPT`
`-A OUTPUT -s 172.18.0.0/16 -d 172.18.0.0/16 -j ACCEPT`
`-A OUTPUT -d 212.##.##.##/32 -o eth0 -j ACCEPT`
`-A OUTPUT -d 212.##.##.##/32 -o eth0 -j ACCEPT`
`-A OUTPUT -d 212.##.##.##/32 -o eth0 -j ACCEPT`
`-A OUTPUT -d 212.##.##.##/32 -o eth0 -j ACCEPT`
`-A OUTPUT -d 212.##.##.##/32 -o eth0 -j ACCEPT`
`-A OUTPUT -o eth0 -p tcp -m tcp --sport 8112 -j ACCEPT`
`-A OUTPUT -o eth0 -p udp -m udp --sport 8112 -j ACCEPT`
`-A OUTPUT -o eth0 -p tcp -m tcp --sport 8080 -j ACCEPT`
`-A OUTPUT -o eth0 -p udp -m udp --sport 8080 -j ACCEPT`
`-A OUTPUT -o eth0 -p tcp -m tcp --sport 8090 -j ACCEPT`
`-A OUTPUT -o eth0 -p udp -m udp --sport 8090 -j ACCEPT`
`-A OUTPUT -o eth0 -p tcp -m tcp --sport 9117 -j ACCEPT`
`-A OUTPUT -o eth0 -p udp -m udp --sport 9117 -j ACCEPT`
`-A OUTPUT -o eth0 -p tcp -m tcp --sport 5076 -j ACCEPT`
`-A OUTPUT -o eth0 -p udp -m udp --sport 5076 -j ACCEPT`
`-A OUTPUT -d 192.168.0.0/24 -o eth0 -p tcp -m tcp --sport 58846 -j ACCEPT`
`-A OUTPUT -d 192.168.0.0/24 -o eth0 -p tcp -m tcp --sport 8118 -j ACCEPT`
`-A OUTPUT -p icmp -m icmp --icmp-type 8 -j ACCEPT`
`-A OUTPUT -o lo -j ACCEPT`
`-A OUTPUT -o tun0 -j ACCEPT`

**binhex/arch-delugevpn:test**
`-P INPUT DROP`
`-P FORWARD DROP`
`-P OUTPUT DROP`
`-A INPUT -s 172.18.0.0/16 -d 172.18.0.0/16 -j ACCEPT`
`-A INPUT -s 154.##.##.##/32 -i eth0 -j ACCEPT`
`-A INPUT -s 154.##.##.##/32 -i eth0 -j ACCEPT`
`-A INPUT -s 154.##.##.##/32 -i eth0 -j ACCEPT`
`-A INPUT -s 154.##.##.##/32 -i eth0 -j ACCEPT`
`-A INPUT -s 154.##.##.##/32 -i eth0 -j ACCEPT`
`-A INPUT -i eth0 -p tcp -m tcp --dport 8112 -j ACCEPT`
`-A INPUT -i eth0 -p udp -m udp --dport 8112 -j ACCEPT`
`-A INPUT -i eth0 -p tcp -m tcp --dport 8080 -j ACCEPT`
`-A INPUT -i eth0 -p udp -m udp --dport 8080 -j ACCEPT`
`-A INPUT -i eth0 -p tcp -m tcp --dport 8090 -j ACCEPT`
`-A INPUT -i eth0 -p udp -m udp --dport 8090 -j ACCEPT`
`-A INPUT -i eth0 -p tcp -m tcp --dport 9117 -j ACCEPT`
`-A INPUT -i eth0 -p udp -m udp --dport 9117 -j ACCEPT`
`-A INPUT -i eth0 -p tcp -m tcp --dport 5076 -j ACCEPT`
`-A INPUT -i eth0 -p udp -m udp --dport 5076 -j ACCEPT`
`-A INPUT -s 192.168.0.0/24 -d 172.18.0.0/16 -i eth0 -p tcp -m tcp --dport 58846 -j ACCEPT`
`-A INPUT -s 192.168.0.0/24 -d 172.18.0.0/16 -i eth0 -p tcp -m tcp --dport 8118 -j ACCEPT`
`-A INPUT -s 192.168.0.0/24 -d 172.18.0.0/16 -i eth0 -p tcp -m tcp --sport 8080 -j ACCEPT`
`-A INPUT -s 192.168.0.0/24 -d 172.18.0.0/16 -i eth0 -p tcp -m tcp --sport 8090 -j ACCEPT`
`-A INPUT -s 192.168.0.0/24 -d 172.18.0.0/16 -i eth0 -p tcp -m tcp --sport 9117 -j ACCEPT`
`-A INPUT -s 192.168.0.0/24 -d 172.18.0.0/16 -i eth0 -p tcp -m tcp --sport 5076 -j ACCEPT`
`-A INPUT -s 192.168.0.0/24 -d 172.18.0.0/16 -i eth0 -p tcp -m tcp --sport 8086 -j ACCEPT`
`-A INPUT -s 192.168.0.0/24 -d 172.18.0.0/16 -i eth0 -p tcp -m tcp --sport 8686 -j ACCEPT`
`-A INPUT -p icmp -m icmp --icmp-type 0 -j ACCEPT`
`-A INPUT -i lo -j ACCEPT`
`-A INPUT -i tun0 -j ACCEPT`
`-A OUTPUT -s 172.18.0.0/16 -d 172.18.0.0/16 -j ACCEPT`
`-A OUTPUT -d 154.##.##.##/32 -o eth0 -j ACCEPT`
`-A OUTPUT -d 154.##.##.##/32 -o eth0 -j ACCEPT`
`-A OUTPUT -d 154.##.##.##/32 -o eth0 -j ACCEPT`
`-A OUTPUT -d 154.##.##.##/32 -o eth0 -j ACCEPT`
`-A OUTPUT -d 154.##.##.##/32 -o eth0 -j ACCEPT`
`-A OUTPUT -o eth0 -p tcp -m tcp --sport 8112 -j ACCEPT`
`-A OUTPUT -o eth0 -p udp -m udp --sport 8112 -j ACCEPT`
`-A OUTPUT -o eth0 -p tcp -m tcp --sport 8080 -j ACCEPT`
`-A OUTPUT -o eth0 -p udp -m udp --sport 8080 -j ACCEPT`
`-A OUTPUT -o eth0 -p tcp -m tcp --sport 8090 -j ACCEPT`
`-A OUTPUT -o eth0 -p udp -m udp --sport 8090 -j ACCEPT`
`-A OUTPUT -o eth0 -p tcp -m tcp --sport 9117 -j ACCEPT`
`-A OUTPUT -o eth0 -p udp -m udp --sport 9117 -j ACCEPT`
`-A OUTPUT -o eth0 -p tcp -m tcp --sport 5076 -j ACCEPT`
`-A OUTPUT -o eth0 -p udp -m udp --sport 5076 -j ACCEPT`
`-A OUTPUT -s 172.18.0.0/16 -d 192.168.0.0/24 -o eth0 -p tcp -m tcp --sport 58846 -j ACCEPT`
`-A OUTPUT -s 172.18.0.0/16 -d 192.168.0.0/24 -o eth0 -p tcp -m tcp --sport 8118 -j ACCEPT`
`-A OUTPUT -s 172.18.0.0/16 -d 192.168.0.0/24 -o eth0 -p tcp -m tcp --dport 8080 -j ACCEPT`
`-A OUTPUT -s 172.18.0.0/16 -d 192.168.0.0/24 -o eth0 -p tcp -m tcp --dport 8090 -j ACCEPT`
`-A OUTPUT -s 172.18.0.0/16 -d 192.168.0.0/24 -o eth0 -p tcp -m tcp --dport 9117 -j ACCEPT`
`-A OUTPUT -s 172.18.0.0/16 -d 192.168.0.0/24 -o eth0 -p tcp -m tcp --dport 5076 -j ACCEPT`
`-A OUTPUT -s 172.18.0.0/16 -d 192.168.0.0/24 -o eth0 -p tcp -m tcp --dport 8086 -j ACCEPT`
`-A OUTPUT -s 172.18.0.0/16 -d 192.168.0.0/24 -o eth0 -p tcp -m tcp --dport 8686 -j ACCEPT`
`-A OUTPUT -p icmp -m icmp --icmp-type 8 -j ACCEPT`
`-A OUTPUT -o lo -j ACCEPT`
`-A OUTPUT -o tun0 -j ACCEPT`

**Comment by binhex** [comment]
ok binhex/arch-delugevpn:latest looks to be not up to date, when switching tag make sure you 'force update; otherwise you will be switching back to the older docker image, you need to force it to pull down the new image.

**Comment by xtacle101** [comment]
> when switching tag make sure you 'force update; otherwise you will be switching back to the older docker image, you need to force it to pull down the new image.

spot on. i came to the same conclusion before coming back and seeing your response. In looking through the supervisord.log, I could see it wasn't using the VPN_OUTPUT_PORTS. i switched to the '2.0.4.dev38-g23a48dd01-3-04' image and watched unraid pulldown the pieces and it clicked. When switching back to the 'latest' image I noticed it wasn't "fetching" anything, but just switching to an older version. After switching to 'latest' and a forced update, it's reading VPN_OUTPUT_PORTS and building tables as expected. Everything is once again working, including the "speedtest" container's communication with the LAN.

thanks!

**Comment by jorgenjanssonlee** [comment]
So sorry, but I'm having a heck of a time trying to get the :latest image to work. It was all working fine on :test, but with :latest I'm getting DNS failures. I can actually access the DelugeVPN web UI, but Jackett, Sonarr and Radarr are having issues connecting. Both curl ifconfig.io and nslookup google.com fails or times out from the deluge console:
```
sh-5.1# curl ifconfig.io
curl: (6) Could not resolve host: ifconfig.io
sh-5.1# 
sh-5.1# nslookup google.com
;; connection timed out; no servers could be reached


sh-5.1# cat /etc/resolv.conf 
nameserver 84.200.69.80
nameserver 37.235.1.174
nameserver 1.1.1.1
nameserver 37.235.1.177
nameserver 84.200.70.40
nameserver 1.0.0.1
sh-5.1# 
```
I don't know if this is coincidental or a change between :latest and :test?

I've tried check/force update as well as remove (with image) and reinstall several times, but this happens everytime.

Fresh pull of :latest seems to be ok:
![Screen Shot 2021-03-04 at 9 13 57 am](https://user-images.githubusercontent.com/28835885/109880896-954d2b80-7ccb-11eb-8a0d-b242b7f8ddcf.png)

supervisord.log attached
[supervisord.log](https://github.com/binhex/arch-delugevpn/files/6079565/supervisord.log)

I will try rolling back to :test to see if that's having the same issue now.

**Comment by jorgenjanssonlee** [comment]
> I will try rolling back to :test to see if that's having the same issue now.

Ok, the :test image works perfectly after roll back, no DNS failures. Is there something else I can try to get the :latest to work?

On a related note, would it be possible to add the repository tag/image id to the supervisord.log on startup? Would be useful for troubleshooting.

**Comment by binhex** [comment]
> Ok, the :test image works perfectly after roll back, no DNS failures. Is there something else I can try to get the :latest to work?

ughh! looks like its my wireguard network change, it seems to intermittently cause dns failure, im reverting that change now and rebuild the images, try a pull in about 30 mins from now.

**Comment by jorgenjanssonlee** [comment]
Thanks, latest works well now! Will close this issue, thanks again for all your work keeping us safe and secure.
