### ISSUE TITLE
Python 3.9 over 3.8

### ISSUE THREAD

**Issue by DrSeussFreak** [binhex/arch-delugevpn#262]
I use the WebAPI-0.4.0-py3.8.egg plugin (also available for Python 3.6 and 3.7), and I see that the python version for this container is 3.9.  Any chance python could be pushed back from 3.9 to 3.8 (or 3.6 or 3.7)?

**Comment by Devo-McDuff** [comment]
I had a similar problem with AutoRemovePlus, I read that renaming the 3.8 to 3.9 at the end of the egg name should work and it did, you could try the same with your plugin

**Comment by DrSeussFreak** [comment]
I will try that, thanks!
