### ISSUE TITLE
New router - container won't start

### ISSUE THREAD

**Issue by SnowDrifterr** [binhex/arch-delugevpn#265]
Running in a docker container on synology

Getting the error: 
Start container delugevpn failed: {"message":"driver failed programming external connectivity on endpoint delugevpn (1dbdc0fe764a3676329239f4047ebb1052db9d8671cd76074ed3ab5bd9a41343): Bind for 0.0.0.0:58946 failed: port is already allocated"}.

Settings:
![image](https://user-images.githubusercontent.com/57574629/111092071-3d47cd80-84f2-11eb-8dde-4c7d1fed44c1.png)
![image](https://user-images.githubusercontent.com/57574629/111092115-5a7c9c00-84f2-11eb-8d29-c2e34bf5876e.png)

**Comment by binhex** [comment]
`failed: port is already allocated"}`

the port you have set on the host side is already in use by something else, you need to either change the port for this container (host side ONLY), or change the port for whatever is currently using it.

**Comment by SnowDrifterr** [comment]
I think I found a bug in docker itself.

Found that restarting the entire docker process fixed it - looks like it wasn't releasing port bindings for some reason. Will see if I can report over there of my findings
