### ISSUE TITLE
Deprecated cert

### ISSUE THREAD

**Issue by jvlarc** [binhex/arch-delugevpn#269]
Having some issue with DelugeVPN docker, I'm using ExpressVPN and has been working fine the past few months, and this seems to not allow me to open up the WebUI page. Only when I disable VPN then does the docker WebUI work.

>  2021-04-01 15:07:14,274 DEBG 'start-script' stdout output:
> 2021-04-01 15:07:14 DEPRECATED OPTION: --cipher set to 'AES-256-CBC' but missing in --data-ciphers (AES-256-GCM:AES-128-GCM). Future OpenVPN version will ignore --cipher for cipher negotiations. Add 'AES-256-CBC' to --data-ciphers or change --cipher 'AES-256-CBC' to --data-ciphers-fallback 'AES-256-CBC' to silence this warning.
> 
> 
> 2021-04-01 15:07:14,275 DEBG 'start-script' stdout output:
> 2021-04-01 15:07:14 WARNING: --keysize is DEPRECATED and will be removed in OpenVPN 2.6
> 
> 2021-04-01 15:07:14 WARNING: --keysize is DEPRECATED and will be removed in OpenVPN 2.6
> 
> 2021-04-01 15:07:14 WARNING: --keysize is DEPRECATED and will be removed in OpenVPN 2.6
> 
> 2021-04-01 15:07:14 WARNING: file 'credentials.conf' is group or others accessible
> 
> 2021-04-01 15:07:14 OpenVPN 2.5.1 [git:makepkg/f186691b32e68362+] x86_64-pc-linux-gnu [SSL (OpenSSL)] [LZO] [LZ4] [EPOLL] [PKCS11] [MH/PKTINFO] [AEAD] built on Feb 24 2021
> 2021-04-01 15:07:14 library versions: OpenSSL 1.1.1j 16 Feb 2021, LZO 2.10
> 
> 2021-04-01 15:07:14,275 DEBG 'start-script' stdout output:
> 2021-04-01 15:07:14 WARNING: --ns-cert-type is DEPRECATED. Use --remote-cert-tls instead.

**Comment by binhex** [comment]
Thats not a deprecated cert, that is informing you about deprecated openvpn options that are specified (currently required for PIA), i suspect this is not the issue, please do the following:- https://github.com/binhex/documentation/blob/master/docker/faq/help.md
