### ISSUE TITLE
Not starting

### ISSUE THREAD

**Issue by rourke** [binhex/arch-delugevpn#27]
I'm trying to get this started, but I'm getting many errors. I'm running the following `docker-compose.yml` file:

```
version: "3"
services:

  deluge:
    image: binhex/arch-delugevpn
    container_name: deluge
    restart: on-failure
    cap_add:
      - NET_ADMIN
    ports:
      - "8112:8112"
      - "8118:8118"
      - "58846:58846"
      - "58946:58946"
    networks:
      - plexnet
    environment:
      - PUID=1001
      - PGID=1001
      - VPN_ENABLED=yes
      - VPN_USER=mask_username
      - VPN_PASS=mask_password
      - VPN_REMOTE=france.privateinternetaccess.com
      - VPN_PORT=1198
      - VPN_PROTOCOL=udp
      - VPN_DEVICE_TYPE=tun
      - VPN_PROV=pia
      - STRONG_CERTS=no
      - ENABLE_PRIVOXY=yes
      - LAN_NETWORK=61.183.79.118/32
      - NAME_SERVERS=8.8.8.8,8.8.4.4
      - DEBUG=false
      - UMASK=000
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /home/tomato/.config/Deluge:/config
      - /home/tomato/downloads:/data

networks:
  plexnet:
    driver: bridge
```

And these are the log files I'm getting: https://pastebin.com/kyPMJdCU

Honestly I have no idea where to start with this, so I'm hoping to get some help here.

**Edit:** these are the logs with `DEBUG` set to `true`: https://pastebin.com/eYeJSF6J

**Comment by rourke** [comment]
I wanted to try _something_ so I decided to analyze the logs line by line and see what wasn't right. Line 266 is the first one out of order:

    [warn] 'tun' module not available, you will not be able to connect to Deluge or Privoxy outside of your LAN

I'm not sure if this is meant to be for the scope of the container, or the system itself. From what I've read there should be a `tun0` device? There is none if I do `ifconfig`, but when I access the shell of the container there is one:

```
tun0: flags=4305<UP,POINTOPOINT,RUNNING,NOARP,MULTICAST>  mtu 1500
        inet 10.60.10.6  netmask 255.255.255.255  destination 10.60.10.5
        unspec 00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00  txqueuelen 100  (UNSPEC)
        RX packets 12  bytes 955 (955.0 B)
        RX errors 0  dropped 0  overruns 0  frame 0
        TX packets 18  bytes 1182 (1.1 KiB)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0
```

So not sure what the error is referring to or if this has anything to do with delugevpn itself, but I'd appriciate if someone could point me in the right direction.

**Comment by hannah98** [comment]
Experiencing this issue as well

**Comment by binhex** [comment]
OK firstly you have permissions issues, please check the user and group your running the container as (can be defined via PUID and PGID, as it currently does not have write access, taken from your logs:-

```
cp: cannot create regular file '/config/privoxy/user.action': Permission denied
```
