### ISSUE TITLE
Memory Leak?

### ISSUE THREAD

**Issue by shakyr** [binhex/arch-delugevpn#283]
I'm running the docker on a QNAP NAS and I keep needing to login every few days and check the memory usage, as it'll spike in cached memory from ~100MB to 1GB.

It used to go higher than 1GB, but I've put in place memory limits with my docker run command. Otherwise the NAS would automatically kill it when the container started using too much memory (I have 8GB RAM, normally the machine barely uses 2GB).

Most of the time deluge just has uploads (currently ~200GB) active and seeding.

I'm using PIA, with port forwarding and Privoxy disabled.

**Comment by binhex** [comment]
you would need to contact deluge dev's for this, keep in mind i do not develop deluge, simply package, try here:- https://forum.deluge-torrent.org/
