### ISSUE TITLE
Is /data volume hardcoded somewhere?

### ISSUE THREAD

**Issue by goku-son** [binhex/arch-delugevpn#288]
Hi, I am using binhex/arch-delugevpn image with the following volumes:

 volumes:
      - ./deluge:/config
      - downloads:/downloads

The Deluge GUI  is using /downloads/incomplete and /downloads/complete. Everything works as it should and it has and continues to run fine with no issues. However, I noticed that it also creates an additional volume mapped to /data, even though it is not used. How can I get by set up such that it does not create the /data volume at all? Whenever I recreate the container, it releases the previous data volume, and creates a new one, causing orphaned volumes. I just don't want /data created since I am using /downloads and would like to keep that name and get rid of /data. Thanks in advance for any guidance.

**Comment by binhex** [comment]
this WAS hard coded into the Dockerfile, however there was a request to remove this for the above reason you just detailed, so the next build of the image will have /data removed.

**Comment by goku-son** [comment]
Thank you!
