### ISSUE TITLE
/home/nobody/vpn_incoming_port.txt: Permission denied

### ISSUE THREAD

**Issue by hotio** [binhex/arch-delugevpn#29]
When using the umask `077 	600 (rw-------)` the file `/home/nobody/vpn_incoming_port.txt` is not readable (obviously) which results in deluge being improperly configured...

**Comment by ErroneousBosch** [comment]
Having an issue where this file doesn't seem to even be created. When I console in, it doesn't exist. VPN appears to be connected fine (getting an address). OpenVPN appears to also be stuck in a restart loop. Debug log:

`2017-07-02 22:25:28.682935 [info] Starting Supervisor...
2017-07-02 22:25:29,233 CRIT Set uid to user 0
2017-07-02 22:25:29,234 INFO Included extra file "/etc/supervisor/conf.d/delugevpn.conf" during parsing
2017-07-02 22:25:29,238 INFO supervisord started with pid 7
2017-07-02 22:25:30,243 INFO spawned: 'start-script' with pid 119
2017-07-02 22:25:30,248 INFO spawned: 'deluge-script' with pid 120
2017-07-02 22:25:30,251 INFO spawned: 'deluge-web-script' with pid 121
2017-07-02 22:25:30,254 INFO spawned: 'privoxy-script' with pid 122
2017-07-02 22:25:30,269 DEBG 'deluge-script' stdout output:
[info] Deluge config file already exists, skipping copy

2017-07-02 22:25:30,269 INFO success: start-script entered RUNNING state, process has stayed up for > than 0 seconds (startsecs)
2017-07-02 22:25:30,270 INFO success: deluge-script entered RUNNING state, process has stayed up for > than 0 seconds (startsecs)
2017-07-02 22:25:30,270 INFO success: deluge-web-script entered RUNNING state, process has stayed up for > than 0 seconds (startsecs)
2017-07-02 22:25:30,270 INFO success: privoxy-script entered RUNNING state, process has stayed up for > than 0 seconds (startsecs)
2017-07-02 22:25:30,270 DEBG 'deluge-script' stdout output:
[info] VPN is enabled, checking VPN tunnel local ip is valid
[debug] Waiting for valid IP address from tunnel...

2017-07-02 22:25:30,271 DEBG 'start-script' stdout output:
[info] VPN is enabled, beginning configuration of VPN

2017-07-02 22:25:30,272 DEBG 'privoxy-script' stdout output:
[debug] Waiting for valid IP address from tunnel...

2017-07-02 22:25:30,292 DEBG 'start-script' stdout output:
[info] VPN default certs defined, copying to /config/openvpn/...

2017-07-02 22:25:30,298 DEBG 'start-script' stdout output:
[debug] Environment variables defined as follows
BASH=/bin/bash
BASHOPTS=cmdhist:complete_fullquote:extquote:force_fignore:hostcomplete:interactive_comments:progcomp:promptvars:sourcepath
BASH_ALIASES=()
BASH_ARGC=()
BASH_ARGV=()
BASH_CMDS=()
BASH_LINENO=([0]="0")

2017-07-02 22:25:30,299 DEBG 'start-script' stdout output:
BASH_SOURCE=([0]="/root/start.sh")
BASH_VERSINFO=([0]="4" [1]="4" [2]="12" [3]="1" [4]="release" [5]="x86_64-unknown-linux-gnu")
BASH_VERSION='4.4.12(1)-release'
DEBUG=true
DIRSTACK=()
ENABLE_PRIVOXY=yes
EUID=0
GROUPS=()
HOME=/home/nobody
HOSTNAME=7d130e1420ca
HOSTTYPE=x86_64
IFS=$' \t\n'
LANG=en_GB.UTF-8
LAN_NETWORK=13.13.13.0/24
MACHTYPE=x86_64-unknown-linux-gnu
NAME_SERVERS=8.8.8.8,8.8.4.4
OPTERR=1
OPTIND=1
OSTYPE=linux-gnu
PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
PGID=1000
PIPESTATUS=([0]="0")
PPID=7
PS4='+ '
PUID=1000
PWD=/
SHELL=/bin/bash
SHELLOPTS=braceexpand:hashall:interactive-comments
SHLVL=1
STRICT_PORT_FORWARD=yes
STRONG_CERTS=no
SUPERVISOR_ENABLED=1
SUPERVISOR_GROUP_NAME=start-script
SUPERVISOR_PROCESS_NAME=start-script
TERM=xterm
UID=0
VPN_CONFIG=/config/openvpn/openvpn.ovpn
VPN_DEVICE_TYPE=tun
VPN_ENABLED=yes
VPN_OPTIONS=
VPN_PASS=XXXXXX
VPN_PORT=1198
VPN_PROTOCOL=udp
VPN_PROV=pia
VPN_REMOTE=us-east.privateinternetaccess.com
VPN_USER=XXXXXXX
_='[debug] Environment variables defined as follows'
exit_code_chmod=0
exit_code_chown=0
[debug] Directory listing of files in /config/openvpn as follows

2017-07-02 22:25:30,306 DEBG 'start-script' stdout output:
total 56
drwxrwxrwx 2 nobody users 4096 Jul  2 21:58 .
drwxrwxr-x 9 nobody users 4096 Jun 30 11:07 ..
-rwxrwxrwx 1 nobody users 2025 Jul  2 22:25 ca.rsa.2048.crt
-rwxrwxrwx 1 nobody users   22 Jul  2 21:58 credentials.conf
-rwxrwxrwx 1 nobody users  869 Jul  2 22:25 crl.rsa.2048.pem
-rwxrwxrwx 1 nobody users  272 Jul  2 22:25 openvpn.ovpn

2017-07-02 22:25:30,306 DEBG 'start-script' stdout output:
[info] VPN config file (ovpn extension) is located at /config/openvpn/openvpn.ovpn

2017-07-02 22:25:30,308 DEBG 'start-script' stderr output:
dos2unix: converting file /config/openvpn/openvpn.ovpn to Unix format...

2017-07-02 22:25:30,403 DEBG 'start-script' stdout output:
[debug] Contents of ovpn file /config/openvpn/openvpn.ovpn as follows...

2017-07-02 22:25:30,409 DEBG 'start-script' stdout output:
client
dev tun
proto udp
remote us-east.privateinternetaccess.com 1198
resolv-retry infinite
nobind
persist-key
cipher aes-128-cbc
auth sha1
tls-client
remote-cert-tls server
auth-user-pass credentials.conf
comp-lzo
verb 1
crl-verify crl.rsa.2048.pem
ca ca.rsa.2048.crt
disable-occ

2017-07-02 22:25:30,419 DEBG 'start-script' stdout output:
[info] Default route for container is 172.17.0.1

2017-07-02 22:25:30,425 DEBG 'start-script' stdout output:
[info] Adding 8.8.8.8 to /etc/resolv.conf

2017-07-02 22:25:30,431 DEBG 'start-script' stdout output:
[info] Adding 8.8.4.4 to /etc/resolv.conf
[debug] Show name servers defined for container

2017-07-02 22:25:30,432 DEBG 'start-script' stdout output:
nameserver 8.8.8.8
nameserver 8.8.4.4

2017-07-02 22:25:30,433 DEBG 'start-script' stdout output:
[debug] Show name resolution for VPN endpoint us-east.privateinternetaccess.com

2017-07-02 22:25:30,472 DEBG 'start-script' stdout output:
;; ->>HEADER<<- opcode: QUERY, rcode: NOERROR, id: 53810
;; flags: qr rd ra ; QUERY: 1, ANSWER: 13, AUTHORITY: 0, ADDITIONAL: 0
;; QUESTION SECTION:
;; us-east.privateinternetaccess.com.   IN      A

;; ANSWER SECTION:
us-east.privateinternetaccess.com.      128     IN      A       108.61.55.67
us-east.privateinternetaccess.com.      128     IN      A       108.61.57.218
us-east.privateinternetaccess.com.      128     IN      A       66.55.141.100
us-east.privateinternetaccess.com.      128     IN      A       107.191.33.9
us-east.privateinternetaccess.com.      128     IN      A       208.167.254.112
us-east.privateinternetaccess.com.      128     IN      A       108.61.68.165
us-east.privateinternetaccess.com.      128     IN      A       108.61.68.156
us-east.privateinternetaccess.com.      128     IN      A       173.199.127.214
us-east.privateinternetaccess.com.      128     IN      A       209.222.5.233
us-east.privateinternetaccess.com.      128     IN      A       108.61.76.6
us-east.privateinternetaccess.com.      128     IN      A       108.61.57.213
us-east.privateinternetaccess.com.      128     IN      A       209.222.5.229
us-east.privateinternetaccess.com.      128     IN      A       66.55.141.84

;; AUTHORITY SECTION:

;; ADDITIONAL SECTION:

;; Query time: 33 msec
;; SERVER: 8.8.8.8
;; WHEN: Sun Jul  2 22:25:30 2017
;; MSG SIZE  rcvd: 259

2017-07-02 22:25:30,492 DEBG 'start-script' stdout output:
[info] Adding 13.13.13.0/24 as route via docker eth0

2017-07-02 22:25:30,494 DEBG 'start-script' stdout output:
[info] ip route defined as follows...
--------------------

2017-07-02 22:25:30,496 DEBG 'start-script' stdout output:
default via 172.17.0.1 dev eth0
13.13.13.0/24 via 172.17.0.1 dev eth0
172.17.0.0/16 dev eth0 proto kernel scope link src 172.17.0.7

2017-07-02 22:25:30,497 DEBG 'start-script' stdout output:
--------------------
[debug] Modules currently loaded for kernel

2017-07-02 22:25:30,503 DEBG 'start-script' stdout output:
Module                  Size  Used by
nf_conntrack_netlink    40960  0
nfnetlink              16384  2 nf_conntrack_netlink
ufs                    73728  0
qnx4                   16384  0
hfsplus               106496  0
hfs                    57344  0
minix                  36864  0
ntfs                   98304  0
msdos                  20480  0
jfs                   180224  0
xfs                   970752  0
veth                   16384  0
xt_nat                 16384  11
xt_tcpudp              16384  33
ipt_MASQUERADE         16384  13
nf_nat_masquerade_ipv4    16384  1 ipt_MASQUERADE
xfrm_user              32768  1
xfrm_algo              16384  1 xfrm_user
iptable_nat            16384  1
nf_conntrack_ipv4      16384  3
nf_defrag_ipv4         16384  1 nf_conntrack_ipv4
nf_nat_ipv4            16384  1 iptable_nat
xt_addrtype            16384  2
iptable_filter         16384  1
ip_tables              24576  2 iptable_filter,iptable_nat
xt_conntrack           16384  2
x_tables               36864  7 ip_tables,xt_tcpudp,ipt_MASQUERADE,xt_conntrack,xt_nat,iptable_filter,xt_addrtype
nf_nat                 24576  3 nf_nat_ipv4,xt_nat,nf_nat_masquerade_ipv4
nf_conntrack          106496  6 nf_nat,nf_nat_ipv4,xt_conntrack,nf_nat_masquerade_ipv4,nf_conntrack_netlink,nf_conntrack_ipv4
br_netfilter           24576  0
bridge                126976  1 br_netfilter
stp                    16384  1 bridge
llc                    16384  2 stp,bridge
aufs                  217088  769
drbg                   32768  1
ansi_cprng             16384  0
xts                    16384  1
gf128mul               16384  1 xts
dm_crypt               28672  1
ppdev                  20480  0
kvm                   544768  0
snd_hda_codec_via      24576  1
snd_hda_codec_hdmi     53248  1
snd_hda_codec_generic    77824  1 snd_hda_codec_via
irqbypass              16384  1 kvm
snd_hda_intel          40960  0
input_leds             16384  0
edac_mce_amd           24576  0
serio_raw              16384  0
k10temp                16384  0
snd_hda_codec         135168  4 snd_hda_codec_hdmi,snd_hda_codec_via,snd_hda_codec_generic,snd_hda_intel
edac_core              53248  0
snd_hda_core           73728  5 snd_hda_codec_hdmi,snd_hda_codec_via,snd_hda_codec_generic,snd_hda_codec,snd_hda_intel
i2c_piix4              24576  0
snd_hwdep              16384  1 snd_hda_codec
snd_pcm               106496  4 snd_hda_codec_hdmi,snd_hda_codec,snd_hda_intel,snd_hda_core
snd_timer              32768  1 snd_pcm
snd                    81920  8 snd_hwdep,snd_timer,snd_hda_codec_hdmi,snd_hda_codec_via,snd_pcm,snd_hda_codec_generic,snd_hda_codec,snd_hda_intel
soundcore              16384  1 snd
parport_pc             32768  0
8250_fintek            16384  0
mac_hid                16384  0
asus_atk0110           20480  0
parport                49152  2 ppdev,parport_pc
shpchp                 36864  0
ib_iser                49152  0
rdma_cm                49152  1 ib_iser
iw_cm                  45056  1 rdma_cm
ib_cm                  45056  1 rdma_cm
ib_sa                  36864  2 rdma_cm,ib_cm
ib_mad                 49152  2 ib_cm,ib_sa
ib_core               106496  6 rdma_cm,ib_cm,ib_sa,iw_cm,ib_mad,ib_iser
ib_addr                20480  2 rdma_cm,ib_core
iscsi_tcp              20480  0
libiscsi_tcp           24576  1 iscsi_tcp
libiscsi               53248  3 libiscsi_tcp,iscsi_tcp,ib_iser
scsi_transport_iscsi    98304  4 iscsi_tcp,ib_iser,libiscsi
autofs4                40960  2
btrfs                 987136  0
raid10                 49152  0
raid456               110592  0
async_raid6_recov      20480  1 raid456
async_memcpy           16384  2 raid456,async_raid6_recov
async_pq               16384  2 raid456,async_raid6_recov
async_xor              16384  3 async_pq,raid456,async_raid6_recov
async_tx               16384  5 async_pq,raid456,async_xor,async_memcpy,async_raid6_recov
xor                    24576  2 btrfs,async_xor
raid6_pq              102400  4 async_pq,raid456,btrfs,async_raid6_recov
libcrc32c              16384  2 xfs,raid456
raid1                  36864  0
raid0
2017-07-02 22:25:30,504 DEBG 'start-script' stdout output:
          20480  0
multipath              16384  0
linear                 16384  0
pata_acpi              16384  0
amdkfd                131072  1
amd_iommu_v2           20480  1 amdkfd
radeon               1515520  1
i2c_algo_bit           16384  1 radeon
ttm                    94208  1 radeon
drm_kms_helper        155648  1 radeon
syscopyarea            16384  1 drm_kms_helper
sysfillrect            16384  1 drm_kms_helper
uas                    24576  0
sysimgblt              16384  1 drm_kms_helper
fb_sys_fops            16384  1 drm_kms_helper
ahci                   36864  4
pata_atiixp            16384  1
usb_storage            69632  1 uas
libahci                32768  1 ahci
r8169                  81920  0
drm                   364544  4 ttm,drm_kms_helper,radeon
mii                    16384  1 r8169
wmi                    20480  0
fjes                   28672  0

2017-07-02 22:25:30,513 DEBG 'start-script' stdout output:
[warn] 'iptable_mangle' kernel module not available, you will not be able to connect to the applications Web UI or Privoxy outside of your LAN
[info] unRAID users: Please attempt to load the module by executing the following on your host:- '/sbin/modprobe iptable_mangle'
[info] Ubuntu users: Please attempt to load the module by executing the following on your host:- '/sbin/modprobe iptable_mangle'

2017-07-02 22:25:30,514 DEBG 'start-script' stdout output:
[info] Synology users: Please attempt to load the module by executing the following on your host:- 'insmod /lib/modules/iptable_mangle.ko'

2017-07-02 22:25:30,523 DEBG 'start-script' stdout output:
[debug] Docker interface defined as eth0

2017-07-02 22:25:30,533 DEBG 'start-script' stdout output:
[debug] Docker IP defined as 172.17.0.7

2017-07-02 22:25:30,540 DEBG 'start-script' stdout output:
[debug] Docker netmask defined as 255.255.0.0

2017-07-02 22:25:30,551 DEBG 'start-script' stdout output:
[info] Docker network defined as    172.17.0.0/16

2017-07-02 22:25:30,689 DEBG 'start-script' stdout output:
[info] iptables defined as follows...
--------------------

2017-07-02 22:25:30,693 DEBG 'start-script' stdout output:
-P INPUT DROP
-P FORWARD ACCEPT
-P OUTPUT DROP
-A INPUT -i tun0 -j ACCEPT
-A INPUT -s 172.17.0.0/16 -d 172.17.0.0/16 -j ACCEPT
-A INPUT -i eth0 -p udp -m udp --sport 1198 -j ACCEPT
-A INPUT -i eth0 -p tcp -m tcp --dport 8112 -j ACCEPT
-A INPUT -i eth0 -p tcp -m tcp --sport 8112 -j ACCEPT
-A INPUT -s 13.13.13.0/24 -i eth0 -p tcp -m tcp --dport 58846 -j ACCEPT
-A INPUT -s 13.13.13.0/24 -d 172.17.0.0/16 -i eth0 -p tcp -j ACCEPT
-A INPUT -p udp -m udp --sport 53 -j ACCEPT
-A INPUT -p icmp -m icmp --icmp-type 0 -j ACCEPT
-A INPUT -i lo -j ACCEPT
-A OUTPUT -o tun0 -j ACCEPT
-A OUTPUT -s 172.17.0.0/16 -d 172.17.0.0/16 -j ACCEPT
-A OUTPUT -o eth0 -p udp -m udp --dport 1198 -j ACCEPT
-A OUTPUT -o eth0 -p tcp -m tcp --dport 8112 -j ACCEPT
-A OUTPUT -o eth0 -p tcp -m tcp --sport 8112 -j ACCEPT
-A OUTPUT -d 13.13.13.0/24 -o eth0 -p tcp -m tcp --sport 58846 -j ACCEPT
-A OUTPUT -s 172.17.0.0/16 -d 13.13.13.0/24 -o eth0 -p tcp -j ACCEPT
-A OUTPUT -p udp -m udp --dport 53 -j ACCEPT
-A OUTPUT -p icmp -m icmp --icmp-type 8 -j ACCEPT
-A OUTPUT -o lo -j ACCEPT

2017-07-02 22:25:30,694 DEBG 'start-script' stdout output:
--------------------

2017-07-02 22:25:30,694 DEBG 'start-script' stdout output:
[debug] OpenVPN command line '/usr/bin/openvpn --cd /config/openvpn --config /config/openvpn/openvpn.ovpn --daemon --dev tun0 --remote us-east.privateinternetaccess.com 1198 --proto udp --reneg-sec 0 --mute-replay-warnings --auth-nocache --keepalive 10 60 --setenv VPN_PROV pia --setenv DEBUG true --script-security 2 --up /root/openvpnup.sh --up-delay --up-restart --writepid /root/openvpn.pid --setenv STRICT_PORT_FORWARD yes --auth-user-pass credentials.conf --disable-occ --remap-usr1 SIGHUP --log-append /config/supervisord.log --auth-user-pass credentials.conf'

2017-07-02 22:25:30,695 DEBG 'start-script' stdout output:
[info] Starting OpenVPN...

2017-07-02 22:25:30,707 DEBG 'start-script' stdout output:
[info] OpenVPN started
[debug] Waiting for valid IP address from tunnel...

2017-07-02 22:25:32,554 DEBG 'start-script' stdout output:
[debug] Valid IP address from tunnel acquired '10.40.10.6'

2017-07-02 22:25:32,605 DEBG 'privoxy-script' stdout output:
[debug] Valid IP address from tunnel acquired '10.40.10.6'
[info] Configuring Privoxy...

2017-07-02 22:25:32,606 DEBG 'deluge-script' stdout output:
[debug] Valid IP address from tunnel acquired '10.40.10.6'

2017-07-02 22:25:32,613 DEBG 'deluge-script' stdout output:
[info] Deluge not running
[info] Deluge listening interface IP 0.0.0.0 and VPN provider IP 10.40.10.6 different, marking for reconfigure

2017-07-02 22:25:32,614 DEBG 'deluge-script' stdout output:
[debug] Waiting for file '/home/nobody/vpn_incoming_port.txt' to be generated (contains PIA API generated incoming port number)...

2017-07-02 22:25:32,839 DEBG 'privoxy-script' stdout output:
[info] All checks complete, starting Privoxy...

2017-07-02 22:25:32,843 DEBG 'privoxy-script' stderr output:
2017-07-02 22:25:32.842 7f5ae0657040 Info: Privoxy version 3.0.26
2017-07-02 22:25:32.842 7f5ae0657040 Info: Program name: /usr/bin/privoxy

2017-07-02 22:28:02,638 DEBG 'start-script' stdout output:
[warn] OpenVPN process terminated, restarting OpenVPN...

2017-07-02 22:28:02,653 DEBG 'start-script' stdout output:
[info] OpenVPN restarted

2017-07-02 22:30:32,721 DEBG 'start-script' stdout output:
[warn] OpenVPN process terminated, restarting OpenVPN...

2017-07-02 22:30:32,734 DEBG 'start-script' stdout output:
[info] OpenVPN restarted

vpn_incoming_port.txt'2017-07-02 22:33:02,796 DEBG 'start-script' stdout output:
[warn] OpenVPN process terminated, restarting OpenVPN...

2017-07-02 22:33:02,807 DEBG 'start-script' stdout output:
[info] OpenVPN restarted

2017-07-02 22:35:32,858 DEBG 'start-script' stdout output:
[warn] OpenVPN process terminated, restarting OpenVPN...

2017-07-02 22:35:32,872 DEBG 'start-script' stdout output:
[info] OpenVPN restarted

2017-07-02 22:38:02,940 DEBG 'start-script' stdout output:
[warn] OpenVPN process terminated, restarting OpenVPN...

2017-07-02 22:38:02,955 DEBG 'start-script' stdout output:
[info] OpenVPN restarted
`

**Comment by binhex** [comment]
> When using the umask 077 600 (rw-------) the file /home/nobody/vpn_incoming_port.txt is not readable (obviously) which results in deluge being improperly configured...

well, don't set the umask to 077 then (leave it on defaults 000), not sure what you want me to do about setting the umask incorrectly?.

**Comment by binhex** [comment]
@ErroneousBosch your issue is not related to umask, its this:- [https://github.com/binhex/arch-delugevpn/issues/28#issuecomment-312433718](url)

**Comment by ErroneousBosch** [comment]
Thanks for the response. I didn't see the other issue.

**Comment by hotio** [comment]
Wasn't the umask command supposed to be used to set the permissions of the config files and downloaded torrent files? Well if the umask of 077 can have such an impact on the startup of the container, something needs fixing...

You are creating the file as root using the umask, obviously the user `nobody` will not be able to read that file.

You could perhaps set explicit permissions for the files that need those...

**Comment by binhex** [comment]
Sure i can set permissions explicitly, the reason it currently doesn't do that is i wasn't expecting people to set such restrictive permissions, OK for now i will chmod the files that require it.
