### ISSUE TITLE
Can't access WebUI

### ISSUE THREAD

**Issue by tr0sity** [binhex/arch-delugevpn#290]
Can't figure out for the life of me why I cant access the web, I can access other docker's WebUI's. Here is the pastebin of the supervisord.log https://pastebin.com/1gzBj10Y

**Comment by binhex** [comment]
there are multiple potential reasons for not being able to access the web ui, lets start with the most common, incorrectly defined LAN_NETWORK, see Q4:- https://github.com/binhex/documentation/blob/master/docker/faq/vpn.md

**Comment by tr0sity** [comment]
Thanks, that seems to have done it!
