### ISSUE TITLE
Unable to successfully download PIA json to generate token from URL

### ISSUE THREAD

**Issue by groot-stuff** [binhex/arch-delugevpn#292]
Started getting this error after autobackup on unRaid restarted the delugevpn container this morning. Web UI gives a 502 bad gateway error for good measure as well.

unRaid docker log:
"2021-11-15 07:13:34,145 DEBG 'start-script' stdout output:
parse error: Invalid numeric literal at line 2, column 0

2021-11-15 07:13:34,146 DEBG 'start-script' stdout output:
[warn] Unable to successfully download PIA json to generate token from URL 'https://privateinternetaccess.com/gtoken/generateToken'
[info] 1 retries left
[info] Retrying in 10 secs..."

Navigating to the generateToken url results in a custom 404 page from PIA:

"OOPS!
It looks like the page you were looking for isn't here anymore. Feel free to visit our homepage by clicking the button below."

I have been using the "ca-vancouver.privacy.network" endpoint on port 1198 for ages, which is on the list of endpoints that support strict port forwarding. Disabling strict port forwarding allows the container to start but is undesirable (as it prevents routing radarr/sonarr and other containers through the delugevpn container).

**Comment by ajw107** [comment]
I'm getting the same error (using the netherlands endpoint), the problem seems to be that the page no longer exists to download the json from.  This is with wireguard, I have to admit I am also getting the same error openvpn too.  The result is this error error:
```
DEBG 'start-script' stderr output:
parse error: Invalid numeric literal at line 2, column 0
```

I assume because instead of the expected json, it is downloading the html for PIAs standard  'Page Not Found' page.  Not sure if this is a temporary problem with PIA or if they have changed their links for some reason.

**Comment by JoeDruryVS** [comment]
'https://privateinternetaccess.com/gtoken/generateToken' redirects to 'https://privateinternetaccess.com/ar/gtoken/generateToken'

If you remove the "ar/" in your browser, then you get a JSON output.

**Comment by ajw107** [comment]
Think I've found the solution.  I noticed that https://github.com/pia-foss changed all their https://privateinternetaccess.com addresses to https://www,privateinternetaccess.com  I added the www. to getvpnport.sh and wireguard.sh and everything seems to now work.

**Comment by JoeDruryVS** [comment]
> 
> 
> Think I've found the solution. I noticed that https://github.com/pia-foss changed all their https://privateinternetaccess.com addresses to https://www,privateinternetaccess.com I added the [www](http://www). to getvpnport.sh and wireguard.sh and everything seems to now work.

Awesome, I got it working too!
For anyone wondering, I spun up a container and ran `docker exec -it deluge bash` 
Then `nano /root/getvpnport.sh`
Scroll down to where it says "token_json_response=$(curl --interface "${VPN_DEVICE_TYPE}" --silent --insecure -u "${VPN_USER}:${VPN_PASS}"" and add "www." to the PIA URL.
exit, and restart the deluge container

**Comment by Thimira** [comment]
> > Think I've found the solution. I noticed that https://github.com/pia-foss changed all their https://privateinternetaccess.com addresses to https://www,privateinternetaccess.com I added the [www](http://www). to getvpnport.sh and wireguard.sh and everything seems to now work.
> 
> Awesome, I got it working too! For anyone wondering, I spun up a container and ran `docker exec -it deluge bash` Then `nano /root/getvpnport.sh` Scroll down to where it says "token_json_response=$(curl --interface "${VPN_DEVICE_TYPE}" --silent --insecure -u "${VPN_USER}:${VPN_PASS}"" and add "www." to the PIA URL. exit, and restart the deluge container

I can confirm that this fix works. Thank you very much!

**Comment by bibi32** [comment]
Works with  arch-rtorrentvpn with editing /root/getvpnport.sh and /root/wireguard.sh.

**Comment by groot-stuff** [comment]
> Think I've found the solution. I noticed that https://github.com/pia-foss changed all their https://privateinternetaccess.com addresses to https://www,privateinternetaccess.com I added the [www](http://www). to getvpnport.sh and wireguard.sh and everything seems to now work.

This does indeed work, thank you @ajw107!


> > Think I've found the solution. I noticed that https://github.com/pia-foss changed all their https://privateinternetaccess.com addresses to https://www,privateinternetaccess.com I added the [www](http://www). to getvpnport.sh and wireguard.sh and everything seems to now work.
> 
> Awesome, I got it working too! For anyone wondering, I spun up a container and ran `docker exec -it deluge bash` Then `nano /root/getvpnport.sh` Scroll down to where it says "token_json_response=$(curl --interface "${VPN_DEVICE_TYPE}" --silent --insecure -u "${VPN_USER}:${VPN_PASS}"" and add "www." to the PIA URL. exit, and restart the deluge container

Thanks for the instructions @JoeDruryVS!

Hopefully master-binhex will be able to drop an update for the lesser-inclined soon. :)
Cheers!

**Comment by binhex** [comment]
the fix is in, please pull 'latest' tagged image and let me know how you get on.

**Comment by JoeDruryVS** [comment]
Working for me! Thanks!

**Comment by groot-stuff** [comment]
Affirmative, CA Auto Update pulled it last night and it is looking good!
Thanks @binhex!
