### ISSUE TITLE
Clarification on purpose of Privoxy

### ISSUE THREAD

**Issue by woojoo666** [binhex/arch-delugevpn#294]
from the Readme, it doesn't seem entirely clear what the purpose of Privoxy here is. From what I read online, Privoxy is commonly used for adblocking (like UBlock). The delugevpn readme however says

> It also includes Privoxy to allow unfiltered access to index sites, to use Privoxy please point your application at http://<host ip>:8118

The word "unfiltered" makes me think that Privoxy is so applications can bypass the VPN? However the [reddit comment here](https://old.reddit.com/r/Piracy/comments/czzv24/what_are_some_essential_programs_every_pirate/ez8ceud/) says:

> Then using the same deluge docker I can enable privoxy and port all the other dockers through the VPN as well. Doing it this way also stops radarr or sonarr from talking to jackett ... It gives me a peace of mind knowing everything is running through the VPN

This makes me think Privoxy is used so other containers like radarr and sonarr can route through delugevpn's internal VPN.

So I'm a bit confused on what exactly Privoxy is used for here. Was wondering if anybody could help clear this up.

**Comment by binhex** [comment]
> The word "unfiltered" makes me think that Privoxy is so applications can bypass the VPN?
you cut short the readme, if you read on it says that "..bypass any filtering that maybe present by your **ISP**" so its not filtering oyur vpn connection, that would be pointless as one of the benefits of a vpn is that you get an unfiltered connection, what it is doing is bypassing nay isp filtering by using the vpn tunnel.

> This makes me think Privoxy is used so other containers like radarr and sonarr can route through delugevpn's internal VPN.

indeed, you can also connect other containers to the vpn tunnel setup by this docker image, so this is another way of using this image, in this scenario all traffic for any containers sharing the network will be forced to use the vpn, it doesnt interact with privoxy process, its simply sharing network connectivity, this video is a bit out of date but might make things clearer for you:-
https://www.youtube.com/watch?v=2MNqonB86ec

**Comment by woojoo666** [comment]
oh I see, I totally missed the FAQ, there's a treasure trove of information there. Will be referring to that from now on, thanks!
