### ISSUE TITLE
Not able to send torrents to Deluge

### ISSUE THREAD

**Issue by scbuckeye75** [binhex/arch-delugevpn#30]
Not able to send torrents to deluge. I have tried to set this manually. This is using the docker app in Unraid v6.3.5

Please see below for example from the log. I am able to test the connection to deluge webui successfully, however.

2017-07-06 23:18:06 WARNING SEARCHQUEUE-MANUAL-161511 :: Deluge: Unable to send Torrent

**Comment by cron410** [comment]
What are you using to send the torrents? This should work find over the local network.

**Comment by binhex** [comment]
no response from OP, closing
