### ISSUE TITLE
Peer ID and Agent ID versions aren't matching and reporting two different versions thus breaking tracker

### ISSUE THREAD

**Issue by RalphHartman** [binhex/arch-delugevpn#325]
Getting error in tracker:  
"-DE205s- Deluge/2.1.1 libtorrent/2.0.6.0	
Client calling in as ("-DE" / "Deluge/2.1.1 libtorrent/2.0.6.0")

Sounds like the Peer ID and Agent ID aren't matching and reporting two different versions and breaking tracker.  Peer ID should  be "-DE211s-" and not "DE205s-"

Peer ID created here:  
https://github.com/deluge-torrent/deluge/blob/develop/deluge/core/core.py#L249%C2%A0

Last version this seemed to work is binhex/arch-delugevpn:2.0.5-1-04

**Comment by RalphHartman** [comment]
Looks like you guys fixed this yesterday !  Thanks for the quick response.  Agent now shows up as 
Deluge/2.1.1 libtorrent/2.0.7.0 and tracker is working.

**Comment by binhex** [comment]
thanks for the confirmation that my fix worked :-)

**Comment by binhex** [comment]
sure its still maintaned, i have done the code changes just not pushed the build button, let me do that now.
