### ISSUE TITLE
OVPN  ncp-disable breaks on tag 2.1.1-3-02

### ISSUE THREAD

**Issue by tskramp** [binhex/arch-delugevpn#349]
On the latest build I get the error:
Options error: Unrecognized option or missing or extra parameter(s) in /config/openvpn/vpn.ovpn:34: ncp-disable (2.6.0).
Works on tag 2.1.1-3-01, but when updated to 2.1.1-3-02 I get the error with no other changes

**Comment by mguyard** [comment]
Hi,

It's a normal behavior as OpenVPN 2.6 as depreciate this option : https://community.openvpn.net/openvpn/wiki/DeprecatedOptions#Option:--ncp-disableStatus:RemovedinOpenVPNv2.6
So only remove it in your ovpn config and all we be ok
