### ISSUE TITLE
OpenVPN broken on 2.1.1-3-02

### ISSUE THREAD

**Issue by CptLoRes** [binhex/arch-delugevpn#350]
Log has continuous stream of:
Options error: Unrecognized option or missing or extra parameter(s) in /config/openvpn/xxx.ovpn:20: keysize (2.6.0)

Reverting to 2.1.1-3-01 fixes issue.

**Comment by tank101st** [comment]
I am getting 
 DEBG 'start-script' stdout output:Options error: Unrecognized option or missing or extra parameter(s) in /config/openvpn/my_expressvpn_usa_-_seattle_udp.ovpn:20: keysize (2.6.0)

any luck on how to fix?

**Comment by binhex** [comment]
Look at line 20 in your openvpn config file, it should say keysize delete that line, that option is now invalid

**Comment by tank101st** [comment]
Man, thanks for getting back to me so quick. It was driving me crazy all is working. Thanks again.
