### ISSUE TITLE
iptables permission denied

### ISSUE THREAD

**Issue by Neonica** [binhex/arch-delugevpn#358]
I've been trying to connect delugevpn with pia as a container on a QNAP ts464 using portianer, and keep getting this error:
iptables v1.8.9 (legacy): can't initialize iptables table `filter': Permission denied (you must be root)
Perhaps iptables or your kernel needs to be upgraded.
2023-03-13 13:21:53.828037 [crit] iptables kernel module 'ip_tables' not available, exiting script...
2023-03-13 13:21:59.635190 [crit] iptables kernel module 'ip_tables' not available, exiting script...
not sure what I need to change in order for this to resolve correctly, I'm relatively new to this.
Thanks

**Comment by Silkas01** [comment]
Had the same problem and solved it by adding this line to my docker compose file:
` sysctls:
      net.ipv4.conf.all.src_valid_mark: 1`

**Comment by Neonica** [comment]
> Had the same problem and solved it by adding this line to my docker compose file: ` sysctls: net.ipv4.conf.all.src_valid_mark: 1`

Thanks for the reply! If I'm building this in portainer using an image file, where could I add this, would it work as an environment variable? Or is that only possible using command line to deploy the container from my own docker compose file?

**Comment by jarixe** [comment]
Hello, could you tell me what solved your issue? I've got the same issue.
@Neonica
