### ISSUE TITLE
Seems there might have been a PIA update

### ISSUE THREAD

**Issue by jsindy** [binhex/arch-delugevpn#36]
2017-10-19 14:06:23,185 DEBG 'deluge-script' stdout output:
[debug] Waiting for file '/home/nobody/vpn_incoming_port.txt' to be generated (contains PIA API generated incoming port number)...

2017-10-19 14:06:23,249 DEBG 'start-script' stdout output:
[warn] Response code 000 from curl != 2xx
[warn] Exit code 7 from curl != 0
[info] 12 retries left

see this over and over, anyone else?

**Comment by Redsandro** [comment]
Yes, me too, causing annoying delay.

```
2017-10-23 21:28:46,803 DEBG 'start-script' stdout output:
[warn] Response code 000 from curl != 2xx
[warn] Exit code 7 from curl != 0
[info] 8 retries left
[info] Retrying in 10 secs...

2017-10-23 21:28:56,961 DEBG 'start-script' stdout output:
[warn] Response code 000 from curl != 2xx
[warn] Exit code 7 from curl != 0
[info] 7 retries left
[info] Retrying in 10 secs...
```

I don't know what it is, but after waiting, Deluge does finally start, but with the following warnings:

```
2017-10-23 21:30:08,078 DEBG 'start-script' stdout output:
[warn] Response code 000 from curl != 2xx, exausted retries exiting script...

2017-10-23 21:30:08,079 DEBG 'start-script' stdout output:
[warn] PIA endpoint 'mexico.privateinternetaccess.com' doesn't support port forwarding, DL/UL speeds will be slow
[info] Please consider switching to an endpoint that does support port forwarding, shown below:-

2017-10-23 21:30:08,089 DEBG 'start-script' stdout output:
[info] ca-toronto.privateinternetaccess.com (CA Toronto)
[info] ca.privateinternetaccess.com (CA Montreal)
[info] nl.privateinternetaccess.com (Netherlands)
[info] swiss.privateinternetaccess.com (Switzerland)
[info] sweden.privateinternetaccess.com (Sweden)
[info] france.privateinternetaccess.com (France)
[info] ro.privateinternetaccess.com (Romania)
[info] israel.privateinternetaccess.com (Israel)
```

@binhex There are some issues with this:

1. The logs can be more clear about what it's trying to do. Also, can we try a couple of times quicker, and give up sooner?
1. No one specified `mexico.privateinternetaccess.com`. The readme says `Netherlands` is the default. How did Mexico sneak in there?
1. If I explicitly set `-e VPN_REMOTE=sweden.privateinternetaccess.com`, it still complains about Mexico.

**Comment by binhex** [comment]
ok so ive switched from using env var's to define the endpoint you connect to, to parsing the ovpn file, several reasons which i wont go into here, but in short the ovpn file will be what is used, and you look to of dropped in a pia file for the mexico endpoint, and as the mexico endpoint does not support port forwarding you are seeing the messages in your post, so two options:-

1. set strict_port_forward to no 
or
2. switch endpoint in the ovpn file to be one of the ones listed in your post.

my advise is to go with 2. otherwise your speeds will be VERY low.

**Comment by Redsandro** [comment]
@binhex ah ok since I thought the env var decides which ovpn file to use, I've extracted _all_ ovpn files into the ovpn folder (it's good to have options).

But now it somehow chooses Mexico out of the bunch. any idea why? Here are the contents of my `openvpn` mapping:

```
$ ls
AU Melbourne.ovpn  France.ovpn       New Zealand.ovpn     US California.ovpn
AU Sydney.ovpn     Germany.ovpn      Norway.ovpn          US Chicago.ovpn
Brazil.ovpn        Hong Kong.ovpn    Romania.ovpn         US East.ovpn
CA Montreal.ovpn   India.ovpn        Singapore.ovpn       US Florida.ovpn
ca.rsa.2048.crt    Ireland.ovpn      South Korea.ovpn     US Midwest.ovpn
CA Toronto.ovpn    Israel.ovpn       Sweden.ovpn          US New York City.ovpn
credentials.conf   Italy.ovpn        Switzerland.ovpn     US Seattle.ovpn
crl.rsa.2048.pem   Japan.ovpn        Turkey.ovpn          US Silicon Valley.ovpn
Denmark.ovpn       Mexico.ovpn       UK London.ovpn       US Texas.ovpn
Finland.ovpn       Netherlands.ovpn  UK Southampton.ovpn  US West.ovpn
```

**Comment by Redsandro** [comment]
I think I get it. It just picks the first one, which for the computer isn't necessarily alphabetically the first one.

So best practice is to have just _one_ ovpn file. Name is irrelevant.

**Comment by binhex** [comment]
Exactly.
