### ISSUE TITLE
Suddenly receiving AUTH_FAILED on previously working setup

### ISSUE THREAD

**Issue by jdbecker** [binhex/arch-delugevpn#370]
Admittedly this is probably not arch-delugevpn's issue because I'm having the same problem on my arch-sabnzbdvpn container, but I'm having a lot of trouble trying to debug this and was hoping to get some ideas here. My services were both previously working fine, but at some point in the last few days, they suddenly stopped working, and when I try to restart them, I get the error message: "AUTH: Received control message: AUTH_FAILED". I've double-checked my name and password and they're still correct (though I wouldn't expect anything else since this same setup was previously working and suddenly stopped). I logged into NordVPN (my provider) app for desktops with this same name and password and it worked fine, so the issue isn't anything to do with my name and password. I even tried updating my ovpn config files to a server that I had just connected to via the desktop app, but with no luck. I'm not sure what else to try, I'd appreciate any suggestions.

Thank you for your help!

**Comment by zkhan96** [comment]
I experienced the same isuse just today: 

2023-07-05 17:02:29 AUTH: Received control message: AUTH_FAILED

checked username and password in nordVPN and works fine, even switched to a new ovpn file with no luck. restarted server and container as well. running latest version of the container.

**Comment by zkhan96** [comment]
This has solved it for me. Looks like my VPN provider didnt send out any comms about this change... Let me know if it fixes it for you as well!

**Comment by jdbecker** [comment]
> i found this reddit thread that might be relevant: https://www.reddit.com/r/nordvpn/comments/14l7r7k/anyone_else_unable_to_login/

This fixed it for me too! Good find! Thanks for sharing!
