### ISSUE TITLE
Openvpn config files missing

### ISSUE THREAD

**Issue by crtpoms** [binhex/arch-delugevpn#38]
Not sure if this is a issue or not but when starting getting errors that the ovpn file and serts are not pressent. How does this work now?

**Comment by FR-TheS** [comment]
Hi,

Do you use a vpn provider as custom ?

**Comment by tizmagik** [comment]
I'm getting this too. I do have a `*.ovpn` file in `/config/openvpn`

**Comment by binhex** [comment]
you download the ovpn file and certs from your vpn provider and place them in /config/openvpn/
