### ISSUE TITLE
Multiple LAN_NETWORK

### ISSUE THREAD

**Issue by Portagoras** [binhex/arch-delugevpn#388]
In my Network, I got my local network and a vpn Network of multiple subnets, of which some would need Access to the Deluge Machine.
Now I can only define one LAN_NETWORK here. Would it be possbile to change the Variable to something like a comma seperated list?

**Comment by binhex** [comment]
It already is a comma separated list 😁

**Comment by Portagoras** [comment]
Thanks!!
