### ISSUE TITLE
iptable_mangle module - docker for windows

### ISSUE THREAD

**Issue by chosejavez** [binhex/arch-delugevpn#389]
Both attempts to load the iptable_mangle module fail. After that I can't load the Web UI since the VPN appears compromised.

> 2024-01-10 07:32:49,082 DEBG 'start-script' stdout output:
> [info] Adding 1.0.0.1 to /etc/resolv.conf
> [info] Attempting to load iptable_mangle module...
> [warn] Unable to load iptable_mangle module using modprobe, trying insmod...
> [warn] Unable to load iptable_mangle module, you will not be able to connect to the applications Web UI or Privoxy outside of your LAN
> [info] unRAID/Ubuntu users: Please attempt to load the module by executing the following on your host: '/sbin/modprobe iptable_mangle'
> [info] Synology users: Please attempt to load the module by executing the following on your host: 'insmod /lib/modules/iptable_mangle.ko'
> [debug] Show name servers defined for container

Attaching my logs.

[supervisord.log](https://github.com/binhex/arch-delugevpn/files/13885336/supervisord.log)

**Comment by vpaulson** [comment]
Did you ever find a solution for this? I just updated to the latest image and am getting this error now on Windows.

**Comment by gjdass** [comment]
On Debian, same error.

```
[info] Attempting to load iptable_mangle module...
2024-01-26 17:58:01,890 DEBG 'start-script' stderr output:
modprobe: FATAL: Module iptable_mangle not found in directory /lib/modules/5.10.0-27-amd64
2024-01-26 17:58:01,890 DEBG 'start-script' stdout output:
[warn] Unable to load iptable_mangle module using modprobe, trying insmod...
2024-01-26 17:58:01,892 DEBG 'start-script' stderr output:
insmod: ERROR: could not load module /lib/modules/iptable_mangle.ko: No such file or directory
2024-01-26 17:58:01,892 DEBG 'start-script' stdout output:
[warn] Unable to load iptable_mangle module, you will not be able to connect to the applications Web UI or Privoxy outside of your LAN
[info] unRAID/Ubuntu users: Please attempt to load the module by executing the following on your host: '/sbin/modprobe iptable_mangle'
2024-01-26 17:58:01,892 DEBG 'start-script' stdout output:
[info] Synology users: Please attempt to load the module by executing the following on your host: 'insmod /lib/modules/iptable_mangle.ko'
2024-01-26 17:58:01,905 DEBG 'start-script' stdout output:
[info] Default route for container is 172.18.0.1
2024-01-26 17:58:02,095 DEBG 'start-script' stdout output:
[info] Docker network defined as    172.18.0.0/16
2024-01-26 17:58:02,099 DEBG 'start-script' stdout output:
[info] Adding 192.168.1.0/24 as route via docker eth0
2024-01-26 17:58:02,101 DEBG 'start-script' stdout output:
[info] ip route defined as follows...
```

**Comment by chosejavez** [comment]
@vpaulson @gjdass I didn’t find a solution with my setup at the time. I was running Docker for Windows. Now I’m running Ubuntu VM and installed docker on it natively. No issued and it immediately worked. I spent more time trying to find a solution than setting this up.

**Comment by gjdass** [comment]
Ok, just found the solution.

I had the wrong IP. So by default, it was refusing my connections (all my network is under 192.168.2.0/24 and I input 192.168.1.0/24 ...).

It's fixed for me.

```
docker run -d \
[...]
-e LAN_NETWORK=<lan ipv4 network>/<cidr notation> \
[...]
```

**Comment by chosejavez** [comment]
That’s interesting. I back up my docker composes files. I was positive the same yaml failed in windows but worked in Ubuntu. Glad you found your solution!

**Comment by vpaulson** [comment]
So not 100% sure what was wrong but I was using Docker with HyperV on windows 10. I switch to using WSL2 instead of HyperV and it works now lol
