### ISSUE TITLE
Unable to access to the web interface

### ISSUE THREAD

**Issue by FR-TheS** [binhex/arch-delugevpn#39]
Hello,

Here my env cfg :
```
"PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin",
"HOME=/data/deluge-home/",
"TERM=xterm",
"LANG=en_GB.UTF-8",
"VPN_ENABLED=yes",
"VPN_USER=sephirot314@hotmail.fr",
"VPN_PASS=xxx",
"VPN_PROV=custom",
"UMASK=0755",
"VPN_OPTIONS=France-256.ovpn",
"LAN_NETWORK=192.168.1.0/24",
"ENABLE_PRIVOXY=yes"
```

My server is on the router ip 192.168.1.3 and when i'm trying to access to 192.168.1.3:8112 from 192.168.1.2 computer, it's not working. I got a message in my browser saying the computer doesn't allow access to the page.

**Comment by abhishekjain14** [comment]
I had the same issue. The fix for me was to run this command on my host computer (found it in another issue):

sudo iptables -t nat -D PREROUTING 1

(I'm using an Ubuntu host)

**Comment by FR-TheS** [comment]
I don't have PREROUTING in my iptable on DEBIAN. Here my iptables of the docker 
Chain INPUT (policy DROP)
target     prot opt source               destination
ACCEPT     all  --  anywhere             anywhere
ACCEPT     all  --  172.17.0.0/16        172.17.0.0/16
ACCEPT     udp  --  anywhere             anywhere             udp spt:https
ACCEPT     tcp  --  anywhere             anywhere             tcp dpt:8112
ACCEPT     tcp  --  anywhere             anywhere             tcp spt:8112
ACCEPT     tcp  --  192.168.1.0/24       anywhere             tcp dpt:58846
ACCEPT     tcp  --  192.168.1.0/24       172.17.0.0/16
ACCEPT     icmp --  anywhere             anywhere             icmp echo-reply
ACCEPT     all  --  anywhere             anywhere

Chain FORWARD (policy ACCEPT)
target     prot opt source               destination

Chain OUTPUT (policy DROP)
target     prot opt source               destination
ACCEPT     all  --  anywhere             anywhere
ACCEPT     all  --  172.17.0.0/16        172.17.0.0/16
ACCEPT     udp  --  anywhere             anywhere             udp dpt:https
ACCEPT     tcp  --  anywhere             anywhere             tcp dpt:8112
ACCEPT     tcp  --  anywhere             anywhere             tcp spt:8112
ACCEPT     tcp  --  anywhere             192.168.1.0/24       tcp spt:58846
ACCEPT     tcp  --  172.17.0.0/16        192.168.1.0/24
ACCEPT     icmp --  anywhere             anywhere             icmp echo-request
ACCEPT     all  --  anywhere             anywhere

**Comment by mrcirillo** [comment]
This is also a problem on an arch host. The PREROUTING suggestion above seems to have no effect. Disabling VPN fixes the problem

**Comment by binhex** [comment]
guys, please don't "me too" this issue, there are dozens of reasons why the tunnel can't be established (and thus the web ui inaccessible), you will need to follow the procedure below if you want to have this resolved:-

https://forums.lime-technology.com/topic/44108-support-binhex-general/?do=findComment&comment=435831
