### ISSUE TITLE
WebUI broke after update/upgrade

### ISSUE THREAD

**Issue by kolmpjess** [binhex/arch-delugevpn#390]
WebUI broke after running update/upgrade on my ubuntu system.
It works when launching without VPN, it does not when running with VPN.
Before update/upgrade it worked properly.
It is only the WebUI, Deluge itself is running with VPN.

History.log -> https://pastebin.com/Tk0ApMY0
Supervisord.log -> https://pastebin.com/0d1ttWvS
Netstat -r -> https://pastebin.com/FFPXX6qM

Apps outside docker (i only use docker for DelugeVPN) are running properly.
I have been reading the log files but i have no clue on what the issue is/how to fix this, maybe someone can help.

**Comment by binhex** [comment]
I think (cannot tell as you trimmed the useful start section) that you have a badly defined LAN_NETWORK, from your log I think it's 192.168.2.4/24 see Q4 https://github.com/binhex/documentation/blob/master/docker/faq/vpn.md

**Comment by kolmpjess** [comment]
> I think (cannot tell as you trimmed the useful start section) that you have a badly defined LAN_NETWORK, from your log I think it's 192.168.2.4/24 see Q4 https://github.com/binhex/documentation/blob/master/docker/faq/vpn.md

You are right! Weird that it did start before with the previous line, corrected it, and i have a WebUI again!

Thank you!
