### ISSUE TITLE
Failed call to `kill`

### ISSUE THREAD

**Issue by samvv** [binhex/arch-delugevpn#392]
When running this image using ProtonVPN and WireGuard, I get the the following messages:

```
deluge-1   | [info] Script finished to assign incoming port
deluge-1   | 
deluge-1   | 2024-03-05 21:20:34,512 DEBG 'start-script' stderr output:
deluge-1   | kill: usage: kill [-s sigspec | -n signum | -sigspec] pid | jobspec ... or kill -l [sigspec]
```

The web UI fails of Deluge to load, either due to this issue or due to another.

**Comment by samvv** [comment]
On that note: `start.sh` seems to be missing from this repository. I was going to debug this but can only find references to the script.

**Comment by binhex** [comment]
ensure you follow Q31:- https://github.com/binhex/documentation/blob/master/docker/faq/vpn.md

**Comment by samvv** [comment]
I'm assuming that fixes my issue. Closing this for now.
