### ISSUE TITLE
BlockingIOError: [Errno 11] Resource temporarily unavailable

### ISSUE THREAD

**Issue by RobCod** [binhex/arch-delugevpn#397]
I recently reinstalled deluge so I could use a different VPN provider and now it looks like I'm getting errors with my file share possibly?

It worked perfectly prior to my re-install, so I have no idea why its having issues with it now. I can force the torrents to resume and they will resume and download perfectly fine for like 15-60 minutes and then error out so I have to force them to resume again. If I resume it long enough to download fully it downloads perfectly fine into the share folders and even gets moved to the folders I have set them to move to. If I change the download folders in the UI interface it even creates the new folders in the share perfectly fine. 

What would a fix for this be? I also have plenty of space so, I'm definitely not running out of space(10TB)

```
BlockingIOError: [Errno 11] Resource temporarily unavailable: b'/downloads/incomplete'

19:33:57 [ERROR   ][deluge.core.rpcserver         :1622] Exception calling RPC request: [Errno 11] Resource temporarily unavailable: b'/downloads/incomplete'
Traceback (most recent call last):
  File "/usr/lib/python3.11/site-packages/deluge/core/rpcserver.py", line 334, in dispatch
    ret = self.factory.methods[method](*args, **kwargs)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/deluge/core/core.py", line 1244, in get_free_space
    return deluge.common.free_space(path)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/deluge/common.py", line 905, in free_space
    disk_data = os.statvfs(path.encode('utf8'))
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
BlockingIOError: [Errno 11] Resource temporarily unavailable: b'/downloads/incomplete'
19:33:59 [WARNING ][deluge.core.rpcserver         :1622] An exception occurred while sending RPC_ERROR to client. Wrapping it and resending. Error to send(causing exception goes next):
Traceback (most recent call last):
  File "/usr/lib/python3.11/site-packages/deluge/core/rpcserver.py", line 334, in dispatch
    ret = self.factory.methods[method](*args, **kwargs)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/deluge/core/core.py", line 1244, in get_free_space
    return deluge.common.free_space(path)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/deluge/common.py", line 905, in free_space
    disk_data = os.statvfs(path.encode('utf8'))
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
BlockingIOError: [Errno 11] Resource temporarily unavailable: b'/downloads/incomplete'

19:33:59 [ERROR   ][deluge.core.rpcserver         :1622] Exception calling RPC request: [Errno 11] Resource temporarily unavailable: b'/downloads/incomplete'
Traceback (most recent call last):
  File "/usr/lib/python3.11/site-packages/deluge/core/rpcserver.py", line 334, in dispatch
    ret = self.factory.methods[method](*args, **kwargs)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/deluge/core/core.py", line 1244, in get_free_space
    return deluge.common.free_space(path)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/deluge/common.py", line 905, in free_space
    disk_data = os.statvfs(path.encode('utf8'))
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
BlockingIOError: [Errno 11] Resource temporarily unavailable: b'/downloads/incomplete'
19:34:01 [WARNING ][deluge.core.rpcserver         :1622] An exception occurred while sending RPC_ERROR to client. Wrapping it and resending. Error to send(causing exception goes next):
Traceback (most recent call last):
  File "/usr/lib/python3.11/site-packages/deluge/core/rpcserver.py", line 334, in dispatch
    ret = self.factory.methods[method](*args, **kwargs)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/deluge/core/core.py", line 1244, in get_free_space
    return deluge.common.free_space(path)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/deluge/common.py", line 905, in free_space
    disk_data = os.statvfs(path.encode('utf8'))
```

**Comment by jcviquez** [comment]
I'm having a really similar problem. Reinstalled after recreating my docker VM and only arch-delugevpn is having problems after the migration.
Data folder mapped to smb mount on my VM with fstab. I tested the permissions several times both on the VM and from the container console and I can create, delete and move files normally. I did noticed that when I check with ls -l on the console I get a similar error about _Resource temporarily unavailable_ and then the folders and files get listed normally.

Every time I bring the container online, it starts re-checking multiple torrents marked with errors and I can download and move downloads for a while, but after a few mins I no longer can download or move things.

I use Deluge as Thin Client and noticed I cannot see the remaining free space on the status bar next to the HDD icon as usual, which I guess relates to the error on the log about _get_free_space_

Docker host VM OS:  Ubuntu 22.04.4 LTS (GNU/Linux 5.15.0-102-generic x86_64)
Docker engine version: 25.0.5
Docker environment managed with Portainer-CE 2.19.4
SMB Host: TrueNAS-SCALE-23.10.2

Redacted docker-compose:
```
services:
  arch-delugevpn:
    image: binhex/arch-delugevpn
    container_name: arch-delugevpn
    privileged: true
    devices:
      - /dev/net/tun
    ports:
      - 8112:8112
      - 58846:58846
    volumes:
      - /smb/arch-delugevpn/data:/data
      - /smb/arch-delugevpn/config:/config
      - /etc/localtime:/etc/localtime:ro
    environment:
      ...
      - UMASK=000
      - PUID=1000
      - PGID=1002
    sysctls:
      - net.ipv4.conf.all.src_valid_mark=1
```

Console example:
```
ls -l
ls: torrent-backups: Resource temporarily unavailable
ls: watch: Resource temporarily unavailable
ls: completed: Resource temporarily unavailable
ls: downloading: Resource temporarily unavailable
total 0
drwxr-xr-x 2 nobody users 0 Apr 18 18:28 completed
drwxr-xr-x 2 nobody users 0 Apr 18 17:11 downloading
drwxr-xr-x 2 nobody users 0 Apr 18 17:10 torrent-backups
drwxr-xr-x 2 nobody users 0 Apr 18 17:46 watch
```

deluged.log:
```
21:12:30 [ERROR   ][deluge.core.torrent           :1622] Restart deluge to clear this torrent error
21:12:30 [INFO    ][deluge.core.rpcserver         :1622] Deluge client disconnected: Connection to the other side was lost in a non-clean fashion: Connection lost.
21:12:30 [INFO    ][deluge.core.rpcserver         :1622] Deluge Client connection made from: 127.0.0.1:35920
21:12:32 [WARNING ][deluge.core.rpcserver         :1622] An exception occurred while sending RPC_ERROR to client. Wrapping it and resending. Error to send(causing exception goes next):
Traceback (most recent call last):
  File "/usr/lib/python3.11/site-packages/deluge/core/rpcserver.py", line 334, in dispatch
    ret = self.factory.methods[method](*args, **kwargs)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/deluge/core/core.py", line 1244, in get_free_space
    return deluge.common.free_space(path)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/deluge/common.py", line 905, in free_space
    disk_data = os.statvfs(path.encode('utf8'))
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
BlockingIOError: [Errno 11] Resource temporarily unavailable: b'/data/torrent/downloading'

```

**Comment by RobCod** [comment]
> I'm having a really similar problem. Reinstalled after recreating my docker VM and only arch-delugevpn is having problems after the migration. Data folder mapped to smb mount on my VM with fstab. I tested the permissions several times both on the VM and from the container console and I can create, delete and move files normally. I did noticed that when I check with ls -l on the console I get a similar error about _Resource temporarily unavailable_ and then the folders and files get listed normally.
> 
> Every time I bring the container online, it starts re-checking multiple torrents marked with errors and I can download and move downloads for a while, but after a few mins I no longer can download or move things.
> 
> I use Deluge as Thin Client and noticed I cannot see the remaining free space on the status bar next to the HDD icon as usual, which I guess relates to the error on the log about _get_free_space_
> 
> Docker host VM OS: Ubuntu 22.04.4 LTS (GNU/Linux 5.15.0-102-generic x86_64) Docker engine version: 25.0.5 Docker environment managed with Portainer-CE 2.19.4 SMB Host: TrueNAS-SCALE-23.10.2
> 
> Redacted docker-compose:
> 
> ```
> services:
>   arch-delugevpn:
>     image: binhex/arch-delugevpn
>     container_name: arch-delugevpn
>     privileged: true
>     devices:
>       - /dev/net/tun
>     ports:
>       - 8112:8112
>       - 58846:58846
>     volumes:
>       - /smb/arch-delugevpn/data:/data
>       - /smb/arch-delugevpn/config:/config
>       - /etc/localtime:/etc/localtime:ro
>     environment:
>       ...
>       - UMASK=000
>       - PUID=1000
>       - PGID=1002
>     sysctls:
>       - net.ipv4.conf.all.src_valid_mark=1
> ```
> 
> Console example:
> 
> ```
> ls -l
> ls: torrent-backups: Resource temporarily unavailable
> ls: watch: Resource temporarily unavailable
> ls: completed: Resource temporarily unavailable
> ls: downloading: Resource temporarily unavailable
> total 0
> drwxr-xr-x 2 nobody users 0 Apr 18 18:28 completed
> drwxr-xr-x 2 nobody users 0 Apr 18 17:11 downloading
> drwxr-xr-x 2 nobody users 0 Apr 18 17:10 torrent-backups
> drwxr-xr-x 2 nobody users 0 Apr 18 17:46 watch
> ```
> 
> deluged.log:
> 
> ```
> 21:12:30 [ERROR   ][deluge.core.torrent           :1622] Restart deluge to clear this torrent error
> 21:12:30 [INFO    ][deluge.core.rpcserver         :1622] Deluge client disconnected: Connection to the other side was lost in a non-clean fashion: Connection lost.
> 21:12:30 [INFO    ][deluge.core.rpcserver         :1622] Deluge Client connection made from: 127.0.0.1:35920
> 21:12:32 [WARNING ][deluge.core.rpcserver         :1622] An exception occurred while sending RPC_ERROR to client. Wrapping it and resending. Error to send(causing exception goes next):
> Traceback (most recent call last):
>   File "/usr/lib/python3.11/site-packages/deluge/core/rpcserver.py", line 334, in dispatch
>     ret = self.factory.methods[method](*args, **kwargs)
>           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "/usr/lib/python3.11/site-packages/deluge/core/core.py", line 1244, in get_free_space
>     return deluge.common.free_space(path)
>            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "/usr/lib/python3.11/site-packages/deluge/common.py", line 905, in free_space
>     disk_data = os.statvfs(path.encode('utf8'))
>                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
> BlockingIOError: [Errno 11] Resource temporarily unavailable: b'/data/torrent/downloading'
> ```

Yeah we have the exact same problem then, i also have the error where it used to give me my remaining space. I also changed the PID, and GID to the root user to make absolute sure im not having perm issues.

I can create, move and delete files as both my ubuntu user and the root user. Its just the docker container thats having issues for some reason.

Perhaps a update between September 2023 and now broke stuff?

**Comment by jcviquez** [comment]
I also tried using a previous version of arch-delugevpn using the tag [2.1.1-4-05] pushed 5 months ago instead of latest, but I had the same problem. Unfortunatelly I'm not sure what version of the image I was using before.

**Comment by jcviquez** [comment]
Hi @RobCod, I was looking for similar problems recently reported with other software and found someone using Immich with a similar setup (TrueNAS, Ubuntu VM, Docker, SMB Mount) with resource temporarily available errors and the problem seems to be related to the current linux kernel (Linux 5.15.0-102-generic) on the host VM Ubuntu machine.

References:
https://github.com/immich-app/immich/discussions/8487
https://github.com/home-assistant/operating-system/issues/3041
https://forum.manjaro.org/t/samba-share-ls-directory-resource-temporarily-unavailable/155083/7

As a temporary workaround the suggestion for Ubuntu 22.04.4 LTS is to downgrade to Linux 5.15.0-10**1**-generic which I did try and indeed solve my problems with arch-delugevpn. 

Not sure why only this container showed problems, or if the others had some that went unnoticeable for my use cases.

**Comment by RobCod** [comment]
> As a temporary workaround the suggestion for Ubuntu 22.04.4 LTS is to either downgrade to Linux 5.15.0-10**1**-generic which I did try and indeed solve my problems with arch-delugevpn or upgrade to 6.5.
> 
Exactly the issue, danke
