### ISSUE TITLE
Logs Web UI

### ISSUE THREAD

**Issue by waredsystems** [binhex/arch-delugevpn#40]
Hi,

Is there a way to access log for deluge-web ? I just find logs for the daemon (/config/deluged.log).
I would like to map it to my host and use fail2ban.

Thanks !

**Comment by binhex** [comment]
the deluge-web log is now sent to /config/deluge-web.log in the latest image, please pull down.

**Comment by megasuperlexa** [comment]
where is it now? I do not even have /config (Ubuntu)
