### ISSUE TITLE
"Username does not exist" error when trying to use deluge-console

### ISSUE THREAD

**Issue by fivestones** [binhex/arch-delugevpn#42]
I've got this docker container running and everything seems to be working great. However, when I try to manage torrents with the command line tool deluge-console (`docker exec delugevpn deluge-console info`),  it gives me the error 
```
[ERROR   ] 14:26:03 client:391 RPCError Message Received!
--------------------------------------------------------------------------------
RPCRequest: daemon.login(, )
--------------------------------------------------------------------------------
  File "/usr/lib/python2.7/site-packages/deluge/core/rpcserver.py", line 262, in dispatch
    ret = component.get("AuthManager").authorize(*args, **kwargs)
  File "/usr/lib/python2.7/site-packages/deluge/core/authmanager.py", line 89, in authorize
    raise BadLoginError("Username does not exist")

BadLoginError: Username does not exist
--------------------------------------------------------------------------------
Failed to connect to 127.0.0.1:58846 with reason: Username does not exist
```
The same thing happens if I use docker exec to get into bash in the container and run deluge-console there. I've looked up the error and some people had this error when they were running deluge-console from a different user than the one that is running deluge, and I'm guessing this is the problem, but I can't figure out how to make it work. Looking in htop while inside the container, it says that user nobody is running deluge. If i su nobody and then run deluge-console, I still get the same error. Any idea how I can use deluge-console with this docker container? Thanks!

**Comment by alocate938** [comment]
docker exec **[container ID of the docker]** deluge-console "connect 127.0.0.1:58846 **[user in auth file]** **[password in auth file**]; info" (NOTE: make sure a torrent is loaded in deluge!)

e.x.  docker exec f69620a35f54 deluge-console "connect 127.0.0.1:58846 nobody deluge ; info"

![capture](https://user-images.githubusercontent.com/35243854/34700092-b3ccdf16-f4a6-11e7-9ce7-dc434ec0cbde.PNG)
