### ISSUE TITLE
[debug] Waiting for valid IP address from tunnel...

### ISSUE THREAD

**Issue by KristofVr** [binhex/arch-delugevpn#43]
I think I filled in all the settings correctly but for some reason it stops at 'Waiting for valid IP address from tunnel...'. I don't know what I'm missing. Can you something in the logs?

[supervisord.log](https://github.com/binhex/arch-delugevpn/files/1563758/supervisord.log)

**Comment by binhex** [comment]
Remove the value you have for VPN_OPTIONS, from your log:-

`VPN_OPTIONS defined as 'MUNCHEN-tcp'`

This is used to define additional vpn options, leave it empty

next problem, you have incorrectly defined your LAN, from your log:-

`LAN_NETWORK defined as '192.168.0.0/24'`

This is not correct, see here for help Q3.:-

https://forums.lime-technology.com/topic/44108-support-binhex-general/?tab=comments#comment-433613

**Comment by binhex** [comment]
i will fix this up, thanks for the info.

**Comment by binhex** [comment]
fix complete.
