### ISSUE TITLE
PIA Setup Example is Out of Date

### ISSUE THREAD

**Issue by Wolfereign** [binhex/arch-delugevpn#45]
The example in the repo and at https://hub.docker.com/r/binhex/arch-delugevpn/ for Private Internet Access do not work.  It seems that to get thing to work we now have to download the openvpn config files from PIA and put the desired ovpn, crt, and pem file in the containers /config/openvpn folder.

The OVPN files can be found here https://www.privateinternetaccess.com/openvpn/openvpn.zip.

If this is not done and you follow the current examples the container goes into a restart loop.

I've had to use a bash script to get this all to work specifically because I had to have the openvpn config files in place before the docker container was run.  Here's my script if you want a reference https://github.com/Wolfereign/Portland/blob/master/run_container/deluge.sh

**Comment by jwigley** [comment]
I ran into the same issue. Thanks for pointing out the solution!

**Comment by DjCoke** [comment]
Ah damn thanks m8, you are my hero today

**Comment by binhex** [comment]
ok so i finally got around to enhancing the readme's, take a look guys i think its detailed enough to hopefully get somebody up and running fairly swiftly.

**Comment by Wolfereign** [comment]
Looks good to me.
