### ISSUE TITLE
Deluge Web UI Accessable Via localhost not via ip.

### ISSUE THREAD

**Issue by bensternthal** [binhex/arch-delugevpn#47]
Hoping this is an easy one, I cant seem to sort it.

Can reach deluge webui via localhost without issue (works great btw).

However on a diff machine on my network I can not reach the webui.

So
1. localhost:8112 works
2. 192.168.1.108:8112 does not work 

Docker Command

```
docker run -d 
--cap-add=NET_ADMIN 
-p 8112:8112 
-p 8118:8118
-p 58846:58846 
-p 58946:58946 
--name=delugevpn 
-v {a path}:/data 
-v {another path}:/config
-v /etc/localtime:/etc/localtime:ro 
-e VPN_ENABLED=yes 
-e VPN_USER=angela_merkel 
-e VPN_PASS=chocolate 
-e VPN_PROV=pia 
-e VPN_REMOTE=us-seattle.privateinternetaccess.com 
-e STRICT_PORT_FORWARD=no 
-e ENABLE_PRIVOXY=no 
-e LAN_NETWORK=192.168.1.1/24 
-e NAME_SERVERS=8.8.8.8,8.8.4.4 
-e DEBUG=false 
-e UMASK=000 
-e PUID=1000 
-e PGID=1000
 binhex/arch-delugevpn
```

Note other docker containers like nzbget and sonarr are reachable via ip.

Thanks for the help and effort on maintaining these containers!

**Comment by binhex** [comment]
this is wrong:-

`-e LAN_NETWORK=192.168.1.1/24 `

see here for how to define this correctly Q3.:-
https://forums.lime-technology.com/topic/44108-support-binhex-general/?tab=comments#comment-433613

**Comment by bensternthal** [comment]
Doh! Solved, thanks.

**Comment by Cthanatos** [comment]
for anyone who comes up on this later and wonders _what_ actually was wrong, like I did, it should have been like this - 
192.168.1.**0**/24

Mine was similar, I had put it as 192.168.0.1/24 (thinking it should follow my gateway) but once I changed it to 192.168.0.**0**/24 my webui worked fine after I killed and removed the old docker container and rebuilt it with the correct IP LAN info.
