### ISSUE TITLE
[REQUEST] Add ffmpeg, ffprobe and 7zip packages

### ISSUE THREAD

**Issue by kormic911** [binhex/arch-delugevpn#48]
Hi, 

I don't know if this is too much to ask, but would it be possible to include ffmpeg, ffprobe and 7zip in the docker container? I ask because adding these packages would allow for https://github.com/clinton-hall/nzbToMedia to be added as a deluge plugin. This plugin is very handy for auto extracting downloaded media files and well as verifying they are not corrupt.

Thanks in advance!

**Comment by binhex** [comment]
I'm afraid this isn't going to happen, this would make the image way to large and increase complexity.

**Comment by kormic911** [comment]
Would it be possible to include just 7zip? the image already contains unrar and unzip and tar? This would at least make all the extraction techniques available and post processing (ffmpeg/ffprobe) can be handled else where? I think this might be a minimal addition to the image (I dont personally know much about arch linux though)

**Comment by superkrups20056** [comment]
+1 for 7zip at least if possible.

**Comment by nikolak** [comment]
Gonna add +1 on 7zip too. This is very common requirement for plugins that automatically extract compressed files upon completion, and the overall overhead of adding it should be minimal.

While ffmpeg and similar could reasonably be considered out of scope, I don't think 7zip falls into that category.
