### ISSUE TITLE
[REQUEST] Upgrade libtorrent to 1.0.11

### ISSUE THREAD

**Issue by kormic911** [binhex/arch-delugevpn#49]
Hi,

Would it be possible to upgrade libtorrent to 1.0.11 from the 1.0.9 that is installed now? I have noticed with 1.0.9 there are a number of torrents that report `: Error: unsupported URL protocol`, however I do not see these same issues with 1.0.11.

Thanks in advance!

**Comment by binhex** [comment]
There is/was an issue with Deluge and the later version of libtorrent, so at this time its not possible to update to libtorrent 1.0.11

**Comment by kormic911** [comment]
Prior to submitting this request, I did look over the previous issues for this project and one I noticed was this one: https://github.com/binhex/arch-delugevpn/issues/20 it does state that there is a problem with the **1.1.x** branch of libtorrent but that the **1.0.x** branch is perfectly safe, hence the reason I asked for the upgrade to **1.0.11** not **1.1.6** which I know is incompatible.

**Comment by binhex** [comment]
ahh yes you are right, its been a long while since i visited the issue, all i knew is that there were some issues with a build of libtorrent :-), ok no probs i can do that, leave it with me.

**Comment by binhex** [comment]
im going to close this off for now, deluge 2.x is just around the corner, so i will review things after that is out.
