### ISSUE TITLE
Got it running but can't acces

### ISSUE THREAD

**Issue by tomhoogeveentje** [binhex/arch-delugevpn#5]
I got it running, but I cant seem to acces the web interface..

This is the command I ran to install the container:
docker run -d --cap-add=NET_ADMIN -p 8112:8112 -p 8118:8118 --name=delugevpn -v /media:/data -v /media:/media -v /media/Nori/appdata/DelugeVPN:/config -v /etc/localtime:/etc/localtime:ro -e VPN_ENABLED=yes -e VPN_USER=<username> -e VPN_PASS=<password> -e VPN_REMOTE=nl.privateinternetaccess.com -e VPN_PORT=1194 -e VPN_PROV=pia -e ENABLE_PRIVOXY=yes binhex/arch-delugevpn

And I forwarded 8112 to port 9091 but I can't seem to connect to the web interface.

Did I do something wrong?
Can some one help me please?

**Comment by oddlid** [comment]
I can connect to the web interface from the same host that the docker container runs on, but not from any host in $LAN_RANGE. nmap scan shows ports 8112,8118 as open from the Docker host, but as filtered from hosts in $LAN_RANGE. 
Seems the iptables rules need some adjustment, but I don't have solution myself at the moment.

**Comment by swordfish6975** [comment]
sudo iptables -t nat -D PREROUTING 1

**Comment by Siebes** [comment]
I had this issue too. To circumvent it I just ran Nginx with 

  server {
    listen 8113;
    location / {
      proxy_pass http://localhost:8112;
    }
  }

then you can access it on port 8113

**Comment by msh100** [comment]
I recommend you use `mwldk/go-tcp-proxy` for now to get around this, I schedule the containers with Rancher and therefore can proxy to the service name (resolved by Rancher DNS).

If you just want to quickly get up a container though try:

```
docker run --net="host" mwldk/go-tcp-proxy -r localhost:8112
```

This will listen on port `9999` but you can define something else with `-l`: 
```
-l="localhost:9999": local address
```

**Comment by binhex** [comment]
this should now work internally (if you specify the lan network using the lan_network env var), and also externally if you port forward port 8112 on your router to <ip of host running docker>:8112
