### ISSUE TITLE
How does custom VPN work?

### ISSUE THREAD

**Issue by Redsandro** [binhex/arch-delugevpn#50]
I've recently switched from PIA to a different VPN.
Is there any documentation on how to use the "custom" vpn type? Or can you give a hint? I wouldn't know where to begin.

**Comment by binhex** [comment]
go here https://lime-technology.com/forums/topic/44108-support-binhex-general/ and scroll down to the newbie vpn guide, this is the generic instructions for setting it up for any provider.

**Comment by Redsandro** [comment]
Thanks @binhex. Wow, it kinda just works. All I had to do - this doesn't seem to be in the noob guide, so let me mention it for reference - is remove the password from the personal key. E.g.:

```
$ openssl rsa -in vpnuser.key -out vpnuser.key
Enter pass phrase for vpnuser.key:
writing RSA key
```
