### ISSUE TITLE
iptables_mangle unavailable on QNAP

### ISSUE THREAD

**Issue by sgtsquiggs** [binhex/arch-delugevpn#51]
Hi,

I'm running a QNAP x64 machine and I'm getting the warning about iptables_mangle during startup of the container.

I don't have iptables_mangle available, but I do have ip6table_mangle.

**Comment by binhex** [comment]
ip6table_mangle is the ipv6 version, so that wont do you any good, you need to reach out to whoever supports the qnap and ask them how to do this.
