### ISSUE TITLE
Deluge Settings/Errors on Restart

### ISSUE THREAD

**Issue by Dulanic** [binhex/arch-delugevpn#53]
I am noticing that every day or so the container resets, I am guessing due to the port changing etc... /w PIA. However, when this happens my torrents in the process of downloading go to a error status and have to be rechecked manually. In addition, my selected plugins reset back to default.

I have 2 questions around this:

- Is there any way to make deluge resume when it finds it has to update based on the port or whatever reason? *Update - I see there was a PR for this, so dont think this needs to be answered.

- Is there a way to make my plugin setting persistent? My /config is mapped to a directory to keep things persistent, but the plugins change anyway.

**Comment by binhex** [comment]
So the torrent errors issue has actually been recently fixed, i now do re-checking of torrents in an error state so you might find the latest image fixes this. 

as for plugins being persistent, yes i have had a couple of people mention this, no idea whats going on with that at the moment, i may get some time to dig into that later on.
