### ISSUE TITLE
Some torrents stall until after latest docker image update

### ISSUE THREAD

**Issue by fivestones** [binhex/arch-delugevpn#56]
I did a docker-compose pull (which pulls the newest arch-delugevpn among other docker images) last night and it updated. After restarting arch-delugevpn with the newest image from docker hub, I noticed that many torrents that had stalled and stopped downloading for weeks or months suddenly restarted and were again downloading. What would have made this occur? If, in the future, other torrents stall like this is there a way to get them to start up again other than waiting for a future arch-delugevpn image update?

**Comment by fivestones** [comment]
Actually I discovered that stalled torrents actually start again after just restarting the arch-delugevpn docker image. (i.e., immediately after restarting the image, several torrents that were showing no peers suddenly have peers and are transfering). There were some torrents were still working and transfering as usual before restarting so it wasn't a problem of no connectivity. What would be causing this (torrents to become stalled and show no peers)? How can I keep them from stalling and not need to restart the docker image to get them to start again?
What other info would you need to help me diagnose this?

**Comment by binhex** [comment]
So i have recently improved delugevpn in two areas, firstly it will now detect torrents in an error state and re-check automatically on startup, and secondly i now pass all of the resolved vpn endpoints as ip addresses to openvpn, so it will automatically switch to another one (assuming there is another ip to switch to). so you may find stability is improved, however your issue does sound more like a incoming port issue, what vpn provider are you using (if PIA which endpoint are you connecting to?) and if not PIA how are you getting an incoming port assigned?.

**Comment by Bluglug** [comment]
I am having the same issue on my installation as well. I am using PIA and using US East as the end point.

I actually just had the issue: I have around 20 torrents active at the moment but 9 of those weren't downloading even though they were freshly added yesterday and show seeds on the tracker.
Restarting the docker image caused all the torrents to start downloading now.

**Comment by binhex** [comment]
> I am having the same issue on my installation as well. I am using PIA and using US East as the end point.

pretty sure PIA endpoint US East does NOT support port forwarding, thus your speeds will be low at best and possibly non existent at worst, switch endpoint to one of the following:-

https://helpdesk.privateinternetaccess.com/hc/en-us/articles/219460187-How-do-I-enable-port-forwarding-on-my-VPN-

**Comment by binhex** [comment]
@fivestones  not sure which provider you are using, but the same applies to you, if you are using PIA switch to one of the endpoints in the link above, if you aren't with PIA you will need to sort out how your vpn provider allocates incoming ports and get that working.

**Comment by Bluglug** [comment]
@binhex won't changing to one of those actually lower my speeds since the distance is longer and thus the number of hops adds more overhead.

I didn't have really any issues with slow downloads. I only had an issue where the download would refuse to start.

I just had a download today that was not connected at all and not downloading/uploading. I pause and resumed the download and it started working.

As an aside:
I was able to increase my speeds by removing `comp-lzo` from my .ovpn profile. I have heard that doing the same on the open vpn configuration file itself can also help.

**Comment by binhex** [comment]
> won't changing to one of those actually lower my speeds since the distance is longer and thus the number of hops adds more overhead.

no, number of hops, i.e. latency and download speeds are two seperate things,  remember we are downloading here so latency is of no concern, try switching to a port forward enabled endpoint your speeds will be significantly improved, trust me.
