### ISSUE TITLE
Repeat Plugin

### ISSUE THREAD

**Issue by Dulanic** [binhex/arch-delugevpn#61]
So I have 2 plugins that are causing me issues every time the container resets. Simple Extract adds itself again every single time it resets. And ItConfig has to be ItConfig has to be reeenabled every single time. 

Both work fine /w Deluge outside of the container. Anything I can do to help research why?

![image](https://user-images.githubusercontent.com/2948206/40690408-908ca66e-636c-11e8-89eb-9ee60acecd4d.png)

You can see SimpleExtractor shown 5 times.

**Comment by Dulanic** [comment]
It seems like somehow the container is "caching" the plugin data? I removed the plugins and it still keeps showing up.

![image](https://user-images.githubusercontent.com/2948206/40693635-10e0da0e-637e-11e8-8049-bc88b04b98e4.png)

![image](https://user-images.githubusercontent.com/2948206/40694213-1ff7c086-6381-11e8-91ca-efa3c7a2ca7d.png)

![image](https://user-images.githubusercontent.com/2948206/40694248-4499ad1e-6381-11e8-85c0-b7d02cbdf2f0.png)

**Comment by binhex** [comment]
related to the issue above, for now your only way around this is to stop the container and manually remove the plugins you dont want from the /config/core.conf file and then start the container again.
