### ISSUE TITLE
Deluge Thin Client from computer within LAN

### ISSUE THREAD

**Issue by sda2b** [binhex/arch-delugevpn#68]
Hello,

Is it possible to connect to the dockerized deluge daemon from an other computer within LAN ?
I would like to use Deluge Thin Client on my main laptop to connect to the deluge dockerized instance on my home server.

On my laptop, I disabled classic mode in Deluge and filled the required fields 

Hostname : 192.168.1.40 Port : 58846
Username : localclient
Password : pass found in config/auth

But it doesn't work.

Thanks for your help.

**Comment by FedoraTipper** [comment]
Got the same issue

**Comment by kjrocker** [comment]
@FedoraTipper can you include some details about how you fixed this? I've run into the same problem, trying and failing to connect a deluge client on a different machine on my network to the docker daemon.
