### ISSUE TITLE
Support for Wireguard?

### ISSUE THREAD

**Issue by mpatton125** [binhex/arch-delugevpn#69]
Hey there,

Love the container! A feature request, as per the title - any chance of adding support for Wireguard?
Shouldn't be too hard, I don't imagine as most of your stuff should be adaptable.
I might even give it a shot myself and hit you up with a PR.

M.

**Comment by binhex** [comment]
im afraid this wont get done, there is more to this than meets the eye, and as nearly all vpn providers support openvpn and very few support wireguard i think its a no for now, please feel free to fork my code of course and have a go :-).
