### ISSUE TITLE
[REQUEST] Themes

### ISSUE THREAD

**Issue by HalianElf** [binhex/arch-delugevpn#72]
Is it possible to somehow either expose the themes directory or somehow link it in the config folder so it's not overwritten? I managed to create a new CSS that gives the WebUI a dark theme and as of right now, created a symbolic link in the deluge install directory to the file in my config folder but it would be nice to not have to worry about it when there's updates to the container. If it's not possible, that's fine. I figured it was worth asking. Thanks!

Themes Directory: /usr/lib/python2.7/site-packages/deluge/ui/web/themes

**Comment by TechplexEngineer** [comment]
Just mount the themes directory as a volume
