### ISSUE TITLE
Help with adding a service to DelugeVPN container

### ISSUE THREAD

**Issue by gurabli** [binhex/arch-delugevpn#74]
Hi,
I understand this is off, but I see you are really good at this and you helped so much people.
I use Deluge and Oscam routed over VPN with iptables to prevent leaks, wotks perfectly fine. 
Would lile to move to dockers, but I can't figure out how can I have both Deluge and Oscam in a VPN (PIA) container. I know it is not a good practice to have two processes in a single container, but I don't really want to use two connections to PIA for this. 
What would you suggest, and can I ask for you kind help, while having a beer? :) 

Thanks

**Comment by jshridha** [comment]
I understand you right, you're trying to use two separate containers with one VPN connection. To do that, make sure you have privoxy turned on in your deluge container. Also make sure you expose the privoxy port.

Then in your oscam container, you want to add the environmental variable:
```
 "http_proxy=http://192.168.1.XXX:8119"
```

replacing the ip address and port appropriately. That'll make sure that your oscam container uses privoxy for all http/https requests. You can also specifiy which domains shouldn't use the proxy if you need to access local resources. For example:

```
"no_proxy=*.local,google.com"
```

will cause it to not use the proxy for any domains ending in .com or for google.com. Hopefully that works for you.

**Comment by gurabli** [comment]
Thank you @jshridha
Yes, you got this correct. I want to have a single openvpn client connection, but want at least two dockers to use that connection. One is Deluge, and the other is oscam.
I will give a try to your suggestion. 
Interesting, port 8119 will mean that I can connect every container over the Deluge VPN container?

I need wan side and local access to both webui and Deluge Daemon ports, but only local for oscam is enough.

Best would be to have an nginx Letsencrypt container to handle all the reverse proxy for my containers. Will see how to integrate that.

**Comment by fryfrog** [comment]
Doesn't PIA give you a handful of connections? I use AirVPN and they let me have 10 or 20 and I generally only use 1 or 2.

**Comment by gurabli** [comment]
You get 5 connections with PIA, and yes, I could probably do that. But that is a workaround, which I actually don't like. I am sure I can connect containers and route them over one vpn.

**Comment by fryfrog** [comment]
Yeah, not an unreasonable thing to do.

To keep thing in the "docker way" and to minimize your setup's complexity, I'd suggest running a dedicated openvpn container and pointing everything at *that* instead. That way, all your other images that use vpn won't be interrupted by rTorrent issues and restarts. :)

**Comment by binhex** [comment]
no further comments since 20th sept, closing

**Comment by gurabli** [comment]
> If I understand you right, you're trying to use two separate containers with one VPN connection. To do that, make sure you have privoxy turned on in your deluge container. Also make sure you expose the privoxy port.
> 
> Then in your oscam container, you want to add the environmental variable:
> 
> ```
>  "http_proxy=http://192.168.1.XXX:8119"
> ```
> 
> replacing the ip address and port appropriately. That'll make sure that your oscam container uses privoxy for all http/https requests. You can also specifiy which domains shouldn't use the proxy if you need to access local resources. For example:
> 
> ```
> "no_proxy=*.local,google.com"
> ```
> 
> will cause it to not use the proxy for any domains ending in .com or for google.com. Hopefully that works for you.

Sorry for reopening, just I wonder if I use the proxy aproach from Oscam container, is DNS also tunneled ovet proxy? I don't think so, or I am not sure?
