### ISSUE TITLE
Connect Thin Client with VPN enabled

### ISSUE THREAD

**Issue by gurabli** [binhex/arch-delugevpn#76]
I managed to configure everything I wanted (at this point), except to connect with Thin Client outside from local network, while VPN is enabled. It works when I disable VPN.

Is this possible? If yes, what configuration is needed.

I'm running DelugeVPN on a VPS with Traefik, delugevpn.example.com
Added a new line with user:pass to auth

As I said, if I disable VPN, Thin Clien connects perfectly fine.

Thanks

**Comment by drkdragonarcher** [comment]
This might be a dumb way to do it but the way I got around this is using IP tables to create a SNAT on the host box that just changes traffic coming in on port 58846 to look like it's coming from itself. (Note: I have a firewall in front of this that's blocking all traffic to that port except for specific IPs I allow)

Here's what mine looks like:
SNAT       tcp  -- !192.168.1.0/24        anywhere             tcp dpt:58846 to:192.168.1.131

Let me know if that helps or you need more than that.

**Comment by gurabli** [comment]
@drkdragonarcher Thanks, it makes sense. I'm lost a little bit because of being new to Docker.
I run Deluge docker on a VPS. What IP address should I use in this case?

Lets say the IP of VPS is: 10.10.10.1.
The Docker container's IP is: 172.22.0.2

How would the SNAT command look in this case?

Thanks

**Comment by drkdragonarcher** [comment]
iptables -t nat -A POSTROUTING **! -s 192.168.1.0/24** -p tcp --dport 58846 -j SNAT --to-source 10.10.10.1

You can leave out the part I bolded (! -s 192.168.1.0/24). All that does is tell it not to NAT any traffic coming from 192.168.1.0-255 since if you added the LAN_NETWORK environment variable, the container will already be handling these properly. You'd obviously want to change that to match whatever you LAN_NETWORK is set to if you're using that.

**Comment by gurabli** [comment]
Thanks, very helpful, will look into this.
You said you are running a firewall, I guess you do this on the host. I read there are certain issues with UFW and Docker. Amy particular recommendations on that?

**Comment by drkdragonarcher** [comment]
I mean physical firewall in front of my server. IPtables is also a firewall though, you can just do the filtering with it. There's a lot of guides out there for it but [this one](https://www.howtogeek.com/177621/the-beginners-guide-to-iptables-the-linux-firewall/) looks pretty good to start with.

**Comment by binhex** [comment]
no comments since 28th sept closing.
