### ISSUE TITLE
OpenVPN docker without Deluge

### ISSUE THREAD

**Issue by gurabli** [binhex/arch-delugevpn#78]
I really like your work. One thing I would prefer is to have a separate OpenVPN and Deluge container. Could you create an OpenVPN container with all the options you have now (Pivoxy, port forwarding, firewall, etc), but exclude Deluge? All the other containers could use this with - - net=container:<name> and would have all the traffic routed over vpn container.

Thanks

**Comment by binhex** [comment]
this is actually more work than it looks and right now i dont have the time to do this, feel free to fork and have a go.
