### ISSUE TITLE
Way to use same Port Forward to both your Deluge & rTorrent container?

### ISSUE THREAD

**Issue by restalfep** [binhex/arch-delugevpn#79]
I'm thinking of running rtorrent for long-term seeding & Deluge for automation like Sonarr, short term seeding, etc. Deluge seems to slow down significantly with lots of seeds and thinking rtorrent may be better for that.

The issue is that many private trackers don't let you connect from 2 IPs so I can't open the VPN 2x. Is there a way to make it so when DelugeVPN container starts it also sends the port that should be added to rTorrentVPN container? 

At first I was going to use the http_proxy through privoxy env variable but realized then the port would never be updated on 1 container (i.e. DelugeVPN would update Deluge but rTorrent would never know what port to forward).

**Comment by binhex** [comment]
Im sorry this is impossible in its current configuration.

**Comment by restalfep** [comment]
No problem. Realized that most private trackers actually DO allow 2 ips at same time. Just not two accounts per ip so it’s no problem opening both containers. Thanks for the great work!!

**Comment by binhex** [comment]
no probs.
