### ISSUE TITLE
VPN_OPTIONS enclosed in single quotes causes VPN to not start

### ISSUE THREAD

**Issue by mike391** [binhex/arch-delugevpn#83]
When you specify VPN_OPTIONS, they are enclosed in single quotes when starting openvpn and cause it to fail when starting:
```
/usr/bin/openvpn --daemon --reneg-sec 0 --mute-replay-warnings --auth-nocache --setenv VPN_PROV 'pia' --setenv DEBUG 'true' --setenv VPN_DEVICE_TYPE 'tun0' --setenv VPN_REMOTE 'nl.privateinternetaccess.com' --script-security 2 --up /root/openvpnup.sh --up-delay --up-restart --writepid /root/openvpn.pid --remap-usr1 SIGHUP --log-append /dev/stdout --pull-filter ignore 'up' --pull-filter ignore 'down' --pull-filter ignore 'route-ipv6' --pull-filter ignore 'ifconfig-ipv6' --pull-filter ignore 'tun-ipv6' --pull-filter ignore 'persist-tun' --pull-filter ignore 'reneg-sec' --remote 46.166.188.223 1198 udp --remote 46.166.138.172 1198 udp --remote 109.201.154.141 1198 udp --remote 46.166.137.237 1198 udp --remote 109.201.154.151 1198 udp --remote 46.166.138.142 1198 udp --remote 46.166.138.143 1198 udp --remote 46.166.190.130 1198 udp --remote 46.166.138.153 1198 udp --remote 109.201.154.152 1198 udp --remote 46.166.190.219 1198 udp --remote 109.201.154.189 1198 udp --remote 185.107.44.30 1198 udp --remote-random --keepalive 10 60 --setenv STRICT_PORT_FORWARD 'yes' --disable-occ --auth-user-pass credentials.conf '--inactive 3600 --ping 10 --ping-exit=60' --cd /config/openvpn --config '/config/openvpn/Netherlands.ovpn'
```

**Comment by binhex** [comment]
Its got nothing to do with single quotes, VPN_OPTIONS is to pass in advanced openvpn options to the client, unless you know what you are doing you should NOT use this option, most likely you are supplying invalid options and thus it wont start (cmd line above does not show what you were trying to pass in as a value for VPN_OPTIONS).

**Comment by mike391** [comment]
I was using these as my VPN_OPTIONS: 
VPN_OPTIONS=--inactive 3600 --ping 10 --ping-exit 60

I want the VPN to reconnect in case it ever disconnects

**Comment by mike391** [comment]
Ah okay, got it all working then. You've done an awesome job on this :)

**Comment by binhex** [comment]
enjoy :-), btw if you want to test the reconnection then simply pull the power on your mode/router and you should see once your connection is up the vpn will reconnect with 30 seconds - no ip leakage due to iptable rules at ANY time :-)
