### ISSUE TITLE
Won't copy custom openvpn files 

### ISSUE THREAD

**Issue by erosenberg** [binhex/arch-delugevpn#85]
I'm using ExpressVPN and downloaded the openvpn file (for Switzerland 2, specifically), mapped the folder its in as a volume (`/ovpn/expressvn/<file.ovpn>:/config/openvpn`) and for some reason, when I set `VPN_ENABLED` to `yes`, my container constantly tries to restart and won't let me `exec` into bash. When I set it to `no`, I am able to `exec` into the container, and can see that the `ovpn` file is in fact not being properly referred to in the volume I set up.

When I set `VPN_PROV`, should I set it to `custom`, or `expressvpn`?
Currently using `expressvpn` so maybe that's why it's throwing an error and not mapping the file properly?

**Comment by binhex** [comment]
if this is a container side path then it wont work:-

> /ovpn/expressvn/<file.ovpn>:/config/openvpn

the openvpn config file must be in /config/openvpn/<openvpnfile> see the readme for example run command.

in answer to your question, it should be custom, again see the readme.
