### ISSUE TITLE
Interface eno1 on RHEL 7 or Ubuntu 18

### ISSUE THREAD

**Issue by therealgill** [binhex/arch-delugevpn#89]
I am attempting to deploy the container on a fresh install of Centos 7 with selinux disabled. Since RHEL 7, and Ubuntu 18, local NICs are labeled using the eno# convention, not the eth# convention. I notice that the source of the docker file points to[ /run/root/iptable.sh](https://github.com/binhex/arch-delugevpn/blob/master/run/root/iptable.sh#L156) for iptables rules. And, while there is some code in there to determine the appropriate name of the NICs, when the iptables rules are actually entered, they are entered using eth0, which is hardcoded. Is there a chance that you could look at that specific script? Specifically, lines: 90, 93, 94, 103, 107, 134, 146, 147, 156, and 160.

**Comment by binhex** [comment]
Yeah i saw your comment on the forum, took a look at the code and have reworked it to identify the adapter name as opposed to hard coded, ive punted the change up but as of yet i haven't rebuilt the image, take a look at the changes and see what you think.

**Comment by binhex** [comment]
image rebuilt, if you think this has not resolved the issue then let me know.
