### ISSUE TITLE
Can't Access Deluge Web UI

### ISSUE THREAD

**Issue by raymondshiner** [binhex/arch-delugevpn#90]
I keep getting the following error when trying to reach the web UI from docker on my ubuntu server.

```
deluge_vpn_1  | 2019-01-05 05:31:23,023 DEBG 'start-script' stdout output:
deluge_vpn_1  | [warn] Response code 000 from curl != 2xx
deluge_vpn_1  | [warn] Exit code 7 from curl != 0
deluge_vpn_1  | [info] 7 retries left
deluge_vpn_1  | [info] Retrying in 10 secs...
deluge_vpn_1  |
```

I have tried rebooting containers multiple times, deleting and replacing my cert and pem files, and have updated and upgraded my server to the latest version. I even manually backuped my relevant data and did a full reinstall of the ubuntu server itself. Can't figure out why I keep getting this error message. 

Don't know how it started, just rebooted my Server one day after a power flicker knocked it out I think and I was no longer able to connect to Deluge UI.

**Comment by binhex** [comment]
see here:- https://forums.unraid.net/topic/44109-support-binhex-delugevpn/?do=findComment&comment=433617
