### ISSUE TITLE
WebUI on different network interface

### ISSUE THREAD

**Issue by julianflapper** [binhex/arch-delugevpn#91]
Hi,

I'm trying to access the WebUI from eth1 rather than eth0, but it doesn't seem to work. Perhaps you know what I am doing wrong.
I repeated the iptables rules (3x INPUT, 3x OUTPUT) from the container's initialization script for eth1 and the IP belonging to that (172.18.0.0/16).

However, while I can ping 172.18.0.3, I can't curl the webUI (curl http://172.18.0.3:8112). Curl does work for the eth0 address, which is 172.19.0.2. Curl also works on localhost inside the container, and on the localhost:8112 of the Docker host if I bind that port to the container. So it seems traffic can go in and out through that interface. It's the 172.18.0.3 that's not working for some reason.

I specified the lan network setting as follows:
```LAN_NETWORK=172.18.0.0/16,10.10.0.0/16,172.19.0.0/16```
to include both eth0 and eth1, and the network of the Docker host.

This is the iptables -L output:
```bash
Chain INPUT (policy DROP)
target     prot opt source               destination
ACCEPT     all  --  anywhere             anywhere
ACCEPT     all  --  172.19.0.0/16        172.19.0.0/16
ACCEPT     udp  --  anywhere             anywhere             udp spt:openvpn
ACCEPT     tcp  --  anywhere             anywhere             tcp dpt:8112
ACCEPT     tcp  --  anywhere             anywhere             tcp spt:8112
ACCEPT     tcp  --  172.18.0.0/16        anywhere             tcp dpt:58846
ACCEPT     tcp  --  10.10.0.0/16         anywhere             tcp dpt:58846
ACCEPT     tcp  --  172.21.0.0/16        anywhere             tcp dpt:58846
ACCEPT     tcp  --  192.168.0.0/16       anywhere             tcp dpt:58846
ACCEPT     icmp --  anywhere             anywhere             icmp echo-reply
ACCEPT     all  --  anywhere             anywhere
ACCEPT     all  --  172.18.0.0/16        172.18.0.0/16
ACCEPT     tcp  --  anywhere             anywhere             tcp dpt:8112
ACCEPT     tcp  --  anywhere             anywhere             tcp spt:8112

Chain FORWARD (policy ACCEPT)
target     prot opt source               destination

Chain OUTPUT (policy DROP)
target     prot opt source               destination
ACCEPT     all  --  anywhere             anywhere
ACCEPT     all  --  172.19.0.0/16        172.19.0.0/16
ACCEPT     udp  --  anywhere             anywhere             udp dpt:openvpn
ACCEPT     tcp  --  anywhere             anywhere             tcp dpt:8112
ACCEPT     tcp  --  anywhere             anywhere             tcp spt:8112
ACCEPT     tcp  --  anywhere             172.18.0.0/16        tcp spt:58846
ACCEPT     tcp  --  anywhere             10.10.0.0/16         tcp spt:58846
ACCEPT     tcp  --  anywhere             172.21.0.0/16        tcp spt:58846
ACCEPT     tcp  --  anywhere             192.168.0.0/16       tcp spt:58846
ACCEPT     icmp --  anywhere             anywhere             icmp echo-request
ACCEPT     all  --  anywhere             anywhere
ACCEPT     all  --  172.18.0.0/16        172.18.0.0/16
ACCEPT     tcp  --  anywhere             anywhere             tcp dpt:8112
ACCEPT     tcp  --  anywhere             anywhere             tcp spt:8112

```

**Comment by jadrian2006** [comment]
Show your routing table (netstat -r) 

You could be missing a route for that network, the default route sends all traffic toward the tun interface. So if you are not on the original subnet that could be the reason.

Another thing that is a bit odd is you have an eth1 on a docker container? 
eth0 should be the docker network, tun0 should be your vpn tunnel and lo is your loopback.

Bit more information to isolate why it doesn't work.
