### ISSUE TITLE
Connection speed barely exceeds 1MiB/s on PIA Germany Berlin

### ISSUE THREAD

**Issue by rshackleton** [binhex/arch-delugevpn#93]
I believe the configuration is correct, speed test from the docker host is around 80mb/s.

Not sure what logs to share that would be useful.

Also tried other PIA servers (France and Frankfurt) and also UK Manchester with port forwarding disable. 

All were ultimately failing to exceed 1MiB/s.

**Comment by rshackleton** [comment]
I get the impression it may be a port forwarding issue within my network, however, which port should be forwarded? From what I can see the port is random due to the VPN.

**Comment by rshackleton** [comment]
Closing as I had missed to link to the support forum, will post there instead!

**Comment by rshackleton** [comment]
In case anyone finds this in future with a similar issue - I resolved it by adding the [ltConfig](https://github.com/ratanakvlun/deluge-ltconfig) plugin.

My issue was related to uTP which can be disabled by disabling these two settings with that plugin:

enable_outgoing_utp
enable_incoming_utp

**Comment by OscarVanL** [comment]
I also disabled `mixed_mode_algorithm` which helped fix the slow speeds.
