### ISSUE TITLE
Invalid perm 

### ISSUE THREAD

**Issue by Raiu** [binhex/arch-delugevpn#99]
vpn_external_ip.txt is updated/created with the wrong permission.

`2019-03-10 14:02:31,318 DEBG 'watchdog-script' stderr output:
/home/nobody/getvpnextip.sh: line 9: /home/nobody/vpn_external_ip.txt: Permission denied`

`-rw------- 1 root   root    13 Mar 10 14:02 vpn_external_ip.txt`

all other files in /home/nobody is set correctly

**Comment by binhex** [comment]
This will be a configuration issue, check the umask remember umask != chmod

**Comment by binhex** [comment]
invalid fix, you are setting chmod on a txt file not a script, not only that but your issue is related to UMASK, check the readme.md for an example value.
